### ISSUE TITLE
嵌套使用情况下的BUG

### ISSUE THREAD

**Issue by xudehuai** [pujiaxin33/JXCategoryView#10]
嵌套使用情况下，由子SegmentView切换导致父SegmentView切换时，快速左右滑动，响应的为父SegmentView的切换，该处逻辑稍有问题。
PS：功能挺多，辛苦了

**Comment by pujiaxin33** [comment]
你好，通过文字不太明白你说的那个bug，如何复现。
方便的话，加入QQ群： 112440151   通过录制屏幕告知一下，可能就能明白了

**Comment by pujiaxin33** [comment]
最新版本已经修复，谢谢反馈
