### ISSUE TITLE
为什么不通过addChildViewController来管理，而是直接使用self.view呢？

### ISSUE THREAD

**Issue by SmallMX** [pujiaxin33/JXCategoryView#100]
这样无法在item中直接使用self.navigationController，不是很方便啊!

**Comment by pujiaxin33** [comment]
在以前的版本封装过一个类`JXCategoryListVCContainerView`，这个类就是列表是`UIViewController`类专门使用的。但是有几点问题促使我最终废弃了它：
1.它要求列表只能是UIViewController类，不支持UIView。但是很多现有业务列表有用UIView封装的，所以灵活性不够高；
2.要实现childController的所有生命周期方法，需要添加需要额外的API，不方便使用。

但是，你的列表是UIViewController，你可以自己再返回列表代理方法里面，加上addChildViewController方法，代码如下：
```Objective-C
- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index {
    LoadDataListContainerListViewController *listVC = [[LoadDataListContainerListViewController alloc] init];
    [self addChildViewController:listVC];
    return listVC;
}
```
这样也可以实现你的需求
