### ISSUE TITLE
跳转到不同VC

### ISSUE THREAD

**Issue by shuiliang** [pujiaxin33/JXCategoryView#103]
作者您好，运行demo 后 切换视图后都是跳转到 ListViewController里，我的需求类似 "特殊效果"里的"嵌套使用"，主题一 有3个不同的VC，这3个VC布局啥的都不一样，主题二有5个VC，VC布局都一样 。。。  这时候我怎么写跳转呢？

**Comment by pujiaxin33** [comment]
跳转都是按照同样逻辑处理

**Comment by hselenat** [comment]
作者您好，请问如何单独设置每个title对应列表的风格呢

**Comment by pujiaxin33** [comment]
在下面这个代理方法里面，根据不同的index，就知道是什么title，再返回对应的列表即可。
```Objective-C
- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index;
```

**Comment by shuiliang** [comment]
谢谢您之前的回复，后来又碰到一个新问题  
![image](https://user-images.githubusercontent.com/17922774/54507453-59a0e600-497c-11e9-90fa-c18dd5f231e6.png)

![image](https://user-images.githubusercontent.com/17922774/54507470-7fc68600-497c-11e9-9c09-58285a8b7b10.png)

我开始以为我自己写的布局有问题，后来我是把您的demo 里面的文件放进了 我的项目里面跑的，它也会向上偏移

**Comment by pujiaxin33** [comment]
向上偏移？截图一下呢？

**Comment by shuiliang** [comment]
我截图了，刚刚图二里面的二级标题， 香蕉，苹果，荔枝   都隐藏在导航后了😀

**Comment by pujiaxin33** [comment]
你自己把frame的y写成64嘛，布局是自己负责的

**Comment by shuiliang** [comment]
![image](https://user-images.githubusercontent.com/17922774/54509095-4d6c5700-4983-11e9-8a7b-c3c0972b59a6.png)

可以了，谢谢
