### ISSUE TITLE
listDidDisappear方法调用错误

### ISSUE THREAD

**Issue by liangjinbai** [pujiaxin33/JXCategoryView#104]
JXCategoryView->JXCategoryListCollectionContainerView.m

- (void)collectionView:(UICollectionView *)collectionView didEndDisplayingCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath {
   id<JXCategoryListCollectionContentViewDelegate> list = _validListDict[@(indexPath.item)];
    if (list && [list respondsToSelector:@selector(listDidAppear)]) {
        [list listDidDisappear];
    }
}
该判断有误，调用的方法和判断的方法不是同一个

**Comment by pujiaxin33** [comment]
非常感谢，已修复
