### ISSUE TITLE
能pod进自己的工程项目中，但是在cocoapods上search不到？

### ISSUE THREAD

**Issue by Azraeltulips** [pujiaxin33/JXCategoryView#106]
能pod进自己的工程项目中，但是在cocoapods上search不到？

**Comment by shimminZ** [comment]
真的搜不到啊

**Comment by Azraeltulips** [comment]
![image](https://user-images.githubusercontent.com/25146432/54740118-5fedc700-4bf5-11e9-8bec-a47c5289b191.png)

**Comment by Azraeltulips** [comment]
你也搜不到？但是可以直接pod进工程里面

**Comment by shimminZ** [comment]
你用这个库了吗，看时间是7个月之前上传的。靠谱吗

**Comment by pujiaxin33** [comment]
需要pod repo update 更新本地索引库

**Comment by Azraeltulips** [comment]
正准备用，也是一个同事推荐的。
好的，我试试pod repo update，谢谢

**Comment by shimminZ** [comment]
@pujiaxin33 执行过了  pod  search  还是搜不到

**Comment by pujiaxin33** [comment]
试一下这个方案呢：[https://www.jianshu.com/p/9add72f11df6](https://www.jianshu.com/p/9add72f11df6)
不能的话再去网上搜索一下，关键字“pod search找不到”

**Comment by Azraeltulips** [comment]
@shimminZ 先移除rm ~/Library/Caches/CocoaPods/search_index.json，在pod search试试。我刚才这样做成功搜到了

**Comment by shimminZ** [comment]
移除以后 pod search

**Comment by shimminZ** [comment]
移除之后pod search 停在这个地方不动了，我哭了 
shimin-zhang:~ shimin_zhang$ pod search AFNetworking
Creating search index for spec repo 'gitee-lz156-qymspecs'.. Done!
Creating search index for spec repo 'master'..
