### ISSUE TITLE
defaultSelectedIndex这个默认选中index，但是视图控制器怎么是一片空白，视图控制器怎么选初始化时默认的

### ISSUE THREAD

**Issue by myevery** [pujiaxin33/JXCategoryView#107]
defaultSelectedIndex这个默认选中index，但是视图控制器怎么是一片空白，视图控制器怎么选初始化时默认的，想进入程序选择第一个为默认的，但是视图控制器没有改变，
self.titles = @[@"标讯", @"资讯",@"服务"];
    self.myCategoryView.defaultSelectedIndex = 1;
    self.myCategoryView.frame = CGRectMake(0, 0, 180, 40);
    self.myCategoryView.titles = self.titles;
    self.myCategoryView.cellSpacing = 0;
    self.myCategoryView.cellWidth = 180/3;
    self.myCategoryView.titleColor = c999999;
    self.myCategoryView.titleFont = [UIFont systemFontOfSize:14 weight:UIFontWeightRegular];
    self.myCategoryView.titleSelectedColor = c141414;
    self.myCategoryView.titleSelectedFont = [UIFont systemFontOfSize:17 weight:UIFontWeightMedium];
    self.myCategoryView.titleColorGradientEnabled = YES;
    self.myCategoryView.titleLabelZoomEnabled = YES;
    self.myCategoryView.titleLabelZoomScale = 1.3;

**Comment by pujiaxin33** [comment]
需要同时设置listContainerView.defaultSelectedIndex = 1   其他注意事项文档里面有写哈

**Comment by myevery** [comment]
谢谢
