### ISSUE TITLE
使用 JXCategoryListCollectionContainerView 出现错误

### ISSUE THREAD

**Issue by JonesCxy** [pujiaxin33/JXCategoryView#108]
您好,使用 collection 布局后 出现  Terminating app due to uncaught exception 'CALayerInvalid', reason: 'layer <CALayer: 0x283348420> is a part of cycle in its layer tree' 错误

**Comment by JonesCxy** [comment]
实现这个方法时会出现以上错误:
- (id<JXCategoryListCollectionContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index {
//    LoadDataListCollectionListViewController *listVC = [[LoadDataListCollectionListViewController alloc] init];
//    listVC.naviController = self.navigationController;
    
//    ListViewController *list = [ListViewController new];
    return self;
}

**Comment by pujiaxin33** [comment]
不可以返回self，需要返回列表的新实例，可以看下api说明哈。你返回self，就循环添加了。因为self添加了JXCategoryListCollectionContainerView，然后JXCategoryListCollectionContainerView又添加了self

**Comment by JonesCxy** [comment]
好的,谢谢,发完邮件,就看到说明了,哈哈
