### ISSUE TITLE
pod install出错

### ISSUE THREAD

**Issue by johnchen** [pujiaxin33/JXCategoryView#109]
Installing JXCategoryView (1.3.0)

[!] Error installing JXCategoryView
[!] /usr/bin/git clone https://github.com/pujiaxin33/JXCategoryView.git /var/folders/jb/hw2wd5d54jlbntf0c02ctt700000gn/T/d20190326-854-cj9f2b --template= --single-branch --depth 1 --branch 1.3.0

Cloning into '/var/folders/jb/hw2wd5d54jlbntf0c02ctt700000gn/T/d20190326-854-cj9f2b'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by pujiaxin33** [comment]
“fatal: The remote end hung up unexpectedly” 看样子是远端服务器问题
1、可以多尝试一下；
2、先试一下 pod repo update;
3、翻墙试一下；

**Comment by johnchen** [comment]
这几种方式都试了，还是不行

**Comment by pujiaxin33** [comment]
你百度下报错的关键信：“error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54”
看看网上的解决方案呢

**Comment by zhao1zhihui** [comment]
我也是你这个库pod不下来其他的可以
