### ISSUE TITLE
某些机型 出现label 模糊的问题

### ISSUE THREAD

**Issue by maxwell44** [pujiaxin33/JXCategoryView#111]
在IPhone6 大小机型会出现 label 模糊的问题。

**Comment by YanPengImp** [comment]
能提供更加详细的描述吗，什么情况下出现的，什么字符，最好有图片可以看下。

**Comment by maxwell44** [comment]
我数据源是指定的四个 未选中是14号字 选中是15号字 图片详情我已经发送到你的邮箱。

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/55300988-f2e7f600-546c-11e9-9bd2-c778c4c4f565.png)

**Comment by pujiaxin33** [comment]
请问是哪个版本呢？

**Comment by pujiaxin33** [comment]
使用titleFont和titleSelctedFont两个属性吗？

**Comment by maxwell44** [comment]
是使用titleFont和titleSelctedFont  iOS版本是10.3.3 我还看了公司其他测试机 仅限于iPhone6 7 这种机型会出现这种情况




| |
Maxwell Yu
|
|
邮箱：maxwell44@126.com
|
在2019年04月01日 11:00，暴走的鑫鑫 写道：

使用titleFont和titleSelctedFont两个属性吗？

**Comment by pujiaxin33** [comment]
JXCategoryView版本号呢？

**Comment by maxwell44** [comment]
1.1.3😅




| |
Maxwell Yu
|
|
邮箱：maxwell44@126.com
|
在2019年04月01日 11:03，暴走的鑫鑫 写道：

JXCategoryView版本号呢？

**Comment by pujiaxin33** [comment]
你尝试更新到最新版本1.3.0呢？
如果只是使用titleFont和titleSelectedFont两个顺序性，是不可能有模糊问题的。
你更新到最新版本试试
