### ISSUE TITLE
你好，接受到内存警告后，出现闪退问题。

### ISSUE THREAD

**Issue by HanksHu** [pujiaxin33/JXCategoryView#112]
你好，用的是JXCategoryView', '1.2.9'版。iPhone6plus手机。
<img width="912" alt="屏幕快照 2019-03-29 下午2 01 57" src="https://user-images.githubusercontent.com/16836336/55212780-00626d80-522c-11e9-900e-d5fa2439e25b.png">

我猜应该是`setObject:`方法时，`currentList`为`nil`。
```
- (void)didReceiveMemoryWarningNotification:(NSNotification *)notification {
    [_lock lock];
    for (NSNumber *index in _validListDict) {
        if (index.integerValue != _currentIndex) {
            id<JXCategoryListContentViewDelegate> list = _validListDict[index];
            [[list listView] removeFromSuperview];
        }
    }
    id<JXCategoryListContentViewDelegate> currentList = _validListDict[@(_currentIndex)];
    [_validListDict removeAllObjects];
    [_validListDict setObject:currentList forKey:@(_currentIndex)];
    [_lock unlock];
}
```

**Comment by YanPengImp** [comment]
感谢您提出的问题，应该是触发内存警告的时候刚好currentIndex也改变了，但是加锁之后_vaildListDict还没有添加新的index键值对，导致取出来的是nil。我们会在下一个版本中修复这个bug。
你如果急需解决这个问题可以在92行中修改为：
`[_lock lock];`
`self.currentIndex = defaultSelectedIndex;`
`[_lock unlock];`
在154行中修改为：
`[_lock lock];`
`self.currentIndex = index;`
`id<JXCategoryListContentViewDelegate> list = _validListDict[@(index)];`
`[_lock unlock];`

**Comment by HanksHu** [comment]
没想到能回复这么快呢。谢谢。

**Comment by gzdaxiong** [comment]
你好，用的是JXCategoryView', '1.2.8'版。iPhone6plus手机。

按你的意见修改 还是不行.

- (void)didReceiveMemoryWarningNotification:(NSNotification *)notification {
    [_lock lock];
    for (NSNumber *index in _validListDict) {
        if (index.integerValue != _currentIndex) {
            id<JXCategoryListContentViewDelegate> list = _validListDict[index];
            [[list listView] removeFromSuperview];
        }
    }
    id<JXCategoryListContentViewDelegate> currentList = _validListDict[@(_currentIndex)];
    [_validListDict removeAllObjects];
    [_validListDict setObject:currentList forKey:@(_currentIndex)];
    [_lock unlock];
}

这句
[_validListDict setObject:currentList forKey:@(_currentIndex)];
中的@(_currentIndex) 修改为NSString会不会好些 因为我跟踪到_currentIndex=0 出现闪退

谢谢

**Comment by gzdaxiong** [comment]
你好，用的是JXCategoryView', '1.2.8'版。
也是同样的问题,我采用您的处理方式,还是出现闪退,不知道是不是我处理不对的问题.
我做了下面的修改:
- (void)didReceiveMemoryWarningNotification:(NSNotification *)notification {
    [_lock lock];
    for (NSNumber *index in _validListDict) {
        if (index.integerValue != _currentIndex) {
            id<JXCategoryListContentViewDelegate> list = _validListDict[index];
            [[list listView] removeFromSuperview];
        }
    }
    id<JXCategoryListContentViewDelegate> currentList = _validListDict[@(_currentIndex)];
    if(nil != currentList){
        [_validListDict removeAllObjects];
        [_validListDict setObject:currentList forKey:@(_currentIndex)];
    }
    [_lock unlock];
}

不知道这样处理 会不会导致新的问题 谢谢!

**Comment by HanksHu** [comment]
我觉得还是有必要判断下是否为nil。

**Comment by YanPengImp** [comment]
判断一下是否为nil更加保险。我这边测试添加定时器10秒触发一次内存泄露也没出现crash，不知道你们是在哪种情况下出现的crash呢。

**Comment by HanksHu** [comment]
当时，我的手机(6sp)是没有复现的。但是bugly中捕捉的挺多的，基本上所有的机型都有，
![FireShot Capture 010 --Bugly - bugly qq com](https://user-images.githubusercontent.com/16836336/55302435-b7045f00-5473-11e9-8f9f-7e88b774c16d.png)

**Comment by pujiaxin33** [comment]
已对nil进行了判断处理
