### ISSUE TITLE
JXCategoryView优化

### ISSUE THREAD

**Issue by xiaoFan125** [pujiaxin33/JXCategoryView#113]
建议在标题列表右侧添加一个可选择的功能按钮

**Comment by pujiaxin33** [comment]
你想要的效果，类似于【今日头条】首页，最右侧有一个按钮，点击之后就是排序界面？

**Comment by xiaoFan125** [comment]
类似微博最右侧功能按钮，点击可以做其他操作。单独使用JXCategoryView的时候可以通过设置JXCategoryTitleView的frame，再在右侧添加一个button实现，但是使用JXPagerView再套用JXCategoryView时，设置JXCategoryTitleView的frame不起作用

**Comment by pujiaxin33** [comment]
只需要新增一层绿色视图包装一下即可，如下图所示：
![image](https://user-images.githubusercontent.com/12654640/55313265-ef1e9880-5499-11e9-91cc-24c75da38e94.png)

**Comment by xiaoFan125** [comment]
问题解决了，感谢作者的解答。
