### ISSUE TITLE
cell多行怎么处理

### ISSUE THREAD

**Issue by 287291867** [pujiaxin33/JXCategoryView#115]
cell多行怎么处理，类似网易云阅读分类界面的分类

**Comment by pujiaxin33** [comment]
如果是初次加载指定默认页面，需要把categoryView.defaultSelectedIndex和listContainerView.defaultSelectedIndex都设置为同一个值

**Comment by pujiaxin33** [comment]
我体验了网易云阅读中“两行分类”的效果，理论上是可行的，但是很难处理，介于实现成本与其特殊性。只能提供一个思路给你，你可以尝试修改源码实现其效果：
1.将JXCategoryView内部的CollectionView的layout.direction设置为垂直方向；
2.自定义indicatorLineView，在每一行都添加一个，然后根据contentScrollView的滚动，特殊处理。
