### ISSUE TITLE
选项只有两三个也是按全屏宽度适应怎么根据文字宽度适应

### ISSUE THREAD

**Issue by 287291867** [pujiaxin33/JXCategoryView#116]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/19721013/55374627-be8f3b00-553b-11e9-85d1-e5eb318c43c8.png">

**Comment by 287291867** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/19721013/55374674-ed0d1600-553b-11e9-9878-e0b528074d83.png">

**Comment by 287291867** [comment]
找到了

**Comment by LSK1994** [comment]
> 找到了

怎么做的

**Comment by LSK1994** [comment]
我想一行5个 每个cell宽度为 屏幕宽度/5

**Comment by LSK1994** [comment]
> > 找到了
我想一行5个 每个cell宽度为 屏幕宽度/5

**Comment by pujiaxin33** [comment]
cellWidth=screenWidth/5;

**Comment by 287291867** [comment]
averageCellSpacingEnable这个属性设置成NO
