### ISSUE TITLE
[Feature Request]希望增加delegate，控制是否可以点击cell

### ISSUE THREAD

**Issue by hstdt** [pujiaxin33/JXCategoryView#118]
**Feature描述**
用于控制是否可进行点击，否则需要还原selectedIndex。

**参考效果**
无

**其他补充**
无

**Comment by pujiaxin33** [comment]
比如有5个tab，规定第3个不能点击。那我通过从列表2滚动到列表3又怎么处理呢?毕竟第3个列表是存在的

**Comment by hstdt** [comment]
@pujiaxin33 点击的时候控制，滚动的时候不走这个delegate。因为有这种需求的话，应该不需要开启滚动功能的，交互逻辑也说不通。

```
- (BOOL)categoryView:(JXCategoryBaseView *)categoryView canClickItemAtIndex:(NSInteger)index;
```

**Comment by pujiaxin33** [comment]
等于说不能点击的那个tab，就没有真实的列表内容可展示，既不可以通过点击切换，又不可以通过滚动切换。等于那个不能点击的tab就只能看了？我理解的正确不

**Comment by hstdt** [comment]
是的，类似于`textField:shouldChangeCharactersInRange`这样

**Comment by pujiaxin33** [comment]
有点好奇这种需求的应用场景？同时会考虑该需求的实现价值

**Comment by hstdt** [comment]
如果我手动去设置index其实也可以，但是动画会很奇怪
![animate](https://user-images.githubusercontent.com/10215098/55448187-64ed4600-55f9-11e9-82aa-5fa3e09897be.gif)

**Comment by pujiaxin33** [comment]
为什么城市不允许点击呢？

**Comment by hstdt** [comment]
业务逻辑的话，就是没选择省，不予许选择城市

**Comment by hstdt** [comment]
尝试提交了一个pull

**Comment by pujiaxin33** [comment]
我回复了一些建议，你看一下呢？
我理解到你的应用场景，就是把CategoryView当做segmentedControl来用

**Comment by hstdt** [comment]
是的，pull已修改

**Comment by luo-h** [comment]
我也有这个需求，后面某些item不准点击，也不准左滑，前面可以点击和左右滑动的不影响，题主怎么处理的啊

**Comment by pujiaxin33** [comment]
@luo-h  有一个canClick代理方法，你自己找一下
