### ISSUE TITLE
指示器渐变色

### ISSUE THREAD

**Issue by haoXu1990** [pujiaxin33/JXCategoryView#12]
您好， 能不能添加一个指示器渐变色的功能，最近产品看上了书旗小说书城页面顶部导航栏的那种切换效果，我看了下您的源码，能力有限没实现效果

**Comment by haoXu1990** [comment]
@pujiaxin33  感谢您的回复，当所有页面加载成功，您把所有页面向上滑动到导航栏背景为白色的时候，在左右滑动切换页面的时候会看到下面的指示器线条是会有颜色渐变的， 只修改背景颜色达不到这种效果

**Comment by pujiaxin33** [comment]
纳尼，这是什么产品经理想出来的效果，你从男生滚动到二次元，是颜色渐变过滤，一但选中二次元，又变成了白色。
一会儿渐变，一会儿跳变，我也是服了

**Comment by pujiaxin33** [comment]
我感觉是不是程序bug啊，如果全是渐变的话，还是很简单的

**Comment by haoXu1990** [comment]
@pujiaxin33  最神奇的是被我们的产品看到了，还非要一模一样的，商量了半天我说最多实现一个指示器线条渐变色

**Comment by pujiaxin33** [comment]
如果只是渐变色，就是放一个渐变色layer，然后把lineView当做它的mask控制显示范围。你参考下qq红点效果，JXCategoryIndicatorBallView被添加到UICollectionView上面，它的frame是(0,0,0,0)。只是控制两个红点视图的frame，即使它们超出了JXCategoryIndicatorBallView也可以被显示出来。你再尝试一下呢，不行明天再call我。

**Comment by haoXu1990** [comment]
@pujiaxin33  好的感谢您的指点，我去试试

**Comment by pujiaxin33** [comment]
稍等，我有个想法，就是把渐变色layer放到JXCategoryIndicatorLineView上面，根据手势进度渐变layer的frame。你先试试吧，我明天抽空弄一下

**Comment by pujiaxin33** [comment]
老哥，加入QQ群： 112440151  渐变色基本搞定了，我把文件发给你

**Comment by haoXu1990** [comment]
@pujiaxin33 非常感谢您花费时间处理我的问题。
