### ISSUE TITLE
我想5个title，每个title的宽度为 屏幕宽/5，不想自适应宽度，如何解决

### ISSUE THREAD

**Issue by LSK1994** [pujiaxin33/JXCategoryView#120]
求助

**Comment by pujiaxin33** [comment]
cellWidth = screenWidth/5

**Comment by LSK1994** [comment]
![image](https://user-images.githubusercontent.com/17511513/55450193-e7c5cf00-5600-11e9-8ff5-ff34e441ee21.png)
多谢

**Comment by LSK1994** [comment]
_categoryView.cellWidth = screenWidth/self.titles.count;
 _categoryView.cellSpacing = 0;
