### ISSUE TITLE
您好,下方视图切换时能否抽空添加一些动画?谢谢您

### ISSUE THREAD

**Issue by mm2m123** [pujiaxin33/JXCategoryView#121]
**Feature描述**
您好,下方视图切换时能否抽空添加一些动画?谢谢您

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：学习强国

**Comment by pujiaxin33** [comment]
1.列表切换效果不是CategoryView的负责目标，所以不会花大力气支持这个；
2.我之前看过一篇文章讲解该效果，只是现在又找不到了，所以，你可以尝试去百度一下；
3.我觉得这个效果还是有点意思，但是最近比较忙，后续会考虑加入，如果你急着需要的话，可能要你自己多去尝试了；

**Comment by pujiaxin33** [comment]
还是自己实现吧- -
