### ISSUE TITLE
闪动bug

### ISSUE THREAD

**Issue by Kevin369** [pujiaxin33/JXCategoryView#122]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
点击第一个,然后点击最后一个,有连续页面闪动(直接改变偏移量应该可以吧)

**Comment by pujiaxin33** [comment]
contentScrollViewClickTransitionAnimationEnabled设置为NO即可
