### ISSUE TITLE
使用JXCategoryTitleImageView出现位置偏移

### ISSUE THREAD

**Issue by QuintGao** [pujiaxin33/JXCategoryView#123]
**bug描述**
在使用JXCategoryTitleImageView，设置底部锚点后出现位置偏移，设置titleLabelVerticalOffset无效

**版本号**
1.JXCategoryView版本号：1.3.0

**复现步骤**
将demo中的LoadDataListCollectionViewController修改如下：
![image](https://user-images.githubusercontent.com/13514024/55529169-85d59a00-56d2-11e9-9c59-82d409a56272.png)

**截图、GIF**
显示效果如下：
![image](https://user-images.githubusercontent.com/13514024/55529193-a56cc280-56d2-11e9-9183-4405db5e9723.png)

我主要想实现如喜马拉雅FM那样的效果，图文混排且底部对齐，希望作者可以看一下。

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复，1.3.1版本更新
