### ISSUE TITLE
你好，如果我顶部并不是headerView如何使用选项卡的悬浮效果?

### ISSUE THREAD

**Issue by DotaAntiMagic** [pujiaxin33/JXCategoryView#124]
**Feature描述**
请简单描述你想要的效果：？
如图:如果我的页面的顶部不是headerView该框架是否支持选项卡悬浮？
**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？网页考拉app首页
2.目标页面路径：？
3.目标效果截图：？
![image](https://user-images.githubusercontent.com/13567812/55788345-bb232300-5aea-11e9-90af-407d6993190c.png)
![image](https://user-images.githubusercontent.com/13567812/55788374-cb3b0280-5aea-11e9-91bd-20accde05bfa.png)

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
请参考这个库：https://github.com/pujiaxin33/JXPageListView
