### ISSUE TITLE
JXCategoryTitleView换行后文字上下间距如何修改

### ISSUE THREAD

**Issue by LSK1994** [pujiaxin33/JXCategoryView#125]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
暂不支持，你可以试一下，demo工程里面的JXCategoryTitleAttributeView，通过富文本来实现调整上下边距

**Comment by LSK1994** [comment]
-(NSMutableAttributedString *)addAttributeWithStr:(NSString *)str andTitleLength:(NSInteger )titleLength{
    NSMutableAttributedString * attStr = [[NSMutableAttributedString alloc]initWithString:str];
    [attStr addAttribute:NSFontAttributeName
                   value:KPingFangSCBoldFont(16)
                   range:NSMakeRange(0, str.length-titleLength)];
    [attStr addAttribute:NSFontAttributeName
                   value:KPingFangSCBoldFont(14)
                   range:NSMakeRange(str.length-titleLength, titleLength)];
    NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    [paragraphStyle setLineSpacing:7];
    paragraphStyle.alignment = NSTextAlignmentCenter;
    [attStr addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, [attStr length])];
    return attStr;
}

**Comment by LSK1994** [comment]
多谢
