### ISSUE TITLE
headerView的高度如何改变

### ISSUE THREAD

**Issue by KLOVEY** [pujiaxin33/JXCategoryView#126]
**Feature描述**
请简单描述你想要的效果：

比如进来的时候是JXTableHeaderViewHeight=100，展开某个列表后更改JXTableHeaderViewHeight=为200，JXCategoryTitleView随着往下偏移100.
JXTableHeaderViewHeight=100后，JXCategoryTitleView由之前的200往上偏移100.

**Comment by pujiaxin33** [comment]
参看[JXPagingView使用文档](https://github.com/pujiaxin33/JXPagingView)
里面有高度修改示例

**Comment by KLOVEY** [comment]
找到了swift的 ，没找到oc的，求指点

**Comment by pujiaxin33** [comment]
OC原理一样的，你看下调用了哪些api即可
