### ISSUE TITLE
你好需求是类似商城订单的界面，点击不同订单状态，加载对应状态下的VC，发现在前面的订单状态下的VC会提前创建，具体请看下下图的描述，谢谢

### ISSUE THREAD

**Issue by ClearWB** [pujiaxin33/JXCategoryView#127]
![WechatIMG329](https://user-images.githubusercontent.com/15646505/55874409-dbbfab80-5bc4-11e9-9ca8-7fddb4593bcb.jpeg)
![WechatIMG330](https://user-images.githubusercontent.com/15646505/55874414-e11cf600-5bc4-11e9-9165-9d372e9af1a6.jpeg)
![WechatIMG331](https://user-images.githubusercontent.com/15646505/55874440-f7c34d00-5bc4-11e9-809a-10f545bb53e8.jpeg)

**Comment by pujiaxin33** [comment]
请问你使用的是`JXCategoryListContainerView`类吗？
你用下面这段代码试试：
```Objective-C
 self.categoryView.defaultSelectedIndex = 2;
 self.listContainerView.defaultSelectedIndex = 2;
```

**Comment by ClearWB** [comment]
用的是JXCategoryListCollectionContainerView类， self.categoryView.contentScrollViewClickTransitionAnimationEnabled = NO;这个也设置了，ok我试一试您说的上面那个代码，我貌似下面那句没设置，谢谢回复

**Comment by pujiaxin33** [comment]
JXCategoryListCollectionContainerView新增了defaultSelectedIndex。正在更新1.3.2版本，稍后可以更新体验。
