### ISSUE TITLE
有个小疑问，如果我使用的是JXCategoryListCollectionContainerView，那么下图的方法是不是就不需要调用了？，我看到您LoadDataListCollectionViewController事例中并没有调用

### ISSUE THREAD

**Issue by ClearWB** [pujiaxin33/JXCategoryView#129]
![image](https://user-images.githubusercontent.com/15646505/56113846-b00c3f00-5f91-11e9-8418-17728d1d18da.png)

**Comment by pujiaxin33** [comment]
是的，`JXCategoryListCollectionContainerView`是后面添加了，进行了一些优化，就没有这两个方法了。

**Comment by ClearWB** [comment]
谢谢回复
