### ISSUE TITLE
求助已更新最新版本。 JXCategoryListCollectionContainerView   Crash

### ISSUE THREAD

**Issue by Y-Dragon** [pujiaxin33/JXCategoryView#130]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryListCollectionContainerView
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
![企业微信截图_69984f0c-d6bb-42e6-ab24-2fa02fbfd1c5](https://user-images.githubusercontent.com/17962542/56199862-47e05a80-6070-11e9-881a-2e5c376223fc.png)
![企业微信截图_acfd8e49-3051-497b-ba62-54052b75816a](https://user-images.githubusercontent.com/17962542/56199863-4878f100-6070-11e9-978e-ec298be21328.png)

**Comment by pujiaxin33** [comment]
请问你的手机系统是多少？

**Comment by pujiaxin33** [comment]
还就是离开页面的时候发生的crash吗？

**Comment by pujiaxin33** [comment]
我在1.3.3版本优化了通知移除，现在移除的时机调整为如下代码：
```Objective-C
- (void)willMoveToSuperview:(UIView *)newSuperview {
    if (newSuperview == nil) {
        [[NSNotificationCenter defaultCenter] removeObserver:self];
    }
}
```
这样应该能规避这个问题，你可以升级新版本尝试一下

**Comment by pujiaxin33** [comment]
我严重怀疑你把JXCategoryBaseView的contentScrollView错误置为nil了，导致了没有走kvo代码。如果你能复现你再打开此Issue吧
```
@implementation JXCategoryBaseView

- (void)dealloc
{
    if (self.contentScrollView) {
        [self.contentScrollView removeObserver:self forKeyPath:@"contentOffset"];
    }
    [self.animator stop];
}
```
