### ISSUE TITLE
TabBarController切换子VC里的JXCategoryView的子选项,第一次切换没效果

### ISSUE THREAD

**Issue by WangGuibin** [pujiaxin33/JXCategoryView#131]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。
1. 首页里有个按钮,点击切换到tabBarVC里第二个子控制器,通过通知切换categoryView的下标 
```
  [kNotificationCenter postNotificationName: kChangeToChatListSelectedIndexNotification object: nil];
   self.tabBarController.selectedIndex = 1;
```
2. 通过通知中心更新下标
```
    @weakify(self);
    [[kNotificationCenter rac_addObserverForName: kChangeToChatListSelectedIndexNotification object:nil] subscribeNext:^(NSNotification * _Nullable x) {
        @strongify(self);
        self.categoryView.defaultSelectedIndex = 2;
        self.listContainerView.defaultSelectedIndex = 2;
        [self.categoryView reloadData];
        self.listContainerView.scrollView.contentOffset = CGPointMake(2*KWIDTH, 0);
    }];

```
`看起来代码没有什么问题,可结果不如我所愿`

**版本号**
1.JXCategoryView版本号：pod 'JXCategoryView','~> 1.1.9'
2.手机系统版本号：iOS 12.1
3.手机型号：iPhone 6s

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
从上往下依次操作,出现的结果: 
![image](https://user-images.githubusercontent.com/15259130/56255595-14491300-60f8-11e9-9a41-6c5510764895.png)
![image](https://user-images.githubusercontent.com/15259130/56255608-20cd6b80-60f8-11e9-81bb-48c327ba826b.png)
![image](https://user-images.githubusercontent.com/15259130/56255627-2e82f100-60f8-11e9-9fc9-aa2751a291ff.png)
![image](https://user-images.githubusercontent.com/15259130/56255641-39d61c80-60f8-11e9-9f47-313cd0241764.png)

我有点不明白,希望大佬指点一二,第一次进入那个页面会不执行那个通知... 但是第二次以及之后进入就会有响应...

**Comment by pujiaxin33** [comment]
第一次点击，切换tab，应该是通知先没有注册上，你可以打断点确认一下。看看注册通知和点击处理的代码谁先调用。

**Comment by WangGuibin** [comment]
是的是的  感谢大佬指点, 确实如此 , 本来写在`viewDidLoad`里的 , `Debug`的时候尝试过把代码放在`viewWillAppear`和`loadView`里均不能实现效果, 最后把监听通知的代码写在`init`方法里才正常, 是VC生命周期执行顺序的基础问题...
