### ISSUE TITLE
指示器发生偏移

### ISSUE THREAD

**Issue by lifeiyang19** [pujiaxin33/JXCategoryView#132]
**bug描述**
官方demo里 （大小缩放+Cell宽度缩放 ）：添加指示器后，指示器发生偏移

**版本号**
1.JXCategoryView版本号：1.3.2
2.手机系统版本号：12.2
3.手机型号：iPhone 8plus

**复现步骤**
选中第二个cell，然后滚动到底，再选中倒数第二个cell，指示器会偏移

**截图、GIF**
![64056DE6598B96685C41F5B1D17F2ADD](https://user-images.githubusercontent.com/14243936/56481515-17764180-64f2-11e9-8485-8057d9b8206e.gif)

**Comment by pujiaxin33** [comment]
感谢反馈，你可以clone最新仓库体验一下，已经修复了。麻烦再帮忙测试一下，如果确定没有问题，我后续再发布新版本。

**Comment by lifeiyang19** [comment]
好的，多谢哈，我看了两天源码没改掉 👍👍

**Comment by lifeiyang19** [comment]
测了一遍，不偏移了，很棒 😁😁
