### ISSUE TITLE
JXCategoryListCollectionContainerView配合MJRefresh快速切换加载菊花消失

### ISSUE THREAD

**Issue by wenmobo** [pujiaxin33/JXCategoryView#133]
你好，项目中我使用JXCategoryListCollectionContainerView配合MJRefresh加载数据，快速点击选项卡，点击回到上个选项卡，加载菊花消失，可能是什么原因呀，如果还没有请求到数据，菊花应该是loading状态的。

**Comment by pujiaxin33** [comment]
因为`JXCategoryListCollectionContainerView`内部通过`UICollectionView`的cell加载列表。当切换tab的时候，之前的列表所在的cell就被回收到缓存池，就会从视图层级树里面被剔除掉，即没有显示出来且不在视图层级里面。这个时候MJRefreshHeader所持有的UIActivityIndicatorView就会被设置hidden。所以需要在列表显示的时候，且isRefreshing==YES的时候，再让UIActivityIndicatorView重新开启动画。

你clone最新的仓库，在`LoadDataListCollectionListViewController`类里面有示例代码：
```Objective-C
- (void)listDidAppear {
    if (self.tableView.mj_header.isRefreshing) {
        UIActivityIndicatorView *activity = [self.tableView.mj_header valueForKey:@"loadingView"];
        [activity startAnimating];
    }
}
```

**Comment by wenmobo** [comment]
好的，我克隆下来看看，谢谢你为我答疑

**Comment by Smiley058** [comment]
@ [ **** ](url)
