### ISSUE TITLE
什么时候支持悬浮分类横向滚动

### ISSUE THREAD

**Issue by yuanshuainiuniu** [pujiaxin33/JXCategoryView#135]
类似网易考拉,大众点评,闲鱼app的分类方式

**Comment by pujiaxin33** [comment]
有截图吗，最好用箭头标准以下具体位置

**Comment by yuanshuainiuniu** [comment]
![image](https://user-images.githubusercontent.com/9314006/56654765-73dc8b00-66c3-11e9-8260-fd339f44a551.png)

![2](https://user-images.githubusercontent.com/9314006/56654890-cae26000-66c3-11e9-93f5-9698cdef982a.gif)
像这种悬浮左右滑动

**Comment by pujiaxin33** [comment]
你看下文档的个人主页效果呢？应该和你说的是一样的

**Comment by yuanshuainiuniu** [comment]
-uiscrollview
   -uicollectionview
   -uiscrollview
      -uicollectionview

发自我的 iPhone
