### ISSUE TITLE
JXCategoryTitleView 支持自动左右滑动吗，通过代码来控制

### ISSUE THREAD

**Issue by GodzzZZZ** [pujiaxin33/JXCategoryView#140]
**Feature描述**
请简单描述你想要的效果：JXCategoryTitleView 支持自动左右滑动

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：让用户知道 title 可以滑动的一种提示

**Comment by pujiaxin33** [comment]
你可以访问到JXCategoryTitleView.collectionView来实现你的需求
