### ISSUE TITLE
我觉得你们的文档写的有点垃圾。

### ISSUE THREAD

**Issue by ZHanOBa** [pujiaxin33/JXCategoryView#142]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
不好意思脏了你的眼睛

**Comment by China-Gary** [comment]
垃圾你别看啊, 有能耐你写出一个几千个星的..
