### ISSUE TITLE
与MJRefresher冲突

### ISSUE THREAD

**Issue by liuxz656** [pujiaxin33/JXCategoryView#143]
[collectionView.mj_header endRefreshing] 居然会失效

**Comment by pujiaxin33** [comment]
`[collectionView.mj_header endRefreshing] ` 这里的`collectionView`这得是你自定义列表的`collectionView`吗？还是其他的？能再具体一点面熟问题吗？

**Comment by liuxz656** [comment]
collectionView是很普通的一个view 没做什么其他操作
collectionView放在普通的ViewController里面 [mj_header endRefreshing]是没问题的 
collectionView放在listViewController里面 用于preferredListAtIndex代理里面 就会出现手动下拉[mj_header endRefreshing]不生效的情况

**Comment by liuxz656** [comment]
我用系统的refreshControl 就不会存在这个问题 貌似是和MJrefresh冲突 但是找不到具体是哪个冲突

**Comment by pujiaxin33** [comment]
你是demo工程吗？如果是发我邮箱:317437084@qq.com

**Comment by liuxz656** [comment]
已解决 代码没变 今天居然没问题了。。。
