### ISSUE TITLE
JXCategoryDotRelativePosition 属性设置的BUG

### ISSUE THREAD

**Issue by LZS535261548** [pujiaxin33/JXCategoryView#144]
下文？？？处应该删除掉，否则设置无效了，另外红点为止能不能增加额外便宜位置  

  [super layoutSubviews];

    [CATransaction begin];
    [CATransaction setDisableActions:YES];

    JXCategoryDotCellModel *myCellModel = (JXCategoryDotCellModel *)self.cellModel;
    self.dotLayer.bounds = CGRectMake(0, 0, myCellModel.dotSize.width, myCellModel.dotSize.height);
    switch (myCellModel.relativePosition) {
        case JXCategoryDotRelativePosition_TopLeft:
        {
            self.dotLayer.position = CGPointMake(CGRectGetMinX(self.titleLabel.frame), CGRectGetMinY(self.titleLabel.frame));
        }
            break;
        case JXCategoryDotRelativePosition_TopRight:
        {
            self.dotLayer.position = CGPointMake(CGRectGetMaxX(self.titleLabel.frame), CGRectGetMinY(self.titleLabel.frame));
        }
            break;
        case JXCategoryDotRelativePosition_BottomLeft:
        {
            self.dotLayer.position = CGPointMake(CGRectGetMinX(self.titleLabel.frame), CGRectGetMaxY(self.titleLabel.frame));
        }
            break;
        case JXCategoryDotRelativePosition_BottomRight:
        {
            self.dotLayer.position = CGPointMake(CGRectGetMaxX(self.titleLabel.frame), CGRectGetMaxY(self.titleLabel.frame));
        }
            break;

        default:
            break;
    }
？？？？？
    self.dotLayer.position = CGPointMake(CGRectGetMaxX(self.titleLabel.frame), CGRectGetMinY(self.titleLabel.frame));

    [CATransaction commit];

**Comment by LZS535261548** [comment]
增加一个红点配置属性关于  横向偏移值   纵向偏移值

**Comment by pujiaxin33** [comment]
1.3.5版本已经修复，并添加了dotOffset字段
