### ISSUE TITLE
难道只有我会出现，tab下的VC viewWillApear等函数根本不执行？取不到导航栏

### ISSUE THREAD

**Issue by mrxiruo** [pujiaxin33/JXCategoryView#145]
tab下的VC viewWillApear等函数根本不执行；而且tab里的vc也取不到导航栏，push比较不方便 这个问题有人遇到过吗？

**Comment by mrxiruo** [comment]
主要就是在tab切换的时候，viewWillApear不执行，这个有什么方法解决呢？

**Comment by mrxiruo** [comment]
我先通过listDidAppear解决业务问题吧

**Comment by pujiaxin33** [comment]
> tab下的VC viewWillApear等函数根本不执行；而且tab里的vc也取不到导航栏，push比较不方便 这个问题有人遇到过吗？

VC的viewWillAppear不会触发，用`listDidAppear`方法代替
@protocol JXCategoryListContentViewDelegate <NSObject>
/**
 可选实现，列表显示的时候调用
 */
- (void)listDidAppear;

**Comment by pujiaxin33** [comment]
取不导航栏参考：
> Demo的使用方法是给列表新增一个属性：@property (nonatomic, strong) UINavigationController *naviController，然后将父VC的navigationController赋值给它。这样列表的cell点击就可以通过自定义的naviController属性进行跳转了。详情参考源码LoadDataListBaseViewController

**Comment by mrxiruo** [comment]
@pujiaxin33，好的这条我刚也看到了，谢谢
