### ISSUE TITLE
JXCategoryBaseView.m 有循环引用

### ISSUE THREAD

**Issue by D-meng** [pujiaxin33/JXCategoryView#146]
**bug描述**
JXCategoryBaseView.m 有循环引用

JXCategoryBaseView.m 534 和536行 使用了self，没有使用 weakSelf。
![屏幕快照 2019-05-20 下午8 06 39](https://user-images.githubusercontent.com/26738512/58020641-4e646500-7b3b-11e9-9b84-e2d36fe00c93.png)

**Comment by mrxiruo** [comment]
😆 这都被你发现了

**Comment by pujiaxin33** [comment]
感谢反馈，已修复
