### ISSUE TITLE
IndicatorLineView 偏移

### ISSUE THREAD

**Issue by DogTwoChen** [pujiaxin33/JXCategoryView#147]
**bug描述**
刚开始进去页面的时候IndicatorLineView没有发生偏移,点击之后位置偏移

**版本号**
1.JXCategoryView版本号：1.3.6
2.手机系统版本号：iOS12.1
3.手机型号：iPhone X

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryTitleVerticalZoomView JXCategoryIndicatorLineView
2.具体的操作步骤是：刚开始进去页面的时候IndicatorLineView没有发生偏移,点击之后位置偏移

**截图、GIF**

![e1v9w-km5ic](https://user-images.githubusercontent.com/18676761/58079738-457b9e00-7be4-11e9-9caf-0cbdf9a16c0c.gif)

**Comment by pujiaxin33** [comment]
确实是跟JXCategoryTitleVerticalZoomView搭配使用时的bug，需要花点时间找下问题

**Comment by DogTwoChen** [comment]
请问有查到是什么原因吗

**Comment by pujiaxin33** [comment]
sorry，忙忘了，这两天抽空看一下哈

**Comment by DogTwoChen** [comment]
好的谢谢

**Comment by pujiaxin33** [comment]
@DogTwoChen 你下载最新的示例项目，我更新了代码，自测没有问题了。但是麻烦你帮忙多测试一下边界情况。没有问题了，你给我说下，我就打个新包。

**Comment by DogTwoChen** [comment]
@pujiaxin33 测过没问题了,感谢

**Comment by DogTwoChen** [comment]
@pujiaxin33 发现使用  selectItemAtIndex 设置小标的时候依然有存在便宜的情况

**Comment by pujiaxin33** [comment]
谢谢补充，已修复，正准备发布1.3.11，请静候
