### ISSUE TITLE
仓库里的代码和pod里面的代码不一致？

### ISSUE THREAD

**Issue by peterios2016** [pujiaxin33/JXCategoryView#148]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
pod里面的JXCategoryIndicatorBackgroundView类好像是旧版的，使用了会报错
![image](https://user-images.githubusercontent.com/38389546/58141120-c2eeef00-7c74-11e9-863a-f9bc2f87706b.png)

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
你现在是什么版本？

**Comment by peterios2016** [comment]
> 你现在是什么版本？

pod1.3.7

**Comment by pujiaxin33** [comment]
建议你clean下xcode，你可以自己看下pod库源码，是没有问题的
