### ISSUE TITLE
9.3系统界面卡死，内存飙升是什么问题，怎么解决

### ISSUE THREAD

**Issue by 287291867** [pujiaxin33/JXCategoryView#149]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
请通过Xcode的相关测试工具，确定导致界面异常的问题点，确认是你的业务代码还是JXCategoryView代码问题。

**Comment by pujiaxin33** [comment]
你可以通过xcode的debug memory graph 工具看下究竟是些类的内存在飙升，如果是JXCategoryView，请截图一下，然后你再打开此issue，我先关闭了。

**Comment by bigNiuSanMao** [comment]
作者 我也遇到了 同样的 问题，版本是iOS 9.3

**Comment by pujiaxin33** [comment]
请使用最新1.5.1版本，因为9.3有循环调用。请查看1.5.0版本迁移指南哟。
