### ISSUE TITLE
特殊效果中对全面屏底部没有安全区域的问题。

### ISSUE THREAD

**Issue by AnnyName** [pujiaxin33/JXCategoryView#151]
在collectionView样式中。如果设置 self.categoryView.defaultSelectedIndex = 1;self.listContainerView.defaultSelectedIndex = 1; 会看到没有安全区域的效果。 需要滑到.defaultSelectedIndex = 0的时候才能看到

**Comment by pujiaxin33** [comment]
我用iOS12.1的iPhoneX模拟器，并未出现你说的问题。请问你的测试情况呢？
