### ISSUE TITLE
你好  我滑动切换的时候  界面会有点抖动  是什么原因呢

### ISSUE THREAD

**Issue by xuhuaping** [pujiaxin33/JXCategoryView#153]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
有GIF吗？

**Comment by xuhuaping** [comment]
> 有GIF吗？

没有 和今日头条那样的新闻列表

**Comment by pujiaxin33** [comment]
可以提供一个可以复现问题的demo吗？不然我怎么知道什么问题呢？

**Comment by zysmmy** [comment]
大概是这里的问题：

`-(BOOL)mainTableViewGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer{
    
    if (otherGestureRecognizer.view == 你的横向滑动的ScrollView) {
        return 0;
    }
    
    return [gestureRecognizer isKindOfClass:UIPanGestureRecognizer.class] && [otherGestureRecognizer isKindOfClass:UIPanGestureRecognizer.class];
    
}`

你加上这些就ok了。

**Comment by xuhuaping** [comment]
> 大概是这里的问题：
> 
> ` - （BOOL）mainTableViewGestureRecognizer：（UIGestureRecognizer *）gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer：（UIGestureRecognizer *）otherGestureRecognizer {
> 
> ```
> if (otherGestureRecognizer.view == 你的横向滑动的ScrollView) {
>     return 0;
> }
> 
> return [gestureRecognizer isKindOfClass:UIPanGestureRecognizer.class] && [otherGestureRecognizer isKindOfClass:UIPanGestureRecognizer.class];
> ```
> 
> }`
> 
> 你加上这些就OK了。
好的  谢谢  我用JXCategoryListCollectionContainerView这个也不会
