### ISSUE TITLE
实现了JXCategoryListCollectionContentViewDelegate的控制器内部无法获取其self.navigationController

### ISSUE THREAD

**Issue by JianRuHong** [pujiaxin33/JXCategoryView#155]
如题，当控制器的view当做JXCategoryView的展示内容时，控制器内部无法获知导航控制器。
```
- (UIView *)listView {
    return self.view;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.navigationController == nil;//true
}
```

**Comment by JianRuHong** [comment]
因为获取不到，所以现在就能相当两种解决办法：
1. 获取当前屏幕正在展示的导航控制器；
2. 把跳转事件传出去。

但是，我觉得这两种方式都不符合设计规范，最好是能**在JXCategoryListCollectionContentViewDelegate里添加属性指向当前的导航控制器**。

**Comment by pujiaxin33** [comment]
下面的文档有说明
[常见问题和答案](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/%E4%BD%BF%E7%94%A8%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.md)
