### ISSUE TITLE
大佬，已经加载过的VC在不重置的情况下 ， 如何改变VC的顺序， 和今日头条的排序那样

### ISSUE THREAD

**Issue by xuhuaping** [pujiaxin33/JXCategoryView#157]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
目前还不支持，确实是一个值得支持的特性，需要花点时间实现

**Comment by xuhuaping** [comment]
> 目前还不支持，确实是一个值得支持的特性，需要花点时间实现

好的  期待

**Comment by pujiaxin33** [comment]
可以留一个qq吗，我先实现之后让你测试之后再发布新包，免得自测不充分，遗留问题

**Comment by pujiaxin33** [comment]
你下载最新的示例工程，特殊效果-》重新排序 示例，你可以看看是否满足需求

**Comment by xuhuaping** [comment]
> 可以留一个QQ吗，我先实现之后让你测试之后再发布新包，免得自测不充分，遗留问题

869735652 新增和删除也可以增加下

**Comment by pujiaxin33** [comment]
之前思路搞复杂了，你下载最新工程看下《删除、增加、重新排序不重复创建列表》示例
清爽了许多，并且没有新增api，你试一下，有没有问题都反馈一下哈
