### ISSUE TITLE
UICollectionViewCell frame与JXCategoryListCollectionContainerView frame不一致

### ISSUE THREAD

**Issue by GodWolf** [pujiaxin33/JXCategoryView#159]
**bug描述**
使用 Masonry 进行自动布局，当 JXCategoryListCollectionContainerView 的 frame 发生变化的时候，调用 layoutSubviews: 方法，layoutSubviews: 内只修改了 self.collectionView 的 frame，没有修改 cell 的 size ,造成显示错误

**版本号**
1.JXCategoryView版本号：1.3.5
2.手机系统版本号：12.3.1
3.手机型号：iPhone X

![IMG_0003](https://user-images.githubusercontent.com/9720928/59734003-5faba900-9282-11e9-8d46-9096177bc7fb.jpg)

**Comment by pujiaxin33** [comment]
你先自己在父视图layoutSubviews方法里，在修改listContainerView frame之后调用`[self.listContainerView.collectionView.collectionViewLayout invalidateLayout];`方法
应该能临时解决问题

**Comment by GodWolf** [comment]
已经临时解决了，感谢

**Comment by pujiaxin33** [comment]
1.3.12修复
