### ISSUE TITLE
collectionViewClassInListContainerView调用存在问题

### ISSUE THREAD

**Issue by donggelaile** [pujiaxin33/JXCategoryView#160]
1、对于JXCategoryListCollectionContainerView，自定义UICollectionView目前给出的方案是实现- (Class)collectionViewClassInListContainerView:(JXCategoryListCollectionContainerView *)listContainerView方法。
2、实际使用中发现dataSource实现了该方法确不会被调用。看源码后发现该方法调用在initializeViews中，此时正在初始化当前类，dataSource尚未赋值，导致调用失败。
3、因此，可能需要更改该方法的调用时机或者初始化时增加dataSource参数。

**Comment by pujiaxin33** [comment]
感谢反馈，当时写的急了，没有认真review。为了兼容老版本，只能先新增一个`- (instancetype)initWithDataSource:(id<JXCategoryListCollectionContainerViewDataSource>)dataSource NS_DESIGNATED_INITIALIZER;`方法了。

**Comment by pujiaxin33** [comment]
算了，不兼容老版本了，直接只有这一个初始化方法`- (instancetype)initWithDataSource:(id<JXCategoryListCollectionContainerViewDataSource>)dataSource NS_DESIGNATED_INITIALIZER;`

**Comment by donggelaile** [comment]
👌好的

**Comment by pujiaxin33** [comment]
今天晚些时候会更新包哈，你明天再更新一下

**Comment by donggelaile** [comment]
ok

**Comment by pujiaxin33** [comment]
再晚一天，有一个新bug，想跟着一起打包

**Comment by donggelaile** [comment]
🆗不急 😄

**Comment by donggelaile** [comment]
这个。。。 我又回来了。今天更新了1.3.14版本，还是有点问题哈。大概是JXCategoryListCollectionContainerView文件中的68行需要改成
if (self.dataSource &&
        [self.dataSource respondsToSelector:@selector(collectionViewClassInListContainerView:)] &&
        [[self.dataSource collectionViewClassInListContainerView:self] isKindOfClass:object_getClass([UICollectionView class])])
第三个类型判断条件，判断一个类对象是哪种类型，isKindOfClass后面放的是元类对象，需要#import <objc/runtime.h>头文件

**Comment by pujiaxin33** [comment]
确实有问题，已采用你的方案修复了。明天再发布新版本哈
