### ISSUE TITLE
请问可以为 listContent 和 JXCategoryBaseView添加一个是否允许 select(scroll)的代理吗

### ISSUE THREAD

**Issue by kchtin** [pujiaxin33/JXCategoryView#161]
**Feature描述**
例如说,我有一个页面,有 5 个子模块,顶栏是ABCDE item,
对应 view 为 a,b,c,d,e view.
其中,cView和 dView 需要根据是否登录来显示.
如果从 bView 滑动到 cView,如果未登录或者登录失效,就需要拦截滚动,在加载 cView 之前中断它.
点击 C item 也一样.

目前如果使用JXCategoryListCollectionContainerView, 除了在生成 view 的代理方法中可以拦截一次之外,其他地方没办法拦截了.

**Comment by pujiaxin33** [comment]
categoryView已经有这个代理了

```
/**
 控制能否点击Item

 @param categoryView categoryView对象
 @param index 准备点击的index
 @return 能否点击
 */
- (BOOL)categoryView:(JXCategoryBaseView *)categoryView canClickItemAtIndex:(NSInteger)index;
```

**Comment by pujiaxin33** [comment]
然后关于`JXCategoryListCollectionContainerView`的话，我准备加一个代理方法：
```
/**
 控制能否初始化对应index的列表。有些业务需求，需要在某些情况才允许初始化某些列表，通过通过该代理实现控制。
 */
- (BOOL)listContainerView:(JXCategoryListCollectionContainerView *)listContainerView canInitListAtIndex:(NSInteger)index;
```
这样子应该能解决问题吧

**Comment by kchtin** [comment]
好的,谢谢.
如果方便的话,JXCategoryListContainerViewDelegate也一起加个哦

**Comment by pujiaxin33** [comment]
1.3.14版本添加
