### ISSUE TITLE
嵌套JXPagerView 使用

### ISSUE THREAD

**Issue by Jokemac** [pujiaxin33/JXCategoryView#162]
使用特殊情况的嵌套模式 并且嵌套了 JXPagerView 无法滑动切换到下个顶层控制器
比如顶层有 A, B 控制器, A 使用了 JXPagerView
A 有 1, 2, 3 VC
B 有 1 个 VC
A 滑到 3 的时候无法通过滑动切换到 B控制器

**Comment by pujiaxin33** [comment]
建议你参考下这个库 https://github.com/pujiaxin33/JXPagingView
的这个示例【CategoryView嵌套PagingView 】
