### ISSUE TITLE
点击 Titles 切换时 IndicatorLine 发生偏移

### ISSUE THREAD

**Issue by chen570075003** [pujiaxin33/JXCategoryView#165]
**bug描述**
不同长度的 Title 滚动过程 IndicatorLine 正常，点击时发生偏移

**版本号**
1.JXCategoryView版本号：1.3.14
2.手机系统版本号：iOS 12.2
3.手机型号：iPhone XS Max Simulator

**复现步骤**

1. 遇到问题的相关效果、类是：JXCategoryTitleVerticalZoomView

2.具体的操作步骤是：点击较短 Title

**截图、GIF**
![offset](https://user-images.githubusercontent.com/8541399/60777771-ad6f4f00-a166-11e9-9106-e096acafc291.gif)

**Comment by pujiaxin33** [comment]
感谢反馈，是个bug，晚些时间修复，请静候

**Comment by pujiaxin33** [comment]
1.3.16版本修复
