### ISSUE TITLE
pod install 一直安装不成功

### ISSUE THREAD

**Issue by zdmjerry** [pujiaxin33/JXCategoryView#166]
BUG：
通过pod安装，pod install 一直安装不成功
JXCategoryView(1.3.0)

错误如下：
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by ZYHB** [comment]
BUG：
通过pod安装，pod install 一直安装不成功
pod 'JXCategoryView', '~> 1.3.7'

错误如下：
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by pujiaxin33** [comment]
网络问题，隔一段时间，多试试就行。我之前也遇到过

**Comment by pujiaxin33** [comment]
尽量选择最新版本，因为某个版本（记不清了），我把库里面的示例gif全部移除了，这样子`pod install`的时候clone更快。

**Comment by KaiserJoe** [comment]
最近 pod search  最新 1.1.0 ，之前还是能pod 出 1.3.3的。是不是作者版本手误出错了 ？ @pujiaxin33
