### ISSUE TITLE
请问能让下划线和文本左对齐吗?

### ISSUE THREAD

**Issue by honkerSK** [pujiaxin33/JXCategoryView#167]
**Feature描述**
请简单描述你想要的效果：？
能让下划线和文本左对齐吗?
componentPosition属性, 只能设置下划线顶部居中对齐和底部居中对齐

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？
![Snip20190711_1](https://user-images.githubusercontent.com/9138683/61025049-ff6fd900-a3e1-11e9-9f5b-6abd3ea2d5de.png)

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
能给个UI截图吗？很好奇最终的显示效果

**Comment by honkerSK** [comment]
> 能给个UI截图吗？很好奇最终的显示效果

你好,已添加效果截图

**Comment by pujiaxin33** [comment]
你这不是已经实现了？我是好奇为什么有这样的设计，看起来不是很难受吗？（个人意见）。

**Comment by pujiaxin33** [comment]
建议你自定义indicatorLineView

**Comment by honkerSK** [comment]
好的. 这样设计是因为项目中文字都是英文,每个分类项会很长, 下划线和文字等长或者固定长度居中都不合适,所以设计成这样了

**Comment by pujiaxin33** [comment]
你clone最新仓库，新增了`JXCategoryIndicatorAlignmentLineView`类实现了该效果，你自己运行demo体验一下。
