### ISSUE TITLE
怎样实现在点击标题和滚动视图的情况下使指示器的的移动效果是一致的

### ISSUE THREAD

**Issue by ismilesky** [pujiaxin33/JXCategoryView#170]
**Feature描述**
请简单描述你想要的效果：？

怎样实现在点击标题和滚动视图的情况下使指示器的的移动效果是一致的， 无论是点击标题还是滚动下方视图都是第一种的那种效果。

![guide_1](https://user-images.githubusercontent.com/12742733/61425539-d7d0c180-a949-11e9-8dac-91e373f3dae3.gif)
![guide_2](https://user-images.githubusercontent.com/12742733/61425549-def7cf80-a949-11e9-9009-9d5ee80b2e6d.gif)

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by ismilesky** [comment]
已解决，contentScrollView做了用户滚动的判断

**Comment by ismilesky** [comment]
如果去掉用户滚动的判断，点击标题时会出现指示器错位的问题。 是不是我采取的方式不对呢，该怎么实现这种效果呢
![QQ20190718-144255](https://user-images.githubusercontent.com/12742733/61435326-c946d200-a96a-11e9-9604-4d2357234146.png)
![guide_1](https://user-images.githubusercontent.com/12742733/61435332-cc41c280-a96a-11e9-9fec-8acc9be2b250.gif)

**Comment by pujiaxin33** [comment]
指示器的滚动必须要把【点击切换】和【滚动切换】事件分开，如果只依赖滚动驱动指示器的话，比如跨多个item点击（比如有a、b、c三个，当前在a，直接点击c），那么指示器就会工作异常。
基于现在的情况，只有点击的时候，自定义指示器的动画来模拟实现滚动时的效果。

**Comment by ismilesky** [comment]
那您那边有时间加上这种功能吗？

**Comment by pujiaxin33** [comment]
你clone最新的仓库，新加了一个类型`JXCategoryIndicatorScrollStyle`。你把`JXCategoryIndicatorLineView.scrollStyle`设置为`JXCategoryIndicatorScrollStyleSameAsUserScroll`即可。你体验一下，顺便测试一下有没有问题。

**Comment by ismilesky** [comment]
好的，效率真快。我试了一下，没有问题，谢谢作者大大。 我是看到了芒果tv类似的功能才给你提了个需求，哈哈，勿怪。

**Comment by pujiaxin33** [comment]
我以为你急着用啊

**Comment by Abnerzj** [comment]
当设置指示器`lineView.scrollStyle = JXCategoryIndicatorScrollStyleSameAsUserScroll`时，如果指示器的样式是`lineView.lineStyle = JXCategoryIndicatorLineStyle_LengthenOffset; `，点击标题是正常的，但是滚动视图到下一个时，会由小到大缩放一下。
` // 指示器
    JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
    lineView.indicatorWidth = 20; // 固定线宽
    lineView.indicatorHeight = 4.6; // 固定线高
    lineView.indicatorColor = customPinkColor; // 颜色
    lineView.lineStyle = JXCategoryIndicatorLineStyle_Lengthen; // 线条延长style+偏移
    lineView.scrollStyle = JXCategoryIndicatorScrollStyleSameAsUserScroll; // 点击item时指示器和列表滚动时效果一致`

**Comment by pujiaxin33** [comment]
@Abnerzj 朋友，你能将你的问题单独提一个ISSUE吗？这个ISSUE已经被关闭了。
