### ISSUE TITLE
子控制器为同一个控制器，页面布局出现底部安全距离错误

### ISSUE THREAD

**Issue by ECUnion-HD** [pujiaxin33/JXCategoryView#171]
**bug描述**
子控制器为同一个控制器，页面布局出现底部安全距离错误,按照图中解决方案没有解决问题

1.JXCategoryView版本号：1.3.13
2.手机系统版本号：iphoneX 11.3
3.手机型号：iphoneX

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：点击切换视图

**截图、GIF**
![B5E01A07-99A6-4451-9DF2-8F40CF9E4EF7](https://user-images.githubusercontent.com/14834283/61443440-18493300-a97c-11e9-8100-964c9e74845c.png)
![8822D548-EC91-41AB-902D-62EFCBB460D4](https://user-images.githubusercontent.com/14834283/61443453-1f704100-a97c-11e9-983e-95c18ddf42b7.png)
![A4E119EA-752B-4371-AB22-0876FA2B1409](https://user-images.githubusercontent.com/14834283/61444591-40d22c80-a97e-11e9-96dd-b1f2fc7f5d7c.png)

**Comment by pujiaxin33** [comment]
为了排除你项目里面其他代码配置的问题，所以，你能通过demo复现这个问题吗？

**Comment by ECUnion-HD** [comment]
> 为了排除你项目里面其他代码配置的问题，所以，你能通过demo复现这个问题吗？

已解决，谢了
