### ISSUE TITLE
使用titleLabelZoomScale，长文字选中时左右间距出现问题

### ISSUE THREAD

**Issue by Z-Victory** [pujiaxin33/JXCategoryView#172]
左右间距受到titleLabelZoomScale的放大效果影响
![IMG_0847](https://user-images.githubusercontent.com/15643266/61604117-cbfb3d00-ac72-11e9-8433-2ce7d4735eb9.PNG)

**Comment by pujiaxin33** [comment]
字体缩放的原理就是设置transform，可参考`JXCategoryTitleCell`源码。目的就是让左右的title不受缩放影响而调整位置。
给你的建议：
- 把`cellSpacing`调整大一点；
- 把`cellWidthZoomEnabled`设置为YES，这样就可以动态更新cell宽度，不会有重叠问题

**Comment by Z-Victory** [comment]
OK，谢谢

**Comment by Z-Victory** [comment]
试了你的方法，发现titleLabelZoomScale的比例设为1.85时仍然会出现重叠的问题
![1563938443620](https://user-images.githubusercontent.com/15643266/61762770-9d619b80-ae05-11e9-913c-c2211bbd7acd.jpg)
<img width="1004" alt="WechatIMG159" src="https://user-images.githubusercontent.com/15643266/61762776-a3577c80-ae05-11e9-9da0-86cc55d7be9a.png">

**Comment by pujiaxin33** [comment]
你把`cellWidthZoomScale`也设置为1.85呢

**Comment by Z-Victory** [comment]
这下是可以了，但对应的，第一个tab的左间距相应增大，如何调这个距离，另外设置底部对齐，但实际效果差一点点
![IMG_A02E8D56BE62-1](https://user-images.githubusercontent.com/15643266/61763235-3cd35e00-ae07-11e9-9807-4c88d16eb49c.jpeg)
![IMG_0859](https://user-images.githubusercontent.com/15643266/61763312-8f147f00-ae07-11e9-87f3-023dca68b930.jpg)

**Comment by pujiaxin33** [comment]
左边距可以将contentEdgeLeft设置小一点
底部边距你可以参考这个示例
![image](https://user-images.githubusercontent.com/12654640/61763777-2f1ed800-ae09-11e9-8595-3c66d0d993cb.png)

**Comment by Z-Victory** [comment]
我指的是选中的与未选中的他们底部并没有对齐
希望你不要嫌我麻烦。。。^_^

**Comment by pujiaxin33** [comment]
我知道你的意思，我给你的截图，大小缩放+底部锚点，选择和未选中底部都是对齐的，你参考一下使用代码呢？这样可以进一步排查你代码的问题

**Comment by Z-Victory** [comment]
demo中把比例设为1.85后也有这个问题，截图如下
![1563952444425](https://user-images.githubusercontent.com/15643266/61772817-c6922400-ae25-11e9-955d-437a0c2bb511.jpg)
![1563952396139](https://user-images.githubusercontent.com/15643266/61772823-c7c35100-ae25-11e9-9797-26692bb4a280.jpg)

**Comment by pujiaxin33** [comment]
你看下视图层级呢？多半是因为放太大了底部自然显得空白了，但是实际是底部对齐的

**Comment by Z-Victory** [comment]
对，是齐的，label有顶部和底部的空白导致，那能不能缩小一下label的高度，也许就能完全对齐了
![1563957998087](https://user-images.githubusercontent.com/15643266/61779294-027fb600-ae33-11e9-9a04-8be6d96716ae.jpg)

**Comment by pujiaxin33** [comment]
这个方案是行不通的哈，你这一改，其他效果就乱套了。你可以试一下英文，貌似英文的下面没有这么多的空白。

**Comment by pujiaxin33** [comment]
你非要解决的话，目前只有你自己修改源码，把选中的人为下移一点点。

**Comment by Z-Victory** [comment]
英文的一样。。。那我手动改吧
![IMG_5DE323EAEAFE-1](https://user-images.githubusercontent.com/15643266/61780149-92722f80-ae34-11e9-95ef-b00c12353ab3.jpeg)

**Comment by Z-Victory** [comment]
都应该在哪几个方法中修改？

**Comment by pujiaxin33** [comment]
我试了一下，没有写出来，暂时帮不了你了

**Comment by Z-Victory** [comment]
头疼了，要求我改掉。。。。我看看怎么改吧

**Comment by pujiaxin33** [comment]
我明天再试试吧

**Comment by pujiaxin33** [comment]
果然有些问题，得放松一下脑壳，才找得到问题所在。
我添加了一个【大小缩放+底部锚点+视觉对齐】示例，添加了一个`titleLabelZoomSelectedVerticalOffset`属性，细节就查看源码哈。
目前没有更新pods版本，还需要再观察一下改动点是否对其他效果有影响。
建议你先通过拖入文件的方式引入，把当前需求解决再说。
