### ISSUE TITLE
能指定第一次打开显示第几个index吗

### ISSUE THREAD

**Issue by xiaoio4** [pujiaxin33/JXCategoryView#173]

**Comment by zhpengkun** [comment]
https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/%E4%BD%BF%E7%94%A8%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.md#defaultselectedindex%E4%BD%BF%E7%94%A8

文档里不就有么

**Comment by pujiaxin33** [comment]
@zhpengkun 谢谢你，一拳超人。 @xiaoio4 就是一拳超人发的文档里面有答案哈
