### ISSUE TITLE
现在改成了懒加载，如何设置成一次性全部加载？

### ISSUE THREAD

**Issue by aa335418265** [pujiaxin33/JXCategoryView#174]
JXCategoryListContainerView 下的控制器如何全部都先加载了，而不是懒加载

**Comment by pujiaxin33** [comment]
你在JXCategoryView初始化的时候，可以一起初始化你所有的列表，然后记录到listArray数组里面。

然后在代理方法`- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index;`里面，根据index返回listArray里面的列表。

**Comment by aa335418265** [comment]
但是， 这个方法我测试了，只调用一次，当切换到第二个控制器的时候才会接着调用

**Comment by pujiaxin33** [comment]
不是在这里初始化，比如在你vc的viewDidLoad里面初始化所有的列表，然后`initListForIndex`代理方法直接返回你缓存的列表。

**Comment by aa335418265** [comment]
明白！谢谢大神，如此迅速的回复！

**Comment by XiaBaKe** [comment]
为什么我的预加载没有效果，我哪里操作问题吗？TemplateForUViewController *list0 = [[TemplateForUViewController alloc] init];
    ViewController *list1 = [[ViewController alloc] init];
    list1.type = 0;
    ViewController *list2 = [[ViewController alloc] init];
    list2.type = 1;
    self.vc_initArr = @[list0,list1,list2];

- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index {
 
    return self.vc_initArr[index];
}

**Comment by XiaBaKe** [comment]
loadViewIfNeeded
