### ISSUE TITLE
titleSelectedFont=bold 32和titleFont=28,切换titlelabel会有缩放展开，效果能优化吗

### ISSUE THREAD

**Issue by vzhang** [pujiaxin33/JXCategoryView#175]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
> 切换titlelabel会有缩放展开

你能描述清楚一点吗？能有个截图或者GIF说明就更好了。

**Comment by vzhang** [comment]
大小缩放+字体粗细
你的这个案例，现在实现起来，你的label宽度是按照titleFont去计算的，这样在切换到titleSelectedFont的时候宽度会增加，而这个时候label的动画，就是两边在变长，效果就是相当于在左右拉伸到titleSelectedFont长度。和你gif中的例子已经不一样了


`- (JXCategoryTitleView *)categoryTitleView
{
    if (!_categoryTitleView) {
        _categoryTitleView = [[JXCategoryTitleView alloc] init];
        _categoryTitleView.delegate = self;
        _categoryTitleView.titleFont = [UIFont systemFontOfSize:14.0];
        _categoryTitleView.titleSelectedFont =  [UIFont boldSystemFontOfSize:16.0];
        _categoryTitleView.titleColor = [UIColor blackColor];
        _categoryTitleView.titleSelectedColor = [UIColor redColor]; 
        _categoryTitleView.titleDataSource = self;
    
        _categoryTitleView.titleLabelAnchorPointStyle =  JXCategoryTitleLabelAnchorPointStyleBottom;
        
        JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
        _categoryTitleView.indicators = @[lineView];
        lineView.indicatorWidth = 14.0;
        lineView.indicatorHeight = 4.0;
        lineView.indicatorCornerRadius = 2.0;
        
        lineView.indicatorLineViewColor = [UIColor redColor];
    }
    
    return _categoryTitleView;
}`

这个代码就能看出来效果了。

**Comment by pujiaxin33** [comment]
朋友，我按照你的代码运行没有问题吗，你能截图画箭头说明一下问题点吗？

**Comment by chen570075003** [comment]
![scroll](https://user-images.githubusercontent.com/8541399/63581515-cc685a00-c5c9-11e9-8bc7-af24c9928a46.gif)
可能是我最近遇到的一个相同的问题，初始化后字体显示异常，滚动后才会正常

**Comment by pujiaxin33** [comment]
@chen570075003 他跟你用的都不是同一个类。把你的配置代码贴出来呢

**Comment by chen570075003** [comment]
@pujiaxin33 
``` java
    //在原有的配置代码修改并添加后两行字体配置
    self.categoryView.maxVerticalFontScale = 1.5;
    self.categoryView.titleFont = [UIFont boldSystemFontOfSize:22];
    self.categoryView.titleSelectedFont = [UIFont boldSystemFontOfSize:26];
```

**Comment by pujiaxin33** [comment]
@chen570075003 

1. 当使用titleLabelZoomScale时，titleSelectedFont会失效：
> @property (nonatomic, assign, getter=isTitleLabelZoomEnabled) BOOL titleLabelZoomEnabled;     //默认为NO。为YES时titleSelectedFont失效，以titleFont为准。

2.垂直滚动这个bug已经修复，预计1.3.18版本修复
