### ISSUE TITLE
能否调整title 的位置和title 的点击范围（宽度）

### ISSUE THREAD

**Issue by aa335418265** [pujiaxin33/JXCategoryView#176]
**Feature描述**
如题：能否调整title 的位置和title 的点击范围（宽度）
1. 目前是title 的位置能否可以自行调整
2. 当标题只有2个字的时候，点击范围只有文字显示的区域，太小了。能否变大。

**Comment by pujiaxin33** [comment]
你可以设置cellWidth

**Comment by aa335418265** [comment]
> 你可以设置cellWidth

那title的位置呢，可以调整吗

**Comment by pujiaxin33** [comment]
你要怎么调整？
