### ISSUE TITLE
demo太乱。虽然注释清楚，但是用起来花费的时间太长了，demo封来封去的干嘛，要巴拉好久。

### ISSUE THREAD

**Issue by NinJaSir** [pujiaxin33/JXCategoryView#177]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
好建议，我也思考过这方面的事情，但是需要支持的示例实在太多了，不写点父类，就会有许多重复代码。其实对于核心的使用，很简单就是一些属性的配置。对于复杂的示例，可能需要自己多花点时间看了。

**Comment by lechie** [comment]
感谢作者产品，但是demo对于我们这种新手来说，确实封装的太过于抽象了，自己水平欠佳，看个示例要层层抽离分析好久。

**Comment by pujiaxin33** [comment]
第一：核心的使用示例应该是比较简洁明了；
第二：复杂的示例（比如嵌套、垂直滚动缩放、数据加载等）确实代码量要多一些，要花些时间看；
第三：你们可以针对具体的哪些点提出一些建议，比如哪些地方的示例代码过于冗余、有歧义等，我会针对性修改。
