### ISSUE TITLE
侧滑手势的问题

### ISSUE THREAD

**Issue by peterios2016** [pujiaxin33/JXCategoryView#178]
**Feature描述**
查看了你的侧滑手势处理文档，里面有一句“如果产品经理不需要这样的特性，希望侧滑手势任何情况都能响应，就不需要参看此教程，不做任何处理即可。”
但实际上只要JXCategoryListContainerView的宽度是全屏的，手指就必须放到JXCategoryListContainerView的响应范围之外，这点能否做一下兼容

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你可以尝试在`ContentBaseViewController`注释如下两行代码，即不控制侧滑手势，这样子就可以在任何情况下都可以侧滑返回上一个页面，而不是只有在第一个列表时才行。建议你检查一下你项目里面其他地方关于侧滑手势处理，有可能是其他业务逻辑影响到了。

![image](https://user-images.githubusercontent.com/12654640/62412777-81e26600-b639-11e9-9991-f9975247999e.png)
![image](https://user-images.githubusercontent.com/12654640/62412779-8c9cfb00-b639-11e9-945e-fb682b724534.png)

**Comment by peterios2016** [comment]
因为业务有自定义导航栏的需求，所以我在自己的BaseVC是重写了手势的判断，并把系统的侧滑代理设置为自己的BaseVC，不知道是不是这个原因
`
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    self.navigationController.interactivePopGestureRecognizer.delegate = self;
}

//这个方法是在手势将要激活前调用：返回YES允许右滑手势的激活，返回NO不允许右滑手势的激活
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer {
    if (gestureRecognizer == self.navigationController.interactivePopGestureRecognizer) {
        //屏蔽调用rootViewController的滑动返回手势，避免右滑返回手势引起死机问题
        if (self.navigationController.viewControllers.count < 2 ||
            self.navigationController.visibleViewController == [self.navigationController.viewControllers objectAtIndex:0]) {
            return NO;
        }
    }
    //这里就是非右滑手势调用的方法啦，统一允许激活
    return YES;
}`

**Comment by pujiaxin33** [comment]
那你可以尝试注释掉这些代码，看看JXCategoryView能否正常工作。
