### ISSUE TITLE
titleView挡住 在listContainerView 下控制器中的键盘弹出界面

### ISSUE THREAD

**Issue by aa335418265** [pujiaxin33/JXCategoryView#180]
当titleView 在界面很靠底部的时候，listContainerView 中的控制器存在输入框的情况，键盘弹出会被titleView挡住！这个需要我们自己调整吗？IQKeyboard 能解决？

**Comment by pujiaxin33** [comment]
你能截图说明一下吗？关于键盘这种情况我还没有遇到过

**Comment by pujiaxin33** [comment]
其实就是根据键盘的弹出，收回调整列表的contentOffset.y。你可以自己处理，也可以用其他三方库。这个走正常逻辑就行，跟JXCategoryView关系不大哈。
