### ISSUE TITLE
滑动删除手势冲突

### ISSUE THREAD

**Issue by liuxinghudiejie** [pujiaxin33/JXCategoryView#181]
如果列表里添加了滑动删除功能，滑动有时候会响应分页，有时候会响应滑动删除，这个时候怎么解决？能禁用滑动分页，只响应点击分页吗？或者有其他的解决办法吗？

**Comment by liuxinghudiejie** [comment]
我现在是用这个self.listContainerView.scrollView.scrollEnabled = NO;禁止滑动

**Comment by pujiaxin33** [comment]
你的方法是正确的，通过`self.listContainerView.scrollView.scrollEnabled = NO`禁止列表滚动，这样子列表cell的滑动删除就不会有问题了。
