### ISSUE TITLE
关于内容页面TableView侧滑删除手势冲突

### ISSUE THREAD

**Issue by qianhaichao** [pujiaxin33/JXCategoryView#182]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by jenlyser** [comment]
集成后发现跟本身的返回手势冲突,单独使用没问题,一继承项目中的baseController 返回手势就不行.有人能提供一点思路怎么去查找问题吗? 最近项目赶没深入去了解逻辑了. 我看了一些其他的项目也是这样,

**Comment by pujiaxin33** [comment]
@jenlyser 朋友，这是别人提【关于内容页面TableView侧滑删除手势冲突】的ISSUE，你的问题麻烦新开一个ISSUE，然后再分步骤仔细描述一下你的问题呢？

**Comment by pujiaxin33** [comment]
请参考[左滑删除说明](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/%E4%BD%BF%E7%94%A8%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.md)

**Comment by jenlyser** [comment]
朋友,看来有强迫症啊.不喜欢问题太分散是吗?我找时间我整理一下再发,最新的项目暂时没有使用这个了.
