### ISSUE TITLE
增加未读消息数量

### ISSUE THREAD

**Issue by mengkaka** [pujiaxin33/JXCategoryView#183]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

作者做的好用心。有个小小的建议，好多app在 segment 每个item的右上角可以显示数字来代表多少条未读消息。可以参考实现一下！

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/62684338-0d217a00-b9f3-11e9-8b50-4e3ff50e9dc3.png)
这种？
如果不是，麻烦给一个目标效果的截图
