### ISSUE TITLE
有趣的特殊操作 滑动indicator 到一半位置退出到后台，然后再次进去，indicator 无法归正

### ISSUE THREAD

**Issue by shafujiu** [pujiaxin33/JXCategoryView#184]
**bug描述**

滑动切换category下面的内容且只滑动一半，然后退到后台，再次进入demo。底部的内容会自动归正，而我们category的indicator 可能就停留在中间位置了，并不会归正。

**版本号**
1.JXCategoryView版本号：1.2.9
2.手机系统版本号：12.3.1
3.手机型号：iPhone XS Max

**复现步骤**
1. 遇到问题的相关效果、类是：

滑动内容切换不同的category的item的时候，滑动到中间位置 刘海屏通过手势进入后台，然后再进去 就会出现非刘海屏 按下home键 再次进入也会出现 category的indicator 会停留在当你退出后台时候的那个位置，内容可以正确的回到它的位置

2.具体的操作步骤是：

- 打开JXCategoryViewDemo
- 选择指示器样式
- RainbowLineView彩虹效果 进入到详情页
- 滑动内容 使 category的indicator 滑动至"螃蟹"与”麻辣小龙虾“之间
- 非刘海屏点击home键进入后台在进入demo；刘海屏通过上滑手势进入后台，再次进入demo（注意不要杀死demo）
- 最后就会出现如下效果

**截图、GIF**
提供bug出现时的截图或者GIF。
![D2A082F8BABEFA02873270F3A97DE3B1](https://user-images.githubusercontent.com/19347180/62686781-f5002980-b9f7-11e9-9ee9-3c73f4c69300.png)

**Comment by pujiaxin33** [comment]
你重新clone最新的demo仓库，我已经处理好了，但是只是测试了非全面屏手机。你有空帮忙再看看有没有其他逻辑漏洞。没有问题了，后续再打新包。

**Comment by shafujiu** [comment]
好的 谢谢 @pujiaxin33

**Comment by shafujiu** [comment]
> 你重新clone最新的demo仓库，我已经处理好了，但是只是测试了非全面屏手机。你有空帮忙再看看有没有其他逻辑漏洞。没有问题了，后续再打新包。

抱歉比较晚回你，代码已经看到了，也就是在我们滑动过程中需要needReloadByBecomeActive=YES, 其他任何能够选中到目标位置的 selectCellAtIndex ->  needReloadByBecomeActive=NO;  很合理 趋于完美 哈哈

**Comment by pujiaxin33** [comment]
因为影响不大，我就晚点更新包了

**Comment by shafujiu** [comment]
> 因为影响不大，我就晚点更新包了

👌那就有劳了
