### ISSUE TITLE
可以支持 cell 可以实现箭头点击效果吗

### ISSUE THREAD

**Issue by kchtin** [pujiaxin33/JXCategoryView#185]
**Feature描述**
请简单描述你想要的效果：类似京东商品排序功能.

**参考效果**
![Snip20190809_2](https://user-images.githubusercontent.com/18479092/62753889-16b4eb80-baa0-11e9-9ca7-e504a076ad7c.png)

**其他补充**
关于目标效果的其他说明：在选中的情况下,再次点击 cell 可以实现另一种状态(箭头向上)?
再点击其他 cell 或者点击自身,箭头效果恢复原样?

**Comment by pujiaxin33** [comment]
最新的demo工程添加了该效果
路径：【自定义效果示例】-》【京东商品排序cell】
重点提示：
- 该类只在demo工程才有，所以需要将它通过文件引入；
- 仅提供思路，具体细节修改请自己思考并通过修改代码完成。
