### ISSUE TITLE
如果只有一个类别的时候 能否这设置为居左,目前是居中

### ISSUE THREAD

**Issue by guokelide** [pujiaxin33/JXCategoryView#186]
如果只有一个类别的时候 能否这设置为居左,目前是居中

**Comment by pujiaxin33** [comment]
请认真查看示例或【常见问题和答案】，再找不到，再来问

**Comment by SunShineLOL** [comment]
> 如果只有一个类别的时候 能否这设置为居左,目前是居中
//JXSegmentedBaseDataSource
    /// 当collectionView.contentSize.width小于JXSegmentedView的宽度时，是否将itemSpacing均分。
    open var isItemSpacingAverageEnabled: Bool = true

**Comment by pujiaxin33** [comment]
@SunShineLOL 你这是swift版本的代码

**Comment by pujiaxin33** [comment]
`averageCellSpacingEnabled = NO;`
