### ISSUE TITLE
请教下demo里面的特殊效果里面的垂直列表滚动 用UITableView怎么弄

### ISSUE THREAD

**Issue by xuhuaping** [pujiaxin33/JXCategoryView#187]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
请clone最新仓库，查看【垂直列表滚动(UITableView)】示例

**Comment by xuhuaping** [comment]
> 请克隆最新仓库，查看【垂直列表滚动（UITableView的）】示例

好的  谢谢
