### ISSUE TITLE
富文本可以设置选中状态的富文本吗？

### ISSUE THREAD

**Issue by YuanJiaShuai** [pujiaxin33/JXCategoryView#19]
富文本的样式可以设置为下划线样式吗？或者可以设置选中状态的富文本样式吗？

**Comment by pujiaxin33** [comment]
当然可以，但是这是需要自己自定义实现。因为富文本没有一个标准设计。
就像demo工程里面的JXCategoryTitleAttributeView，只是一个示例。
如果想要添加选中的富文本样式，给JXCategoryTitleAttributeView添加一个类似于attributeTitles的选中文本数组，并且在JXCategoryTitleAttributeCell处理一下选中逻辑即可。

**Comment by YuanJiaShuai** [comment]
🙏，已解决！
