### ISSUE TITLE
使用JXCategoryListCollectionContainerView 的时候, 先把每一个page都加载一次,发现在滑动的时候,  即将进入的那个listvc 会先调用 viewWillDisappear

### ISSUE THREAD

**Issue by kchtin** [pujiaxin33/JXCategoryView#199]
使用JXCategoryListCollectionContainerView 的时候, 先把每一个page都加载一次,发现在滑动的时候,  即将进入的那个listvc 会先调用 viewWillDisappear

**Comment by kchtin** [comment]
正确应该是被完全划走的时候,调用viewWillDisappear 和viewDidDisappear.
在
didEndDisplayingCell:
方法中添加[list.listView removeFromSuperview] 就变得正常了.

**Comment by pujiaxin33** [comment]
目前不能依赖VC的viewWillDisappear等生命周期方法，需要使用listDidAppear方法。但是考虑到普遍都使用UIViewController当做列表容器，可能会优化这种情况。

**Comment by pujiaxin33** [comment]
请clone最新仓库，我增加了对UIViewController生命周期方法的支持，请先体验demo，并提出意见，后续没有问题会打包。

**Comment by pujiaxin33** [comment]
请使用1.5.0版本，并参考[1.5.0版本迁移指南](https://github.com/pujiaxin33/JXCategoryView/blob/master/Migration/1.5.0%E7%89%88%E6%9C%AC%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97.md) 和 [列表的生命周期方法处理](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/列表的生命周期方法处理.md)
