### ISSUE TITLE
选项较少时，指示线如何和文字同宽

### ISSUE THREAD

**Issue by H4AER** [pujiaxin33/JXCategoryView#20]
https://upload-images.jianshu.io/upload_images/1290409-fbcf794940e8d5d5.png?

**Comment by pujiaxin33** [comment]
目前的方案会比较麻烦。添加如下代码即可：
CGFloat totalCellWidth = 0;
    for (NSString *title in self.titles) {
        totalCellWidth += ceil([title boundingRectWithSize:CGSizeMake(MAXFLOAT, 30) options:NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading attributes:@{NSFontAttributeName : [UIFont systemFontOfSize:15]} context:nil].size.width);
    }
    self.myCategoryView.cellSpacing = (self.view.bounds.size.width - totalCellWidth)/((self.titles.count - 1) + 2);
    self.myCategoryView.averageCellWidthEnabled = NO;

**Comment by pujiaxin33** [comment]
可能考虑把averageCellWidthEnabled字段去掉。当内容过少的时候，不要去调整cell宽度，而是去调整cellSpacing可能会更好一些

**Comment by H4AER** [comment]
了解，thx

**Comment by pujiaxin33** [comment]
最新仓库已经更新为averageCellSpacingEnabled字段，内部逻辑为调整cellSpacing。pods需要晚些时间更新
