### ISSUE TITLE
关于使用 JXCategoryListCollectionContainerView . 嵌入listVC时生命周期的想法

### ISSUE THREAD

**Issue by kchtin** [pujiaxin33/JXCategoryView#200]
在vc 中, 如果vc.view 被addsubview:
那么,系统会调用 viewWillAppear:和viewDidAppear方法 , 所有觉得代理方法中的listDidAppear 实际上应该是 listWillAppear.

listDidAppear 应该是 当代理方法调用JXCategoryBaseView.m 的selectCellAtIndex:selectedType: 的最后面.
即 该位置为选中某page 或者完全滚动到某page 的时刻
did 应该被理解为完成的意思.

例如我们从Avc push 到Bvc , 如果有动画, 需要在B完成动画才会调用viewDidAppear一样

我尝试过在selectCellAtIndex:selectedType::后面发送通知到JXCategoryListCollectionContainerView, 但是初次进入该页面和点击menuView的Item(不设置过度动画)当listvc 还未初始化的时候, 并无法有效的调用listDidAppear:方法. 所以想请教一下作者,能不能帮我解决一下这个问题.

**Comment by pujiaxin33** [comment]
1、为什么只有`listDidAppear`代理方法？
就是因为列表的切换，无法定义什么是willAppear，什么是DidAppear，所以就没有写两个代理方法，就只用了`listDidAppear`来表示，列表显示了。（这个后续会考虑优化）
2、如果vc.view 被addsubview:那么,系统会调用 viewWillAppear:和viewDidAppear方法
这种情况系统的viewWillAppear:和viewDidAppear方法是不可信的，具体可以参考一下的系统API说明：
```
// If a custom container controller manually forwards its appearance callbacks, then rather than calling
// viewWillAppear:, viewDidAppear: viewWillDisappear:, or viewDidDisappear: on the children these methods
// should be used instead. This will ensure that descendent child controllers appearance methods will be
// invoked. It also enables more complex custom transitions to be implemented since the appearance callbacks are
// now tied to the final matching invocation of endAppearanceTransition.
- (void)beginAppearanceTransition:(BOOL)isAppearing animated:(BOOL)animated __OSX_AVAILABLE_STARTING(__MAC_NA,__IPHONE_5_0);
```
3、初次进入该页面和点击menuView的Item(不设置过度动画)当listvc 还未初始化的时候, 并无法有效的调用listDidAppear:方法
本身库是没有问题的，不知道你修改了什么

**Comment by pujiaxin33** [comment]
请clone最新仓库，我增加了对UIViewController生命周期方法的支持，请先体验demo，并提出意见，后续没有问题会打包。

**Comment by pujiaxin33** [comment]
请使用1.5.0版本，并参考[1.5.0版本迁移指南](https://github.com/pujiaxin33/JXCategoryView/blob/master/Migration/1.5.0%E7%89%88%E6%9C%AC%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97.md) 和 [列表的生命周期方法处理](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/列表的生命周期方法处理.md)
