### ISSUE TITLE
嵌套使用的时候，使用比较繁琐

### ISSUE THREAD

**Issue by sunlight2728** [pujiaxin33/JXCategoryView#201]
嵌套使用的时候，使用比较繁琐
一个VC上嵌套 好难受

**Comment by pujiaxin33** [comment]
嵌套只是提供思路，你可以自己优化代码结构

**Comment by lobby2019** [comment]
问个问题，在嵌套的时候，想在同一个listContainerView下，切换view。改变listContainerView的大小，请问如何实现

**Comment by pujiaxin33** [comment]
滑动的过程，改变容器的大小  
这是什么效果？

**Comment by lobby2019** [comment]
> 滑动的过程，改变容器的大小
> 这是什么效果？

一个listContainerView下有3个view. 三个view的高度是不一样的，也就是当前显示的view要变成我要的高度，而不是listContainerView 的高度

**Comment by pujiaxin33** [comment]
感觉好复杂，你自己fork自定义试试

**Comment by sunlight2728** [comment]
JXCategoryView 
从入门到放弃
嵌套的好辛苦
还是用这玩意简单点  WMPageController

**Comment by pujiaxin33** [comment]
我简单优化了嵌套示例，你可以看一下

**Comment by sunlight2728** [comment]
嵌套时候的位置信息怎么获取
嵌套要请求不同的数据

**Comment by mrxiruo** [comment]
嵌套使用，我也在多个demo中尝试使用了，其实还挺不错的。不过像socket频繁刷新每页数据的时候，有点麻烦。
