### ISSUE TITLE
JXCategoryListCollectionContainerView 进行横竖屏切换闪动

### ISSUE THREAD

**Issue by ismilesky** [pujiaxin33/JXCategoryView#202]
老哥，使用JXCategoryListCollectionContainerView进行嵌套使用，当横竖屏进行切换的时候，界面会闪动，比如当前第一页，当横屏切换至竖屏过程中，JXCategoryListCollectionContainerView 的 cellForItemAtIndexPath 方法，会加载 下一页的界面，然后在回到当前页，造成闪动
怎么避免这个问题
![11](https://user-images.githubusercontent.com/12742733/64420389-c302e580-d0d1-11e9-9679-beaf773bff83.gif)

**Comment by pujiaxin33** [comment]
因为列表再willDisplayCell方法里面触发加载，然后现在只有`- (void)traitCollectionDidChange:(nullable UITraitCollection *)previousTraitCollection`代理方法，没有willChange的代理方法，所以做不到。

**Comment by pujiaxin33** [comment]
其实主要得知，将要转屏，已经转屏结束的通知，就可以解决，但是现在没有可用的api能够得知。

**Comment by pujiaxin33** [comment]
请使用1.5.1版本
