### ISSUE TITLE
JXCategoryView背景可以设置左上角和右上角设置圆角吗

### ISSUE THREAD

**Issue by zhouxiaowei** [pujiaxin33/JXCategoryView#203]
JXCategoryView背景可以设置左上角和右上角设置圆角吗

**Comment by pujiaxin33** [comment]
你可以换一个思路，JXCategoryView的背景色是透明的，你只是在和JXCategoryView相同的位置下面放一个左上角和右上角设置圆角的自定义视图。

**Comment by sssherlock** [comment]
> JXCategoryView背景可以设置左上角和右上角设置圆角吗

请问下你是怎么实现的？

**Comment by Liyongcong** [comment]
> JXCategoryView背景可以设置左上角和右上角设置圆角吗

你好，这个效果你实现了，应该怎么做呀
