### ISSUE TITLE
cell设置圆角跟边框

### ISSUE THREAD

**Issue by BinBear** [pujiaxin33/JXCategoryView#204]
**Feature描述**
请简单描述你想要的效果：？
你好，请教一下，cell可以设置边框跟边框跟圆角吗，设计搞如下

**参考效果**
如果你想要实现一个其他APP已有的效果：
![image](https://user-images.githubusercontent.com/13587915/64599120-6f530d80-d3eb-11e9-81dc-355f74df6d32.png)

**其他补充**
关于目标效果的其他说明：？

**Comment by xjh093** [comment]
改了个圆角的：
https://github.com/xjh093/JHCategoryRoundView

**Comment by pujiaxin33** [comment]
请参考自定义示例，自己DIY，没有现成的类。

**Comment by pujiaxin33** [comment]
请参考自定义示例里面一个相关的的例子
