### ISSUE TITLE
标题太长时固定标签宽度省略号表示后面内容

### ISSUE THREAD

**Issue by QiuXiaochun** [pujiaxin33/JXCategoryView#206]
你好，

项目中，数据的标题内容由于太长，于是想固定宽度，只显示一定宽度的内容，多余的由省略号表示，类似于UILabel展示过多内容时的省略。比如有10个字，我只限定展示4个字，多余的就省略。

但是设置了后，所有的标题挤在一起了。不知道是不是我设置的不对还是怎么的。我只设置了cell的宽度固定，另外间隙调整了也没想要的效果。

**Comment by pujiaxin33** [comment]
目前不支持该特性哈

**Comment by pujiaxin33** [comment]
你可以自己处理文字，不如超过4个字符，就转换为xxxx...

**Comment by QiuXiaochun** [comment]
好的，谢谢，我懂了。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 暴走的鑫鑫 <notifications@github.com>
发送时间: Wednesday, September 18, 2019 5:09:16 PM
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com>
抄送: QiuXiaochun <qiuxiaochunlive@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pujiaxin33/JXCategoryView] 标题太长时固定标签宽度省略号表示后面内容 (#206)


你可以自己处理文字，不如超过4个字符，就转换为xxxx...

―
