### ISSUE TITLE
pod 升级 

### ISSUE THREAD

**Issue by yFeii** [pujiaxin33/JXCategoryView#208]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。
由 1.3.14 升级 1.3.19      ，出现闪退.
**版本号**
1.JXCategoryView版本号：1.3.14 ->1.3.19       升级
2.手机系统版本号：12.1.4
3.手机型号：iPhone X

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
![image](https://user-images.githubusercontent.com/24515770/65326216-89f36680-dbe3-11e9-9fb3-e9dc0ba3c51f.png)

**Comment by pujiaxin33** [comment]
你的tableHeaderView要提前初始化，这里通过代理方法才能获取到

**Comment by pujiaxin33** [comment]
如果还有问题请升级到1.5.1版本，[1.5.0版本迁移指南](https://github.com/pujiaxin33/JXCategoryView/blob/master/Migration/1.5.0%E7%89%88%E6%9C%AC%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97.md)
