### ISSUE TITLE
关于JXCategoryListContentView中reloadData的疑问

### ISSUE THREAD

**Issue by mrxiruo** [pujiaxin33/JXCategoryView#209]
JXCategoryListContentView中reloadData方法，针对validListDict做了以下处理：

```
    for (id<JXCategoryListContentViewDelegate> list in _validListDict.allValues) {
        [[list listView] removeFromSuperview];
    }
    [_validListDict removeAllObjects];
```

这样的话，当处于拖拽中页面刷新时，会出现错乱的问题。

如果我把上面的代码去掉，请问有什么影响吗？ @pujiaxin33

**Comment by pujiaxin33** [comment]
你是在拖拽页面的时候调用reloadData方法吗？

**Comment by mrxiruo** [comment]
> 你是在拖拽页面的时候调用reloadData方法吗？

我的场景是收到socket消息会刷新页面

**Comment by pujiaxin33** [comment]
你应该只需要刷新你的列表，如果你调用了JXCategoryView的reloadData会导致整个列表也会重新加载。

**Comment by mrxiruo** [comment]
但是我title和列表都需要刷新的，title和列表的数据都是可变的，并且有两级嵌套的。😆

**Comment by pujiaxin33** [comment]
那我只能建议你想办法，当socket消息到来时，刷新了title和列表，并且自己想办法终止掉当前正在拖拽中的状态。相当于刷新的时候，如果列表正在拖拽，需要重置，不能继续响应手势。

**Comment by mrxiruo** [comment]
好的谢谢，手势的问题我倒也尝试过。不过话说回来，如果我title固定的，之前你说的“只需要刷新你的列表”是怎么操作？是不是只调用listContainerView的reloadData？

**Comment by pujiaxin33** [comment]
“只需要刷新你的列表”的意思是，你当前显示的单个列表而已
