### ISSUE TITLE
JXCategoryTitleImageView的titleImageSpacing属性在iOS13中失效，只有点击category后才会生效

### ISSUE THREAD

**Issue by CoolPrince** [pujiaxin33/JXCategoryView#210]
如题。

**Comment by hbxfnsm** [comment]
Demo中的都有问题.点击了才会刷新
一堆花里胡哨，分栏组件加入分页有啥用。不如专门开个新库

**Comment by zzw19880707** [comment]
> 如题。
   可以临时添加这个属性解决 self.myCategoryView.titleLabelAnchorPointStyle = JXCategoryTitleLabelAnchorPointStyleTop;

**Comment by CoolPrince** [comment]
好的，谢谢，我试试。

**Comment by zzw19880707** [comment]
ios11的机型也会出现此问题，版本号1.5.1

**Comment by pujiaxin33** [comment]
已修复，预计会在1.5.2办法发布。
