### ISSUE TITLE
关于代理方法

### ISSUE THREAD

**Issue by lobby2019** [pujiaxin33/JXCategoryView#211]
**Feature描述**
请简单描述你想要的效果：？
需要第一次刷新数据并且每次滚动刷新，去调用一个方法

- (id<JXCategoryListContentViewDelegate>)preferredListAtIndex:(NSInteger)index ；
- (void)categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex:(NSInteger)index ；

目前如果在这两个地方都去调用，未加载过的view。会导致重复调用两次， 所以，有没有代理方法，只调用一次。
**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by lobby2019** [comment]
其实也就是第一次刷新数据的时候，在第一页，有没有办法 触发 (void)categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex:(NSInteger)index ；

**Comment by pujiaxin33** [comment]
第一次初始化的时候，并不会触发didSelectedItemAtIndex方法，需要用户点击选中、滚动选中、或者调用selectItemAtIndex方法才会触发。针对第一次的时候，建议你自己做特殊处理。因为第一次初始化的时候，你自己是知道这个事件的。
