### ISSUE TITLE
JXCategoryTitleView defaultSelectedIndex不为0时，JXCategoryListContainerView里的页面不显示

### ISSUE THREAD

**Issue by ziyujing** [pujiaxin33/JXCategoryView#212]
**bug描述**
初始化JXCategoryListContainerView与JXCategoryTitleView时，将defaultSelectedIndex设置为1，JXCategoryListContentViewDelegate里配置的view不显示，需要滑动才会显示。

**版本号**
1.JXCategoryView版本号：1.5.0
2.手机系统版本号：12.4.1
3.手机型号：iPhone XR

**复现步骤**
1. 遇到问题的相关效果、类是：刷新数据+UICollectionView封装列表 LoadDataListCollectionViewController？
2.具体的操作步骤是：初始化的时候将defaultSelectedIndex设置为非0？

**截图、GIF**
提供bug出现时的截图或者GIF。
<img width="1171" alt="屏幕快照 2019-09-25 11 11 10" src="https://user-images.githubusercontent.com/11850686/65566496-9e3db780-df85-11e9-842a-26cbf2d66d75.png">

![Simulator Screen Shot - iPhone Xʀ - 2019-09-25 at 11 11 26](https://user-images.githubusercontent.com/11850686/65566417-574fc200-df85-11e9-95f0-9f9c360433cf.png)

**Comment by FunnyFzl** [comment]
还需要设置: listContainerView.setDefaultSelectedIndex(1)

**Comment by ziyujing** [comment]
> 还需要设置: listContainerView.setDefaultSelectedIndex(1)

1.5.0的版本是不用再设置：listContainerView.setDefaultSelectedIndex(1)

**Comment by InsectQY** [comment]
遇到同样的问题，希望作者解决一下

**Comment by pujiaxin33** [comment]
1.5.1版本做了优化，请升级一下再试试。
执行pod repo update 就会有新版本了。
