### ISSUE TITLE
切换JXCategoryListContainerType 遇到的问题

### ISSUE THREAD

**Issue by FunnyFzl** [pujiaxin33/JXCategoryView#213]
使用JXCategoryListContainerType_CollectionView 的type 创建, 加载正常,但只是单纯切换了type 为: JXCategoryListContainerType_ScrollView之后, 初始化加载index=0的tableview 没有加到scrollView 上, index > 0 的是正常的
请问这是什么情况?

**Comment by FunnyFzl** [comment]
在 type= JXCategoryListContainerType_ScrollView 情况下,设置categoryView.defaultSelectedIndex = 0,第0 的不显示, = 2 第2个不显示

**Comment by FunnyFzl** [comment]
升级到1.5.1 之后就没有这个问题了,1.5.0 肯定是有这个问题的,

**Comment by pujiaxin33** [comment]
是的，1.5.1修复了defaultSelectedIndex的问题
