### ISSUE TITLE
selectItemAtIndex设置时，indicator还是保持在上一个item没有更新

### ISSUE THREAD

**Issue by Merlity** [pujiaxin33/JXCategoryView#214]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
使用selectItemAtIndex设置某个item时，indicator没有更新到设置的那个item上，还是停留在上一个item。

**版本号**
1.JXCategoryView版本号：1.5.0
2.手机系统版本号：iOS13
3.手机型号：iPhone11

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryTitleview和indicator结合使用
2.具体的操作步骤是：在didSelected代理方法里使用selectItemAtIndex指向某个item，但是indicator还是保持在上一个item下。

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
能再提供一下代码截图吗？

**Comment by pujiaxin33** [comment]
不能在didSelected里面再调用selectItemAtIndex哟，indicator本身就会跟着选中的index走的。建议你认真参考demo的写法。

**Comment by Merlity** [comment]
> 不能在didSelected里面再调用selectItemAtIndex哟，indicator本身就会跟着选中的index走的。建议你认真参考demo的写法。

**Comment by Merlity** [comment]
> 不能在didSelected里面再调用selectItemAtIndex哟，indicator本身就会跟着选中的index走的。建议你认真参考demo的写法。

谢谢作者

**Comment by Merlity** [comment]
sdasd
