### ISSUE TITLE
从1.4.0升级到1.5.0后，提示找不到这个协议JXCategoryListCollectionContentViewDelegate

### ISSUE THREAD

**Issue by 008v** [pujiaxin33/JXCategoryView#215]
如题

**Comment by pujiaxin33** [comment]
请参考[1.5.0迁移指南](https://github.com/pujiaxin33/JXCategoryView/blob/master/Migration/1.5.0%E7%89%88%E6%9C%AC%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97.md)

JXCategoryListCollectionView已经被删除了。
