### ISSUE TITLE
当使用图文样式时，图片与文字会产生重叠。滑动或者点击后恢复正常

### ISSUE THREAD

**Issue by MjzDk** [pujiaxin33/JXCategoryView#216]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
当使用图文样式时，图片与文字会产生重叠。滑动或者点击后恢复正常

**版本号**
1.JXCategoryView版本号：1.5.0
2.手机系统版本号：ios13
3.手机型号：iphone7

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：进入图文样式

**截图、GIF**
提供bug出现时的截图或者GIF。

![261569566072_ pic](https://user-images.githubusercontent.com/25068948/65747521-3b3e5300-e134-11e9-81e1-d93b19a9b180.jpg)

**Comment by pujiaxin33** [comment]
已修复，预计会在1.5.2办法发布。
