### ISSUE TITLE
PagingViewBannerTableHeaderView 图片滚动不会居中

### ISSUE THREAD

**Issue by coooliang** [pujiaxin33/JXCategoryView#218]
**bug描述**
PagingViewBannerTableHeaderView 图片滚动不会居中

**版本号**
1.JXCategoryView版本号：1.3.19
2.手机系统版本号：13.0
3.手机型号：iphone 11 pro max 模拟器

**复现步骤**
1. 遇到问题的相关效果、类是：设置了图片，左右滚动时，图片有时会不居中，我设置20的距离，会显示25？
2.具体的操作步骤是：左右滑动时会出现

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
你这是JXPagingView库的问题吧，建议你到JXPagingView提交ISSUE，还有最好粘贴相关代码，你的描述我根本看不懂。有Gif说明就更好了。
