### ISSUE TITLE
建议reloadData后默认选中第一个

### ISSUE THREAD

**Issue by haofanning** [pujiaxin33/JXCategoryView#219]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
如果JXCategoryTitleView的数据源改变后，数组个数可能会发生变化，reloadData如果不默认选中第一个，一旦数据源发生改变，选中位置会随着新的数据源变化而造成数组越界问题

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
> 选中位置会随着新的数据源变化而造成数组越界问题

越界的代码位置在哪里呢？我内部做了判断的，越界会默认设置为0的

**Comment by haofanning** [comment]
哦，看了下代码，确实做过判断了。今天又测出一个问题，用listContainerView有时候子页面的生命周期方法在第一次页面加载的时候不执行，再次打开才可以

**Comment by pujiaxin33** [comment]
> 今天又测出一个问题，用listContainerView有时候子页面的生命周期方法在第一次页面加载的时候不执行，再次打开才可以

请提供一下系统版本，复现路径

**Comment by haofanning** [comment]
用模拟器出现的，系统13.1  滑动的时候生命周期方法第一次不会走，再次滑动到该页面会走；直接点击上面按键方法是正常执行的

**Comment by pujiaxin33** [comment]
同样的ios13.1模拟器，并没有出现你说的情况。建议你录制一个视频，或者按按步骤详细描述你的复现路径。

**Comment by haofanning** [comment]
![aaa](https://user-images.githubusercontent.com/9473376/66731646-f122d480-ee8a-11e9-9ba6-def4d15d4c02.gif)
这是录制的，加载页面数据的方法放在了viewdidappear方法中，而且我加断点测了也是一样，滑动过程中viewdidappear方法并不是每次都执行，点击上面的按键是一定会执行的

**Comment by pujiaxin33** [comment]
你能直接用示例demo复现吗？
我想排除一下，是否应该你项目加了某些代码引起的问题。
