### ISSUE TITLE
好像没有支持调用viewWillAppear？

### ISSUE THREAD

**Issue by tanjieaa** [pujiaxin33/JXCategoryView#22]

**Comment by xclidongbo** [comment]
这个得自己写.
[添加子视图控制器时，子视图控制器的 viewWillAppear 方法不调用](https://blog.csdn.net/u012907783/article/details/78972227)
[addChildViewController 与 viewWillAppear、viewDidAppear 关系说明](https://blog.csdn.net/zhaoxy_thu/article/details/50826190)

**Comment by tanjieaa** [comment]
这些都看过了，不过都没用

**Comment by pujiaxin33** [comment]
请参考最近仓库的`JXCategoryListVCContainerView`类，及在`LoadDataViewController`类的使用示例
