### ISSUE TITLE
设置pinSectionHeaderVerticalOffset后，立刻点击title无反应

### ISSUE THREAD

**Issue by coooliang** [pujiaxin33/JXCategoryView#220]
设置pinSectionHeaderVerticalOffset后，立刻点击title切换列表，无反应，需要等待或是再次点击才可以。

**Comment by coooliang** [comment]
![2019-10-09 14 13 45](https://user-images.githubusercontent.com/8264563/66456151-6f543500-ea9f-11e9-80d6-1d20968b8e5d.gif)

向上滚动后马上点击title切换列表无效，需要等一下或者点两下

**Comment by coooliang** [comment]
真是日了狗了，技术有限，完全看不懂什么个逻辑，各种嵌套。。没找到原因

**Comment by pujiaxin33** [comment]
你可以加我QQ：317437084， 然后把demo发给我，加好友时请备注一下来自Github
