### ISSUE TITLE
添加SDCycleScrollView为TableView的Header，左右滑动和SDCycleScrollView的左右滑动冲突

### ISSUE THREAD

**Issue by lztbwlkj** [pujiaxin33/JXCategoryView#221]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**

按在TableView的Header上左右滑动结果JXCategoryListContainerView的子视图滑动而SDCycleScrollView部分不左右滑动

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：iOS12
3.手机型号：iPhone 7

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
![246FE4EDF6501C9390DF0A777411B2F6](https://user-images.githubusercontent.com/20568661/66532681-c2cb8f00-eb42-11e9-9878-60c6d9b4c45e.jpg)

**Comment by pujiaxin33** [comment]
你能加我qq发一个demo给我吗？317437084

**Comment by lztbwlkj** [comment]
刚我不知道改了什么，自己又好了,Q.Q!!
