### ISSUE TITLE
defaultSelectedIndex默认选择某一个的时候  默认界面没有数据

### ISSUE THREAD

**Issue by xuhuaping** [pujiaxin33/JXCategoryView#223]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
JXCategoryView版本号：？
使用代码？

**Comment by xuhuaping** [comment]
> 使用

1.5.0

**Comment by pujiaxin33** [comment]
你能用demo复现吗？
你能用最新的1.5.2试试吗？

**Comment by IChengLiWei** [comment]
self.myCategoryView.defaultSelectedIndex = 1;  为什么用这个没有实现效果 始终选择的第一个

**Comment by lxx0406** [comment]
> self.myCategoryView.defaultSelectedIndex = 1;  为什么用这个没有实现效果 始终选择的第一个

你好，问下，你的默认的那个不显示数据解决了吗

**Comment by pujiaxin33** [comment]
@IChengLiWei @lxx0406 请使用最新版本，后者自己加上listContainerView.defaultSelectedIndex=1

**Comment by yuanyedehuhuan** [comment]
self.categoryView.defaultSelectedIndex = 1; 我也遇到这个问题，1.5.0，效果是标题栏选中的是第1个，但是控制器选中的是第0个，但是demo中没有复现。

**Comment by pujiaxin33** [comment]
@yuanyedehuhuan 最好能提供一个能复现的demo，我才好分析具体原因

**Comment by mailes** [comment]
需要两个都设置.
 self.myCategoryView.defaultSelectedIndex=0;
 self.listContainerView.defaultSelectedIndex=0;

**Comment by yuanyedehuhuan** [comment]
@mailes 两个都设置试过，也不行。我写一个demo吧，然后发出来。

**Comment by IChengLiWei** [comment]
> > self.myCategoryView.defaultSelectedIndex = 1;  为什么用这个没有实现效果 始终选择的第一个
> 
> 你好，问下，你的默认的那个不显示数据解决了吗



> self.categoryView.defaultSelectedIndex = 1; 我也遇到这个问题，1.5.0，效果是标题栏选中的是第1个，但是控制器选中的是第0个，但是demo中没有复现。

那个只设置了标题的默认选项，还需要选择默认的控制器

**Comment by IChengLiWei** [comment]
升级到1.5.2 在加上了这句代码就对了  [self.listContainerView didClickSelectedItemAtIndex:1];

**Comment by yuanyedehuhuan** [comment]
@IChengLiWei 1.5.2现在可以通过cocoapods引入吗

**Comment by yuanyedehuhuan** [comment]
@IChengLiWei 使用1.5.2可以解决这个问题，但是貌似 index==1 的控制器并没有加载出来

**Comment by lxlnihao** [comment]
![image](https://user-images.githubusercontent.com/16555566/71718253-8ebbed80-2e55-11ea-9325-8151e444ab08.png)
你好 使用你们这个三方库 我创建的时候设置了标题头 请求到数据之后怎么重新设置一下未使用的数量 没有找到合适的方法 谢谢

**Comment by pujiaxin33** [comment]
更新titles等数据，调用reloadDataWithoutListContainer
