### ISSUE TITLE
Feature 建议

### ISSUE THREAD

**Issue by xygkevin** [pujiaxin33/JXCategoryView#224]
**Feature描述**
页面滚动的时候标题跟着滚动，始终保持居中，而不是每一个页面滚动结束后再居中标题；

**参考效果**
蜻蜓FM
![15276C97194EF2934A79AF3AEA077FF6](https://user-images.githubusercontent.com/19592642/66697082-0241d900-ed05-11e9-9316-8a5896142638.JPG)

**Comment by pujiaxin33** [comment]
有空会尝试一下

**Comment by smallidiot** [comment]
特殊效果里，垂直列表滚动（uicollectionview）这个效果，最后一个分组的时候，有没有可能改成不是一屏，而是数据有多少就显示多少，没有空白部分

**Comment by pujiaxin33** [comment]
@smallidiot 【垂直列表滚动】效果只是给出了示例代码，你想要微调。请自行修改。

**Comment by smallidiot** [comment]
> @smallidiot 【垂直列表滚动】效果只是给出了示例代码，你想要微调。请自行修改。

//如果最后一个section条目太少了，会导致滚动最底部，但是却不能触发categoryView选中最后一个item。而且点击最后一个滚动的contentOffset.y也不要弄。所以添加contentInset，让最后一个section滚到最下面能显示完整个屏幕。 这是demo里的注释，我的意思是如果让最后一个section没有留白，有没有实现的可能

**Comment by pujiaxin33** [comment]
只要明白实现的原理，你可以自己尝试，可能性嘛，一切皆有可能😆

**Comment by smallidiot** [comment]
> 只要明白实现的原理，你可以自己尝试，可能性嘛，一切皆有可能😆
大佬说可能我才有去尝试的信心
