### ISSUE TITLE
categoryView滑动到最后一个，监听滑动的contentoffset

### ISSUE THREAD

**Issue by lobby2019** [pujiaxin33/JXCategoryView#227]
**Feature描述**
请简单描述你想要的效果：？
手动滑动 categoryView 最后一个，继续向左滑动 需要监听offset,做相应的操作处理？ 请问该怎么实现呢

**Comment by pujiaxin33** [comment]
你可以KVO categoryView.contentView.contentOffset 
试一试呢？
