### ISSUE TITLE
分页手势应该左右滑动

### ISSUE THREAD

**Issue by CoderLGL** [pujiaxin33/JXCategoryView#228]
**Feature描述**
使用手指斜向上或斜向下滑动时页面过于灵敏,本来不应该有变化的,但是翻到了下一页.
这样造成了如果页面内有tableView时,滑动tableView一不小心就造成了翻页.
具体希望修改为只有左右滑动时才翻页.

**参考效果**
在demo cell样式-->大小缩放+cell宽度缩放  

**其他补充**

**Comment by pujiaxin33** [comment]
你可以认真体验一下demo里面的【刷新数据】示例，同一时间，只能垂直滑动列表，或者左右滑动切换列表。不会出现协滑过于灵敏翻页的问题。
