### ISSUE TITLE
列表刷新问题

### ISSUE THREAD

**Issue by zhongxiaomai** [pujiaxin33/JXCategoryView#229]
加载了四个标题(VC)，第一个能下拉刷新，第二个，第三个下拉刷新无效，第四个又能下拉刷新

**Comment by pujiaxin33** [comment]
你能试一下demo里面的【刷新数据】示例吗？用iOS13系统自测没有你说的问题

建议你自己检查一下代码

或者你尝试通过demo复现同样的问题，再告诉我具体的操作路径

**Comment by zhongxiaomai** [comment]
感谢回答，我把VC换成View就解决了
