### ISSUE TITLE
您好，通过scale对文字做放大缩小操作，文字会变虚，请问一下有没有什么好的建议解决这个问题呢~

### ISSUE THREAD

**Issue by wxzwork** [pujiaxin33/JXCategoryView#23]

**Comment by pujiaxin33** [comment]
可以考虑对Font进行操作

**Comment by pujiaxin33** [comment]
最新代码已经优化为对font进行缩放，不会有变模糊的现象了

**Comment by wxzwork** [comment]
感谢回答。不知道你有没有在用虾米音乐，我看他们首页的切换效果，文字的渐变效果基线是保持一致的，也不会变虚，应该不是通过scale操作的，有没有什么思路分享一下😝~

**Comment by pujiaxin33** [comment]
缩放依然是控制font，至于基线对准，只需要自定义cell，控制titleLabel的布局即可（项目默认是居中的），参考自定义JXCategoryView

**Comment by wxzwork** [comment]
好的，谢谢~~
