### ISSUE TITLE
怎样监听停止左右滑动才开始加载列表

### ISSUE THREAD

**Issue by lztbwlkj** [pujiaxin33/JXCategoryView#230]
怎样监听停止左右滑动才开始加载列表

**Comment by lztbwlkj** [comment]
listDidAppear每次左右滑动结束都会加载新数据，而我只想让他第一次加载，

**Comment by pujiaxin33** [comment]
你可以自己做一个标记，isDataLoaded，第一次才加载

**Comment by lztbwlkj** [comment]
还有就是左右滑动的效果能自定义吗？

**Comment by lztbwlkj** [comment]
> 你可以自己做一个标记，isDataLoaded，第一次才加载

明白了

**Comment by pujiaxin33** [comment]
左右滑动的效果无法自定义

你想如何自定义呢？

**Comment by lztbwlkj** [comment]
拉帘效果 类似《学习强国》APP左右滑动

**Comment by pujiaxin33** [comment]
哦，这个之前有人提过，自己实现哈。内部无法处理

**Comment by lztbwlkj** [comment]
那有没有开放出这种定义动画效果的代理？我没找到，还请指教！

**Comment by pujiaxin33** [comment]
没有哈，建议你自己fork修改源码自定义实现
