### ISSUE TITLE
 关于JXCategoryListContainerViewDelegate  不执行 

### ISSUE THREAD

**Issue by ljssafe** [pujiaxin33/JXCategoryView#231]
我在一个JXCategoryListContainerView 的listview里添加了一个JXCategoryListContainerView

结果选中到这个有JXCategoryListContainerView的 view的时候  JXCategoryListContainerViewDelegate 没有执行 断点完全没有进入  

是否嵌套会有此类bug？

**Comment by pujiaxin33** [comment]
你可以参考示例demo的嵌套示例

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
