### ISSUE TITLE
viewController 生命周期问题

### ISSUE THREAD

**Issue by jacinzhang** [pujiaxin33/JXCategoryView#232]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
第一次滑动到一个新页面的时候，没有触发 viewController 的生命周期方法，后面再滑动一次才会触发，新页面的  viewWillAppear viewDidAppear 第一次没有调用，再次滑动回来才调用

**版本号**
1.JXCategoryView版本号：1.5.2
2.手机系统版本号：iOS 13
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
13.1的模拟器、13.2的真机，均没有出现你说的问题，建议你参考demo和文档，再校对一下使用代码呢？

**Comment by jacinzhang** [comment]
真的是有问题啊

**Comment by pujiaxin33** [comment]
现在还有此问题吗？

**Comment by mrxiruo** [comment]
我记得以前是本来就不会走系统的viewWillAppear viewDidAppear，而是要实现listDidAppear啊。现在新版是可以用系统方法了吗？ @pujiaxin33

**Comment by pujiaxin33** [comment]
@mrxiruo 最新版本，如果列表是vc，就会走系统的viewWillAppear等生命周期方法了

**Comment by jiasongs** [comment]
<img width="1372" alt="图片" src="https://user-images.githubusercontent.com/22904757/77045429-231d0180-69fc-11ea-903a-fa0acbac8d3e.png">
这样写会让VC的生命周期提前，会导致一些布局问题或者其他未知的问题，我目前还没有想到解决办法 @pujiaxin33

**Comment by pujiaxin33** [comment]
@jiasongs 能举一个具体的例子吗？

**Comment by pujiaxin33** [comment]
@jiasongs 你可以暂时让列表是UIView，来规避当前的问题。

**Comment by pujiaxin33** [comment]
@jiasongs 这些会导致viewDidLoad方法被调用，但是不至于导致布局出现问题。你能举一个导致布局异常的例子吗？

**Comment by jiasongs** [comment]
> @jiasongs 这些会导致viewDidLoad方法被调用，但是不至于导致布局出现问题。你能举一个导致布局异常的例子吗？

经过测试之后只是viewDidLoad被提前调用了，造成布局的问题是因为当此控制器不在栈顶时，viewDidLayoutSubviews等不会被调用。如果用约束布局的话，这时在此控制器里拿任何View的Frame都是旧值，当此控制器又在栈顶时，viewDidLayoutSubviews等方法会马上被调用，这时候约束开始生效。

**Comment by pujiaxin33** [comment]
> 此时JXCategoryView拿到的VC.View.Frame都是Zero。

发一下具体代码和所在类位置

**Comment by pujiaxin33** [comment]
不要在viewDidLoad里面依赖frame，要不通过约束，要不在viewDidLayoutSubviews布局

**Comment by jiasongs** [comment]
> 不要在viewDidLoad里面依赖frame，要不通过约束，要不在viewDidLayoutSubviews布局



> > 此时JXCategoryView拿到的VC.View.Frame都是Zero。
> 
> 发一下具体代码和所在类位置

刚才想错了，现在修正了下

**Comment by jiasongs** [comment]
> 不要在viewDidLoad里面依赖frame，要不通过约束，要不在viewDidLayoutSubviews布局

没有在viewDidLoad设置frame。这个问题应该与JXCategoryView无关，是UIKit机制的原因。非栈顶的控制器不会触发viewDidLayoutSubviews等方法

**Comment by pujiaxin33** [comment]
好的
