### ISSUE TITLE
针对内存管理功能诉求

### ISSUE THREAD

**Issue by CocoaHcx** [pujiaxin33/JXCategoryView#236]
**Feature描述**
当某个页面涉及到10多个页面及每个页面有很多数据的时候，类库所持有的内存会很接近手机闲暇内存（举例iPhone 6s，开了一部分应用推至后台，再打开一个含有本类库的App，系统会收到多次内存警告，并且导致crash）

**参考效果**
参考斗鱼App，首页有很多分页数据，左右滑动时，如果受到内存警告，会回收部分未显示的页面
。希望就内存管理这块，作者可以抽时间回复一下，我也想听听作者的看法。

再次感谢作者的开源精神，作者的类库对我的帮助是极大的。

**Comment by pujiaxin33** [comment]
你用JXCategoryListContainerType_CollectionView初始化JXCategoryListContainerView，试试呢？

**Comment by CocoaHcx** [comment]
谢谢。按照您的方法内存会有好一些。
此外我在此抛出两个可以优化的地方：
1、当内存吃紧的时候，左右滑动，底部标题进度条动画会偶现卡顿。
2、期待可以有预加载选择机制。

**Comment by pujiaxin33** [comment]
1、应该是CPU负荷多重，导致的页面动画卡顿。这个跟库本身没有关系；
2、预加载属于业务需求，你可以自己实现：在didSelectItem代理方法里面，比如选中了index=1，你就预加载index=2的列表。然后在initListAtIndex检测是否已经有缓存好的列表，有就返回缓存，没有就新创建一个
