### ISSUE TITLE
可否完善点击 JXCategoryBaseCell 时的动画效果

### ISSUE THREAD

**Issue by zhwayne** [pujiaxin33/JXCategoryView#237]
**Feature描述**
注意到在点击标题时的动画效果和滑动 `listContainer` 时的动画效果并不一致。滑动 listContainer 时的动画（包括标题文字和指示器的颜色渐变，大小缩放等等）比较细腻，而点击标题时，标题的动画效果消失（只保留了指示器的动画），比较突兀。查阅代码发现点击标题时的 selectedType 为 `JXCategoryCellSelectedTypeClick`，但这种情况下没有处理标题相关的动画过度代码。

**参考效果**
目标效果可以参考优酷等主流视频客户端，点击标题时文字动画过渡自然。

**其他补充**
对于实现目标效果，是否可以合并容器的滑动和标题点击事件，或者点击标题时也按照滑动容器的方式进行处理？

**Comment by pujiaxin33** [comment]
你再仔细看下demo的示例，里面有点击切换时，文字是动画渐变的。

**Comment by zhwayne** [comment]
> 你再仔细看下demo的示例，里面有点击切换时，文字是动画渐变的。

你好，确认过多次，应该是没有的。另外如果颜色渐变效果不易察觉，可以尝试测试【大小缩放】样式。点击 title 能比较明显看出文字突然变大，而滑动时文字是逐渐变大的。

感谢回复😀

**Comment by pujiaxin33** [comment]
有注意到这个效果吗？点击的时候有动画
![image](https://user-images.githubusercontent.com/12654640/69428577-88bdf180-0d6c-11ea-9e1f-3d84db37e53e.png)

**Comment by zhwayne** [comment]
真的没有🤣 gif 如下
![E6736273-5F88-490E-8CFB-4EA88D687652](https://user-images.githubusercontent.com/10414010/69431827-74312780-0d73-11ea-82a5-9b0b647dcce4.gif)

**Comment by pujiaxin33** [comment]
朋友，你在认真看下我给你的截图呢? 【大小缩放+点击动画】示例都不一样，我要怎么解释呢？

**Comment by zhwayne** [comment]
哦豁，注意到了😂真是不好意思。
