### ISSUE TITLE
如果设置了 mainTableView.contentInset = UIEdgeInsetsMake(64, 0, 0, 0);子VC里的MJRefreshHeader就会无法滑动

### ISSUE THREAD

**Issue by ffzzqq1128** [pujiaxin33/JXCategoryView#239]
![image](https://user-images.githubusercontent.com/19404612/69221858-37b6cd80-0bb3-11ea-9e6d-7ac6d73644c7.png)
这样设置之后JXPagerListRefreshView会变得无法滑动了，很急不知道是什么原因，希望大兄弟能看一下，项目中需要设置透明导航栏

**Comment by ffzzqq1128** [comment]
补充一下是子VC下的滑动滑不了，看不懂是啥原因

**Comment by ffzzqq1128** [comment]
![image](https://user-images.githubusercontent.com/19404612/69222198-ef4bdf80-0bb3-11ea-8d5a-11114e784872.png)
经过测试只要是1，下面的子VC头就无法滑动，兄弟看下呗

**Comment by pujiaxin33** [comment]
你为什么要设置contentInset呢

**Comment by pujiaxin33** [comment]
你想咨询的是JXPagingView效果？

**Comment by ffzzqq1128** [comment]
我们有需求导航栏透明，整个tableView需要盖住导航栏，然后这样会使得categaryView停在最顶端跟导航栏重叠，而不是停在导航栏下面，后来我仔细看头文件发现有个pinSectionHeaderVerticalOffset可以解决这个问题，打扰了，我只是反馈下问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "暴走的鑫鑫"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 下午2:44
收件人: "pujiaxin33/JXCategoryView"<JXCategoryView@noreply.github.com&gt;; 
抄送: "冰之泉"<617323152@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pujiaxin33/JXCategoryView] 如果设置了 mainTableView.contentInset = UIEdgeInsetsMake(64, 0, 0, 0);子VC里的MJRefreshHeader就会无法滑动 (#239)




你为什么要设置contentInset呢

**Comment by pujiaxin33** [comment]
恩，就是想说明这个问题，pinSectionHeaderVerticalOffset会修改内部的contentInset，所以不要自己修改contentInset属性。
