### ISSUE TITLE
如何获取listContainer内对应index的控制器实例

### ISSUE THREAD

**Issue by LockLight** [pujiaxin33/JXCategoryView#241]
以前的版本可以通过JXCategoryListVCContainerView的listVCArray获取到对应的控制器实例,现在的需求是异步获取数据后,传值到对应的控制器,刷新列表

**Comment by pujiaxin33** [comment]
可以通过validListDict获取

**Comment by LockLight** [comment]
感谢解答,该如何刷新内容视图内指定index的列表呢

**Comment by pujiaxin33** [comment]
列表视图，你拿到视图之后，想怎么刷新就怎么刷新，跟框架没有关系

**Comment by LockLight** [comment]
好的 感谢解惑
