### ISSUE TITLE
UITableView左滑删除不灵敏

### ISSUE THREAD

**Issue by LYluyu** [pujiaxin33/JXCategoryView#242]
**bug描述**
我实现了tableView左滑删除的功能，但是和JXCategoryView存在手势冲突，导致左滑删除的功能很难触发，只能通过禁止JXCategoryListContainerView左右滚动。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
是的，左滑删除手势会和列表的左右滚动手势冲突，只能二选一，禁用掉列表的左右滑动，没有其他方案了。
