### ISSUE TITLE
我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存

### ISSUE THREAD

**Issue by lanligang** [pujiaxin33/JXCategoryView#243]
非常感谢您开源您的框架，可以说是非常一流的了，顶礼膜拜一番。
**bug描述**
![1575253962169_BC3AB271-9704-4F8F-A552-C5D456F1A5E0](https://user-images.githubusercontent.com/18440662/69926926-48d7d680-14f1-11ea-9c84-df1ac0cdc5e2.png)
![1575254056562_B7F1317C-85D8-497B-B360-C713CC7171B8](https://user-images.githubusercontent.com/18440662/69926927-48d7d680-14f1-11ea-8327-f3749ed2d900.png)
![1575254095612_81F2A32C-C16E-4579-BCAE-78BDDA662B27](https://user-images.githubusercontent.com/18440662/69926928-49706d00-14f1-11ea-8eef-8e48c9c4e332.png)
![1575254937762_D690386A-137F-4309-9A33-AA9B80CC87F1](https://user-images.githubusercontent.com/18440662/69926955-61e08780-14f1-11ea-89fa-ef8656593d0b.png)

请简单描述你的bug现象。
OC版本中使用了 reloadData  发现 重新调用 
协议方法：
- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index  
但是在您的例子中 我查看了一下之前的控制器没有进行释放，只有当控制器 pop到上一页面时候才进行释放。释放的数量是N 多次。

这里建议：
在这个方法中添加上控制器重用问题的限制，要不然很多人都以为控制器被释放了。
如果这个页面出现在 tabbarController 持有的控制器时，就会出现不释放问题。 

我在下面做了一次控制器的避免重复创建，
如果不想重复创建 就使用 不知道有没有什么问题：
	[self.listContainerView.validListDict.allValues enumerateObjectsUsingBlock:^(id<JXCategoryListContentViewDelegate>  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
		UIViewController *vc = (UIViewController *)obj;
		[vc removeFromParentViewController];
	}];;

**版本号**
1.JXCategoryView版本号：1.5.2

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by xiky** [comment]
我遇到了同样的问题，请问您是怎么处理的

> - (id)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index
>  但是在您的例子中 我查看了一下之前的控制器没有进行释放，只有当控制器 pop到上一页面时候才进行释放。释放的数量是N 多次。

我有一个资讯类的列表，列表可以上拉加载更多，每一个cell打开都是一个`JXCategoryListContainerView`，如果我加载了上百个，也只有`pop`的时候才会释放这些vc

**Comment by lanligang** [comment]
你需要找到他的强持有控制器的那个字典然后每次reload的时候将字典里面的全部滞空



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Livy Yao <notifications@github.com&gt;
发送时间: 2020年2月12日 10:24
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)




我遇到了同样的问题，请问您是怎么处理的
   
(id)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index
 但是在您的例子中 我查看了一下之前的控制器没有进行释放，只有当控制器 pop到上一页面时候才进行释放。释放的数量是N 多次。 
  
我有一个资讯类的列表，列表可以上拉加载更多，每一个cell打开都是一个JXCategoryListContainerView，如果我加载了上百个，也只有pop的时候才会释放这些vc

**Comment by pujiaxin33** [comment]
```objective-c
- (void)reloadData {
    for (id<JXCategoryListContentViewDelegate> list in _validListDict.allValues) {
        [[list listView] removeFromSuperview];
    }
    [_validListDict removeAllObjects];

    if (self.containerType == JXCategoryListContainerType_ScrollView) {
        self.scrollView.contentSize = CGSizeMake(self.scrollView.bounds.size.width*[self.delegate numberOfListsInlistContainerView:self], self.scrollView.bounds.size.height);
    }else {
        [self.collectionView reloadData];
    }
    [self listWillAppear:self.currentIndex];
    [self listDidAppear:self.currentIndex];
}
```
这是reloaddata的代码块
里面有调用`[_validListDict removeAllObjects];`进行引用去除。

**Comment by lanligang** [comment]
可以加我QQ吗？主要我这段时间在家电脑没带
1176281703



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 暴走的鑫鑫 <notifications@github.com&gt;
发送时间: 2020年2月12日 10:34
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)



- (void)reloadData {     for (id<JXCategoryListContentViewDelegate&gt; list in _validListDict.allValues) {         [[list listView] removeFromSuperview];     }     [_validListDict removeAllObjects];     if (self.containerType == JXCategoryListContainerType_ScrollView) {         self.scrollView.contentSize = CGSizeMake(self.scrollView.bounds.size.width*[self.delegate numberOfListsInlistContainerView:self], self.scrollView.bounds.size.height);     }else {         [self.collectionView reloadData];     }     [self listWillAppear:self.currentIndex];     [self listDidAppear:self.currentIndex]; }
 
这是reloaddata的代码块
 里面有调用[_validListDict removeAllObjects];进行引用去除。

**Comment by pujiaxin33** [comment]
哦，是不是列表是vc的情况，要再调用[vc removeFromParentViewController];方法才行？

**Comment by lanligang** [comment]
我记得是，需要把父子控制器关系去除。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 暴走的鑫鑫 <notifications@github.com&gt;
发送时间: 2020年2月12日 10:42
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)




哦，是不是列表是vc的情况，要再调用[vc removeFromParentViewController];方法才行？

**Comment by pujiaxin33** [comment]
那我晚些再自测试一下哈

**Comment by lanligang** [comment]
我看了他是把咱们的控制器持有到一个他内部的控制器中，而且还在字典中强持有，所以两处都必须进行释放才能将引用计数降下来，内存才不至于一路飙升不过你看看他是否还有别的刷新的Api 如果有尽量用他的。我记得有三个刷新的Api



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 暴走的鑫鑫 <notifications@github.com&gt;
发送时间: 2020年2月12日 10:46
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)




那我晚些再自测试一下哈

**Comment by xiky** [comment]
我在工程中没有用到主动reloadData相关的api，我的有点类似于`Example中-特殊效果-刷新数据+封装列表`，在Demo中，也是只有pop时，才会delloc相关vc
![Xnip2020-02-12_11-03-08](https://user-images.githubusercontent.com/17621199/74299370-5a5a1c00-4d87-11ea-9213-8a4d3ba0addf.jpg)

**Comment by lanligang** [comment]
持有控制器如果刷新的时候释放子控制器的刷新就不会在刷新的时候一直创建控制器了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Livy Yao <notifications@github.com&gt;
发送时间: 2020年2月12日 11:04
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)




我在工程中没有用到主动reloadData相关的api，我的有点类似于Example中-特殊效果-刷新数据+封装列表，在Demo中，也是只有pop时，才会delloc相关vc

**Comment by jiasongs** [comment]
请务必这样改动：
![图片](https://user-images.githubusercontent.com/22904757/75619343-b6a9a200-5bb5-11ea-9629-f1c12e4ee4a9.png)
如果不调用removeFromParentViewController，会造成VC延迟释放，内存会一直存在直到当前JXCategoryListContainerView的实例被销毁。
测试，可以使用NSMapTable，初始化时使用弱引用，如下：
![图片](https://user-images.githubusercontent.com/22904757/75619375-04260f00-5bb6-11ea-8b3f-ee5b47d198da.png)
使用如下：
![图片](https://user-images.githubusercontent.com/22904757/75619383-1b64fc80-5bb6-11ea-9dcf-c981601ab84e.png)
如果VC释放，NSMapTable存储的VC会自动移除，经测试发现：
调用VC的removeFromParentViewController，则NSMapTable里不存在此VC，表明VC已经释放
只调用VC.View的removeFromSuperview，则NSMapTable里存在此VC，且此VC的View为nil，表明VC.view已经释放，但VC并没有释放。
请作者有时间及时提交此修改，否则如果有大量VC没释放，可能会造成内存上的问题

**Comment by lanligang** [comment]
我试试第二个方法😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jia Song <notifications@github.com&gt;
发送时间: 2020年3月1日 12:18
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)




请务必这样改动：
 
 如果不调用removeFromParentViewController，会造成VC延迟释放，内存会一直存在直到当前JXCategoryListContainerView的实例被销毁。
 测试，可以使用NSMapTable，初始化时使用弱引用，如下：
 
 使用如下：
 
 如果VC释放，NSMapTable存储的VC会自动移除，经测试发现：
 调用VC的removeFromParentViewController，则NSMapTable里不存在此VC，表明VC已经释放
 只调用VC.View的removeFromSuperview，则NSMapTable里存在此VC，且此VC的View为nil，表明VC.view已经释放，但VC并没有释放。
 请作者有时间及时提交此修改，否则如果有大量VC没释放，可能会造成内存上的问题

**Comment by jiasongs** [comment]
> 我试试第二个方法😂 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Jia Song <notifications@github.com&gt; 发送时间: 2020年3月1日 12:18 收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt; 抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt; 主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243) 请务必这样改动： 如果不调用removeFromParentViewController，会造成VC延迟释放，内存会一直存在直到当前JXCategoryListContainerView的实例被销毁。 测试，可以使用NSMapTable，初始化时使用弱引用，如下： 使用如下： 如果VC释放，NSMapTable存储的VC会自动移除，经测试发现： 调用VC的removeFromParentViewController，则NSMapTable里不存在此VC，表明VC已经释放 只调用VC.View的removeFromSuperview，则NSMapTable里存在此VC，且此VC的View为nil，表明VC.view已经释放，但VC并没有释放。 请作者有时间及时提交此修改，否则如果有大量VC没释放，可能会造成内存上的问题 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

只能等待作者去修正这个问题了

**Comment by lanligang** [comment]
希望作者能够解决。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jia Song <notifications@github.com&gt;
发送时间: 2020年3月1日 12:50
收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt;
抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243)



 
我试试第二个方法😂 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Jia Song <notifications@github.com&gt; 发送时间: 2020年3月1日 12:18 收件人: pujiaxin33/JXCategoryView <JXCategoryView@noreply.github.com&gt; 抄送: lanligang <1176281703@qq.com&gt;, State change <state_change@noreply.github.com&gt; 主题: 回复：[pujiaxin33/JXCategoryView] 我发现调用 [self.categoryView reloadData]; 时候 很多人都不注意控制器重复创建问题导致内存 (#243) 请务必这样改动： 如果不调用removeFromParentViewController，会造成VC延迟释放，内存会一直存在直到当前JXCategoryListContainerView的实例被销毁。 测试，可以使用NSMapTable，初始化时使用弱引用，如下： 使用如下： 如果VC释放，NSMapTable存储的VC会自动移除，经测试发现： 调用VC的removeFromParentViewController，则NSMapTable里不存在此VC，表明VC已经释放 只调用VC.View的removeFromSuperview，则NSMapTable里存在此VC，且此VC的View为nil，表明VC.view已经释放，但VC并没有释放。 请作者有时间及时提交此修改，否则如果有大量VC没释放，可能会造成内存上的问题 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
只能等待作者去修正这个问题了

**Comment by pujiaxin33** [comment]
非常感谢大家的提醒，疫情期间疏忽了开源管理，今天会更新1.5.3版本进行修复
