### ISSUE TITLE
可否自定义调整不同标题之间的cellSpacing

### ISSUE THREAD

**Issue by wxzwork** [pujiaxin33/JXCategoryView#245]
**Feature描述**
作者大大您好，如果想不同的标题之间的间距不一样，该如何调整呢。比如存在三个标题： 标题1 标题2 标题3 ，想让标题1 标题2 之间的间距是20 ，标题2 标题3之间是50

在demo中的示例 title背景cell中，我看JXCategoryBaseCellModel中有个cellSpacing和index，我想
通过判断index，进而设置不同的cellSpacing，但是发现并不比作用。作者大大可否给个思路，还是说需要自己全部自定义titleview

非常感谢。

**Comment by pujiaxin33** [comment]
标题是放在UICollectionView的cell里面的。UICollectionViewFlowLayout本身就不支持不同cell之间的itemSpacing设置。只能统一设置同一个值。你可以给标题加多个空白字符，尝试达到相同的视觉效果呢。

**Comment by 624990742** [comment]
亲爱的作者您好，请问怎么给间距设固定的值呢？
