### ISSUE TITLE
上下滚动、header悬浮功能里可以自定义header吗

### ISSUE THREAD

**Issue by peterios2016** [pujiaxin33/JXCategoryView#249]
**Feature描述**
请简单描述你想要的效果：我这边有个效果比较复杂的header，但是又需要用到这个悬浮的功能

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
个人主页效果，更多详情参考[JXPagingView](https://github.com/pujiaxin33/JXPagingView)

可以自定义header。
