### ISSUE TITLE
关于视图全部加载问题

### ISSUE THREAD

**Issue by pengrun** [pujiaxin33/JXCategoryView#25]
使用categoryview时，初始化了controller，当categoryview所在的父控制器加载完毕后，子控制器也被加载完毕，并且viewDidAppear也调用了。有没有方法，进入时只加载一个，滑动第二个再加载第二个？

**Comment by pujiaxin33** [comment]
建议：
数据源返回之后，new所有的VC，但是先不创建视图和网络请求。等到滑到某个页面再加载。请参考LoadDataViewController。做适当调整即可

**Comment by pengrun** [comment]
> 建议：
> 数据源返回之后，new所有的VC，但是先不创建视图和网络请求。等到滑到某个页面再加载。请参考LoadDataViewController。做适当调整即可

OK。thanks

**Comment by pujiaxin33** [comment]
感谢你的提问，经过时间的考验，发现确实需要延迟加载列表。
在1.1.7版本加入了`JXCategoryListContainerView`类，支持以下特性：
- 高度封装contentScrollView逻辑，只需少量代码即可完成列表容器逻辑；
- 列表懒加载，当通过滚动、点击选中显示某个列表的时候，才进行列表初始化，性能更优；

[JXCategoryListContainerView的详细使用说明](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/JXCategoryListContainerView%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)
