### ISSUE TITLE
希望增加按列排列的视图

### ISSUE THREAD

**Issue by biostome** [pujiaxin33/JXCategoryView#250]
**Feature描述**
请简单描述你想要的效果：
屏幕左侧或者右侧视图，类似主菜单，纵向排列。

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：饿了么
2.目标页面路径：视图控制器或者视图
3.目标效果截图：和JXCategoryView一样，只不过是纵向排列

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
感谢反馈，不支持纵向排列。两者有比较大的区别，不考虑放入该库。即使要实现，也应该新建一个库。
