### ISSUE TITLE
希望支持 标题文字本身 和 指示条 渐变色

### ISSUE THREAD

**Issue by bluesky0109** [pujiaxin33/JXCategoryView#251]
**Feature描述**
希望支持 标题文字本身 和 指示条 渐变色；每个标题文字本身渐变色 ，不是 切换 过程中 2个标题之间渐变过渡 效果

**参考效果**
![1576937628806](https://user-images.githubusercontent.com/8929364/71309084-b0bd7500-243e-11ea-9f93-217fb09ebb48.jpg)

**Comment by pujiaxin33** [comment]
只要是标题本身的自定义，都需要自己自定义实现。请参考文档和demo里面的自定义说明和示例。需要自己多加理解和实践。
