### ISSUE TITLE
如何延迟加载容器控制器内对应的数据请求

### ISSUE THREAD

**Issue by LockLight** [pujiaxin33/JXCategoryView#252]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
### 首先感谢作者的无私奉献,我的需求是这样的
在进入页面后,需要通过异步请求获取到对应的数据,传入到listVCContainerView,listVCContainerView内的控制器通过传入的数据再去请求对应的数据,这样会产生两种处理情况,

1. 使用一次性加载的方式,在viewDidLoad内请求到对应数据后,创建N个VC,加入到listVCArray,然后在initListForIndex内返回,但是当创建的VC过多,VC内的请求也很多的情况下,开销比较大 

2. 使用懒加载的方式,在initListForIndex,滑动到对应index时创建控制器,这样尝试过有一个问题,对应index的子控制器拿不到异步请求所需要的数据

请问,有没有办法用懒加载的方式也可以获取到异步请求的数据,或者使用一次性加载的方式,但是延迟对应index控制器內的请求,滑动到对应index再请求.

再次感谢

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
两种方案都可以。

### 一次性加载的方式：
在viewDidLoad内请求到对应数据后,创建N个VC,加入到listVCArray,然后在initListForIndex内返回。listVC的网络请求，放到`beginFirstRefresh`方法里面，里面在用一个布尔值属性`isFirstRefreshed`记录是否请求过。保证多次调用只会请求一次。然后在`initListAtIndex`方法调用`beginFirstRefresh`方法。达到网络请求延迟加载。

### 懒加载的方式

主页面请求到了数据之后，在`initListAtIndex`方法里面把列表需要的数据传递进去，然后在列表VC里面，在`viewDidLoad`方法里面用传进来的数据进行该页面的网络请求。也达到了网络的延迟请求。
