### ISSUE TITLE
使用代码选中指定index，没有执行 listDidAppear、listDidDisappear，怎么回事？

### ISSUE THREAD

**Issue by li-qingnan** [pujiaxin33/JXCategoryView#253]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
使用代码选中指定index，没有执行 listDidAppear、listDidDisappear，怎么回事？

**版本号**
1.JXCategoryView版本号：1.3.0
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
建议你用最新的demo在尝试一下，自测没有问题。如果还有问题，建议你加入qq群反馈，并把出现问题的demo发给我。

**Comment by inoryshu** [comment]
我也遇到了，最近更新到最新版1.5.2，真的是出现各种莫名其妙的BUG

**Comment by pujiaxin33** [comment]
@inoryshu 建议你更新到1.5.3版本再试试，如果还有问题，麻烦告诉一下具体的操作环境和步骤
