### ISSUE TITLE
使用懒加载,defaultSelectedIndex对应的容器控制器会重复创建两次

### ISSUE THREAD

**Issue by LockLight** [pujiaxin33/JXCategoryView#254]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：1.5.2
2.手机系统版本号：iOS13.3
3.手机型号:iPhoneX

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：initListForIndex内创建容器控制器,设置defaultSelectedIndex = X, X对应的index会创建两次

**截图、GIF**
提供bug出现时的截图或者GIF。
![Uploading image.png…]()

**Comment by LockLight** [comment]
![image](https://user-images.githubusercontent.com/8235832/71540280-5a42c000-2983-11ea-8e02-f12b8e53634b.png)   
defaultSelectedIndex = 1  ,RaceEventViewController会创建两次

**Comment by pujiaxin33** [comment]
我用1.5.2的demo设置defaultSelectedIndex=1没有出现重复创建的问题，你用demo尝试一下呢？或者贴一下详细的使用代码。
