### ISSUE TITLE
数据源复用问题

### ISSUE THREAD

**Issue by xiaolongchang** [pujiaxin33/JXCategoryView#255]
**bug描述**
数据源复用问题。

**版本号**
1.JXCategoryView版本号：1.5.0
2.手机系统版本号：iOS11+

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryListContainerView 
2.具体的操作步骤是：
JXCategoryListContainerView 在包裹自定义的VC后 
2.1> 如果自定义的vc数据源数量不等，比如index=0时是一个元素 index =2 时是多个元素 需要向上翻页才能解决；
2.2>问题来了：在多元素页面不滑动后左右切签到元素少的页面后重新返回多元素页面向上滑动，发现数据变少了；等同于最后一个元素少的页面元素个数；
2.3>目前只能每次进入页面都网络请求才能解决该问题；

**Comment by pujiaxin33** [comment]
建议你自己在梳理一下代码，JXCategoryListContainerView不会对列表做内容上的处理。更不会错误复用。

如果梳理之后还有问题，建议你发送一个能复现问题的demo，以便我根据真实情况分析问题。
