### ISSUE TITLE
JXCategoryListContentViewDelegate代理实现方法最好添加个Class Prefix

### ISSUE THREAD

**Issue by NSObject-RC** [pujiaxin33/JXCategoryView#258]
在JXCategoryListContentViewDelegate这个代理方法- (UIView *)listView，可以添加个前缀吗？例如- (UIView *)jx_listView；以区别使用者自己的方法，而且便于阅读和维护。

**Comment by pujiaxin33** [comment]
考虑到新老版本兼容问题，无法进行方法名修改。建议你把自己内部使用的`listView`更改为其他名字。
