### ISSUE TITLE
使用示例的两个属性值变更一下

### ISSUE THREAD

**Issue by Bryant24s** [pujiaxin33/JXCategoryView#259]
![9194733E-F79F-4405-B68A-4632F07FE253](https://user-images.githubusercontent.com/14868600/72401671-9fd6f980-3787-11ea-8b91-b92d7298dfdf.png)

你示例中的两个属性可能是早期的，后来改动了。 希望改一下，虽然不是什么bug，哈哈~
 lineView.indicatorColor = [UIColor redColor];
 lineView.indicatorWidth = JXCategoryViewAutomaticDimension;

**Comment by pujiaxin33** [comment]
十分感谢，已更正
