### ISSUE TITLE
JXCategoryDotView不能更新红点的显示或隐藏吗

### ISSUE THREAD

**Issue by hzcly98** [pujiaxin33/JXCategoryView#262]
JXCategoryDotView 似乎只有在初始化的时候设置dotStates属性来控制红点的显示或隐藏，当数据请求回来后再去设置dotStates好像不起作用了，看了下源码确实没有更新红点显示或隐藏的逻辑？请问我该怎么做？谢谢！

**Comment by pujiaxin33** [comment]
你看一下示例呢，点击红点会消失的逻辑，你看一下呢？

**Comment by hzcly98** [comment]
> 你看一下示例呢，点击红点会消失的逻辑，你看一下呢？

好的，问题已解决，谢谢！另外问一下红点现在支持设置borderWidth和borderColor吗？

**Comment by pujiaxin33** [comment]
自己fork修改吧

**Comment by hzcly98** [comment]
OK
