### ISSUE TITLE
指示器添加红点

### ISSUE THREAD

**Issue by peterios2016** [pujiaxin33/JXCategoryView#263]
**Feature描述**
能否提供api给指示器添加红点和数字，或者直接传自己自定义的view

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
指示器的UI定制，请自定义实现。参考相关类源码实现。
