### ISSUE TITLE
类似京东商城首页

### ISSUE THREAD

**Issue by huangping35** [pujiaxin33/JXCategoryView#265]
大佬，类似京东商城首页，如果JXCategoryTitleView第一个选项是首页，整个JXCategoryTitleView都可以向上滚动，如果选择其他选项，整个JXCategoryTitleView就固定在顶部，这个要怎么实现或者调用项目中写好的哪个委托实现，第二，JXCategoryTitleView能不能提供一个类似- (UIView *)viewForPinSectionHeaderInPagerView:(JXPagerView *)pagerView，能自定义悬浮的titleview。

**Comment by pujiaxin33** [comment]
这个效果，只有自己根据列表的滚动，来控制每个控件frame的固定或移动。JXCategoryTitleView内部无法支持。
