### ISSUE TITLE
向上滑动的时候标题栏可以隐藏吗

### ISSUE THREAD

**Issue by niuxiao** [pujiaxin33/JXCategoryView#266]
向上滑动内容的时候标题栏可以隐藏吗

**Comment by pujiaxin33** [comment]
有具体效果参考吗？

**Comment by niuxiao** [comment]
就是界面往上滑动，CategoryTitleView隐藏，往下滑动CategoryTitleView再显示出来

**Comment by tanbinzone** [comment]
就是CategoryTitleView跟着界面上下滚动，不是悬停

**Comment by onceMu** [comment]
categoryTitleView 可以悬停一部分内容吗？ 类似网易云音乐电台主播个人页面滑动效果。
[RPReplay_Final1585664397.MP4.zip](https://github.com/pujiaxin33/JXCategoryView/files/4418590/RPReplay_Final1585664397.MP4.zip)

**Comment by pujiaxin33** [comment]
@niuxiao 没有现成的app可以体验你说得效果？

**Comment by pujiaxin33** [comment]
@onceMu  你说得效果建议参考一下这个库[JXPagingView](https://github.com/pujiaxin33/JXPagingView)

**Comment by pujiaxin33** [comment]
@tanbinzone 没有现成的app可以体验你说得效果？

**Comment by niuxiao** [comment]
类似京东首页，最上面一行TitleView可以悬停也可以跟随界面往上隐藏，第二行的TitleView就悬停

**Comment by pujiaxin33** [comment]
> 类似京东首页，最上面一行TitleView可以悬停也可以跟随界面往上隐藏，第二行的TitleView就悬停

这个效果需要自己处理

**Comment by pujiaxin33** [comment]
最新的demo添加了一个[ScrollUp示例]。
你可以参考一下。
