### ISSUE TITLE
JXCategoryListContainerView能不能设置成当滚动视图完成减速了再加载VC？

### ISSUE THREAD

**Issue by YoHoFee** [pujiaxin33/JXCategoryView#267]
当我有多个标签时，我左右滑动列表控制器，会很卡，因为我还没停止滑动，经过的控制器都会进行加载，很影响性能，所以我们的需求是当滑动完全停下的时候才加载，就是在scrollViewDidEndDecelerating:scrollView时才进行控制器加载，请问要怎么设置？

**Comment by pujiaxin33** [comment]
目前无法通过简单的配置达到你想要的效果，建议你自己fork仓库，修改源码以实现你的需求。

**Comment by JimmyCJJ** [comment]
同需求，首次切换过程中要走一次viewdiwload，会卡主线程
