### ISSUE TITLE
点击切换界面的bug

### ISSUE THREAD

**Issue by tanbinzone** [pujiaxin33/JXCategoryView#269]
**bug描述**
通过点击CategoryView切换时，调试发现JXCategoryListContainerView的scrollView的contentoffset有问题，导致界面偏移到屏幕外面
滑动切换没有问题，在iPhone11 iOS13.3版本无异常

**版本号**
1.JXCategoryView版本号：1.5.3
2.手机系统版本号：12.4.1
3.手机型号：iphone6

**截图、GIF**
![WechatIMG1228](https://user-images.githubusercontent.com/12681460/77607153-68898380-6f54-11ea-8343-e0274f0b9da0.png)

**Comment by qingshanbugai** [comment]
同学，搞定了吗，我遇到了同样的问题 ！

**Comment by tanbinzone** [comment]
> 同学，搞定了吗，我遇到了同样的问题 ！

切换的时候自己手动修改contentsize导致的
