### ISSUE TITLE
一个collectionView容易出现的tableviewcell 都呈现选中状态的问题

### ISSUE THREAD

**Issue by FunnyFzl** [pujiaxin33/JXCategoryView#270]
使用的是最新版本的JXCategoryView
1、collectionView类型的JXCategoryListContainerView
2、容器内装两个viewcontroller，viewcontroller内都是可下拉刷新的tableview  （下拉刷新用的MJRefresh）进入立即刷新状态beginRefreshing
3、在数据还未刷新出来的时候，一直点击tableview，数据一出现，所有的tableviewcell 就都被选中状态了，这是什么原因呢？
<img width="414" alt="截屏2020-03-27下午10 50 31" src="https://user-images.githubusercontent.com/15104149/77768538-928a9500-707d-11ea-8bfd-4797a278b8b5.png">

**Comment by pujiaxin33** [comment]
你把列表不放入JXCategoryListContainerView，放到你的普通页面，进行同样的下拉刷新，一直点击tableView看看是否有同样的问题。

这个建议相当于做实验，尝试寻找问题点。因为我觉得这个问题，跟JXCategoryView库的关系不大。

**Comment by vargeek** [comment]
@FunnyFzl 似乎是MJRefresh的这次commit[(c086852)](https://github.com/CoderMJLee/MJRefresh/commit/c0868527914d25da123e97aa0a8bc5c0e947819b)导致的，我把MJRefresh改成这个版本[(4488bf1)](https://github.com/CoderMJLee/MJRefresh/commit/4488bf1093c327116ccf90815030e9fae8a860bb)后没再复现了。或者把`JXCategoryListContainerView`的`containerType`改为`JXPagerListContainerType_ScrollView`。
