### ISSUE TITLE
PagingViewController 设置 defaultSelectedIndex 后，底部的生命周期有问题

### ISSUE THREAD

**Issue by Natai** [pujiaxin33/JXCategoryView#271]
**bug描述**
在demo中，特殊效果->个人中心，设置 segmentedView.defaultSelectedIndex = 1 后，
"能力"页面也会被创建，并触发 listDidAppear 等方法

**版本号**
1.JXCategoryView版本号：1.0.5

抱歉，这是 JXSegmentedView 中的问题，给提到OC版本来了。。。

**Comment by pujiaxin33** [comment]
感谢返回，是JXSegmentedView example里面JXPagingView的版本太老了，升级到最新版本就没有你说的问题了。
