### ISSUE TITLE
数据过少, 设置cellWidth后, 国际化文字英文文字过多超出, 能否有adjustsFontSizeToFitWidth属性

### ISSUE THREAD

**Issue by xiaoyao20084321** [pujiaxin33/JXCategoryView#272]
请问, 有没有adjustsFontSizeToFitWidth这个属性可以设置文字自动大小

**Comment by pujiaxin33** [comment]
目前无法支持adjustsFontSizeToFitWidth，建议你根据不同语言的文本，计算文本长度，加宽cellWidth或者将titleFont设置小一点。
