### ISSUE TITLE
LoadDataListCollectionListViewController中UIActivityIndicatorView重新开启动画有问题

### ISSUE THREAD

**Issue by wyk190576528** [pujiaxin33/JXCategoryView#273]
左右滑动切换tab的情况，UIActivityIndicatorView重新启动动画成功；
但点击切换tab的情况，UIActivityIndicatorView重新启动动画失败。

**Comment by pujiaxin33** [comment]
建议你将JXCategoryListContainerView的containerType设置为JXCategoryListContainerType_ScrollView，来规避JXCategoryListContainerType_CollectionView触发cell重用导致UIActivityIndicatorView失效的问题。
