### ISSUE TITLE
调用 reloadData 会导致 list 调用两次 viewWillAppear

### ISSUE THREAD

**Issue by fabcz** [pujiaxin33/JXCategoryView#275]
1、在 Example 的 TitleViewController 26 行往下加一句 [self.myCategoryView reloadData]; 
2、重写 ListViewController 的 viewWillAppear 进行打印
3、点击 demo 指示器样式下的某个列表即可复现
业务需要得手动调用 reloadData

**Comment by pujiaxin33** [comment]
初始化的时候，一般也就是在viewDidLoad方法里面无需自己调用`[self.myCategoryView reloadData];`。因为第一次会自己调用。你业务手动调用reloadData，一般是在初始化之后才会调用的。
