### ISSUE TITLE
能否支持竖直的展示方式

### ISSUE THREAD

**Issue by peterios2016** [pujiaxin33/JXCategoryView#276]
**Feature描述**
请简单描述你想要的效果：
现在有一些app已经把横向的CategoryView改为竖直的了，希望作者也能提供类似的功能

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：
标题可以支持竖直展示

**Comment by pujiaxin33** [comment]
能否介绍一个现有的app，具体页面，体验一下具体效果

**Comment by peterios2016** [comment]
> 能否介绍一个现有的app，具体页面，体验一下具体效果

加了你QQ，没回，能否留个联系方式呢

**Comment by pujiaxin33** [comment]
你直接说就行了

**Comment by TeacherXue** [comment]
> 你直接说就行了

他说的应该是类似京东的分类也页面的那种左右结构的

**Comment by pujiaxin33** [comment]
@TeacherXue 我看了一下京东的分类页面，垂直方式根本用不上JXCategoryView库。自己写一个UITableView，再处理didSelectItem方法，更新右边的内容。这很容易实现的。建议自己实践一下哈。
