### ISSUE TITLE
无法单向滑动

### ISSUE THREAD

**Issue by ffzzqq1128** [pujiaxin33/JXCategoryView#277]
![IMG_0035](https://user-images.githubusercontent.com/19404612/79199373-7d787900-7e67-11ea-86dd-9d8fe76c72cf.GIF)

**bug描述**
请简单描述你的bug现象。

子类是滑动的类是UITableView的时候，会出现向下滑动的同时也可以左右滑动，我很认真看过你的刷新类数据，看了差不多一天都没有发现有什么不同，但是另一个页面子类是UICollectionView的时候手势又是正常的了，现在我非常费解不知道是什么情况

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by ffzzqq1128** [comment]
![image](https://user-images.githubusercontent.com/19404612/79200650-57ec6f00-7e69-11ea-84d6-ccc2152dccea.png)
我把你写好的文件拖到我的工程里还是出现一样的问题，之针对UITableView 

pod 'MJRefresh'
pod 'MJExtension'
pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'SDCycleScrollView','>= 1.80'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
pod 'YYKit', '~> 1.0.9',:inhibit_warnings => true
pod 'pop'
pod 'YTKNetwork'
# HUD
pod 'MBProgressHUD'
# 键盘自适应
pod 'IQKeyboardManager'
# iOS8 and later
pod 'TZImagePickerController'
# 搜索
pod 'PYSearch'
# tab bar
pod 'CYLTabBarController', '~> 1.24.0'
# 导航栏
pod 'GKNavigationBarViewController'
# 滚动视图
pod 'GKPageScrollView'
# 腾讯云播放器-独立播放器
pod 'TXLiteAVSDK_Player'
# ZFPlayer
pod 'ZFPlayer', '~> 3.0'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
#pod 'ZFPlayer/ijkplayer', '~> 3.0'
pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0'
# page分类
pod 'JXCategoryView'
pod 'JXPagingView/Pager'
# webP
#pod 'libwebp'
# pickerView
pod 'BRPickerView', '~> 2.2.1'
#日历
pod 'FSCalendar'
pod 'SAMKeychain', '1.5.2'
#内存泄露检查
pod 'MLeaksFinder'
#空数据视图
pod 'DZNEmptyDataSet'

这是我所有导入的库，不知道哪里有冲突了，你的手势无法正常出现

**Comment by ffzzqq1128** [comment]
我定位不到单向选择的手势在哪？定位到哪里调试才行？麻烦告知一下- -!

**Comment by pujiaxin33** [comment]
这种问题，一般只能你弄一个复现的demo给我，我来排查问题。
就之前的多次的经验，有些事引入的三方库hook，代码设置问题，也有发现是JXCategoryView的库。
所以，基于复杂的问题，麻烦你提供一个复现问题的demo给我。

**Comment by ffzzqq1128** [comment]
不过我如果使用JXPageView 就是'JXPagingView/Pager' 相关的就不会出问题，现在感觉很迷

**Comment by pujiaxin33** [comment]
可能是版本问题

**Comment by MyNameZhangXinMiao** [comment]
DZNEmptyDataSet是这个库的原因，导致侧滑无法返回。
