### ISSUE TITLE
请问一下，并排加了四个tableView在scrollView上，不能左右滑动怎么解决

### ISSUE THREAD

**Issue by ldy694** [pujiaxin33/JXCategoryView#28]
可以点选切换，没有加tableView时也是可以左右滑动的，是手势被占用了吗？有解决方案吗？
谢谢

**Comment by pujiaxin33** [comment]
建议参考demo一步一步来，可能是contentSize没有设置正确。你可以自己认真排查一下

**Comment by pujiaxin33** [comment]
如果还有问题，建议你加入QQ群：112440151   进行问题交流
