### ISSUE TITLE
使用自定义效果中秒杀时间和特殊效果中个人主页这两者结合使用在 iOS13 一下出现的问题

### ISSUE THREAD

**Issue by TLQBlueWind** [pujiaxin33/JXCategoryView#281]
**bug描述**
使用自定义效果中秒杀时间和特殊效果中个人主页这两者结合使用，在实现活动到某一个位置去改变self.categoryView这个样式的时候在 iOS13 一下会出现，自动滑到顶部的问题

**版本号**
1.JXCategoryView版本号：'~>1.5.3'
2.手机系统版本号：iOS13 一下
3.手机型号：所有 iOS13 一下的手机

**Comment by pujiaxin33** [comment]
麻烦能再详细一点描述你的问题吗？比如关键步骤和代码。

**Comment by weizhangCoder** [comment]
这个应该和我遇到的问题是一样的，iOS 13 一下，会出现，而且是当你的偏移量大于pinSectionHeaderVerticalOffset这个值的时候，在实现活动到某一个位置的时候然后你调用了[self.pagerView reloadData];然后就走了这个方法。这是我猜测的。2.0.6版本以前
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/11644326/87657252-28f9d800-c78d-11ea-824b-355a24069717.png">

**Comment by pujiaxin33** [comment]
> 这个应该和我遇到的问题是一样的，iOS 13 以下，会出现往上偏移一段距离，这段距离刚好是pinSectionHeaderVerticalOffset的值，而且是必须是当你的偏移量大于pinSectionHeaderVerticalOffset这个值的时候，在实现活动到某一个位置的时候然后你调用了[self.pagerView reloadData];然后就走了这个方法。这是我猜测的。2.0.6版本以前
> <img alt="image" width="1162" src="https://user-images.githubusercontent.com/11644326/87657252-28f9d800-c78d-11ea-824b-355a24069717.png">

已修复
