### ISSUE TITLE
当设置JXCategoryTitleImageType_TopImage时，cpu暴涨

### ISSUE THREAD

**Issue by MeowEight** [pujiaxin33/JXCategoryView#282]
JXCategoryTitleImageCell里layoutSubviews循环调用。在demo上测试相同的代码没问题。使用left、right类型也没问题。找不到问题出在哪，求解。

**Comment by pujiaxin33** [comment]
我用demo加载本地图片没有问题，你是加载的网络图片吗？

把具体的配置代码贴一下呢？

**Comment by doraemontown** [comment]
> 我用demo加载本地图片没有问题，你是加载的网络图片吗？
> 
> 把具体的配置代码贴一下呢？

我用demo测试网络图片确实没问题，同样的代码，在我的项目里有问题。大概是什么冲突了。项目东西比较多，我先研究研究。一般什么会导致layoutSubviews死循环呢？你有没有什么建议

**Comment by pujiaxin33** [comment]
你自己打断点，截图看一下调用栈呢？

**Comment by pujiaxin33** [comment]
1.5.7已修复
