### ISSUE TITLE
初始化JXCategoryTitleView的contentsize不正确

### ISSUE THREAD

**Issue by haijunli68** [pujiaxin33/JXCategoryView#284]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：1.5.5
2.手机系统版本号：12.2
3.手机型号：iPhone6

**复现步骤**
1. 遇到问题的相关效果、类是：？
嵌套使用，iOS12.2，index为0的subVC的JXCategoryTitleView的contentsize少20，index为1的正常，
见截图。
iOS13无此问题。
2.具体的操作步骤是：？
` _myCategoryView.contentScrollViewClickTransitionAnimationEnabled = NO;
    _myCategoryView.cellSpacing = 46;
    _myCategoryView.contentEdgeInsetLeft = 24;
    _myCategoryView.contentEdgeInsetRight = 24;
    _myCategoryView.backgroundColor = rgba(255, 255, 255, 0.1);
    _myCategoryView.layer.cornerRadius = 16;
    _myCategoryView.layer.masksToBounds = YES;
    _myCategoryView.titleColor = [UIColor whiteColor];
    _myCategoryView.titleSelectedColor = [UIColor whiteColor];
    _myCategoryView.titleFont = [UIFont systemFontOfSize:14 weight:UIFontWeightMedium];
    _myCategoryView.titleSelectedFont = [UIFont systemFontOfSize:14 weight:UIFontWeightMedium];
    [self.view addSubview:self.myCategoryView];
    self.myCategoryView.delegate = self;
    self.myCategoryView.listContainer = self.listContainerView;
    
    JXCategoryIndicatorBackgroundView *backgroundView = [[JXCategoryIndicatorBackgroundView alloc] init];
    backgroundView.indicatorHeight = 32;
    backgroundView.indicatorWidthIncrement = 48;
    backgroundView.indicatorColor = rgba(255, 255, 255, 0.1);
    self.myCategoryView.indicators = @[backgroundView];
    `
**截图、GIF**
![image](https://user-images.githubusercontent.com/13010224/80583437-c53ff880-8a42-11ea-81cc-b4bba5c18920.png)

![image](https://user-images.githubusercontent.com/13010224/80583379-b48f8280-8a42-11ea-8b40-e43d6cca497d.png)

**Comment by haijunli68** [comment]
_myCategoryView.cellSpacing = 0;
    _myCategoryView.cellWidth = totalItemWidth/self.titles.count;
这种方式可以解决。

**Comment by pujiaxin33** [comment]
可以给我一个复现问题的demo吗？
不然你就用你现在的方案，能解决也可以。
