### ISSUE TITLE
急！从widget进入APP数据不显示

### ISSUE THREAD

**Issue by hey1207** [pujiaxin33/JXCategoryView#285]
杀死APP，从widget进入默认屏没有数据，不杀死APP没有问题，数据都是提前缓存的没有网络请求！

**Comment by pujiaxin33** [comment]
你在viewwillappear里面调用一下categoryView.reloadData方法试试呢

**Comment by pujiaxin33** [comment]
或者你自己找一个地方调用reloadData方法

**Comment by hey1207** [comment]
我在VIewDIdAppear里调用生效了，但是执行到这中间会有白屏的问题


| |
heyIOS
|
|
hey_iosdeveloper@163.com
|
签名由网易邮箱大师定制


在2020年04月30日 17:10，暴走的鑫鑫<notifications@github.com> 写道：

或者你自己找一个地方调用reloadData方法

**Comment by pujiaxin33** [comment]
viewwillapear，viewdidload，都试试呢？

**Comment by hey1207** [comment]
我在viewwillapear，viewdidload都试了不起作用，在viewDidAppear里面试了才起作用，如果应用不退出的话直接在懒加载JXCategoryVIew的时候刷新就有数据，就是退出应用才有的问题


| |
heyIOS
|
|
hey_iosdeveloper@163.com
|


在2020年04月30日 17:53，暴走的鑫鑫<notifications@github.com> 写道：

viewwillapear，viewdidload，都试试呢？

**Comment by pujiaxin33** [comment]
能提供一个复现问题的demo吗？

**Comment by hey1207** [comment]
- (void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    [self.categoryView reloadData];
}
-(JXCategoryTitleView *)categoryView{
    if (!_categoryView) {
        NSMutableArray *tempArr = [NSMutableArray array];
        for (NSInteger i = 0; i<24; i++) {
            [tempArr addObject:StrOfInterger(i)];
        }
        _categoryView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(0, self.navBar.bottom, ScreenWidth, 0)];
        _categoryView.titles = tempArr;
        _categoryView.defaultSelectedIndex = 1;
        
        _categoryView.delegate = self;
        [self.view addSubview:_categoryView];
        //
        _categoryView.listContainer = self.listContainerView;
        [_categoryView reloadData];
    }
    return _categoryView;
}
-(JXCategoryListContainerView *)listContainerView{
    if (!_listContainerView) {
        _listContainerView = [[JXCategoryListContainerView alloc] initWithType:JXCategoryListContainerType_ScrollView delegate:self];
        [self.view addSubview:_listContainerView];
        _listContainerView.frame = CGRectMake(0, self.categoryView.bottom, ScreenWidth, ScreenHeight - self.navBar.bottom-MainTabBar_Height);
    }
    return _listContainerView;
}
//返回列表的数量
- (NSInteger)numberOfListsInlistContainerView:(JXCategoryListContainerView *)listContainerView {
    return MaxWeekCount;
}
//根据下标index返回对应遵从`JXCategoryListContentViewDelegate`协议的列表实例
- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index {
    MyCoursePageViewController *vc= [[MyCoursePageViewController alloc] init];
    vc.selectIndex = index+1;
    return vc;
}

**Comment by hey1207** [comment]
大神能给看一下问题吗

**Comment by pujiaxin33** [comment]
能提供一个复现问题的demo吗？
