### ISSUE TITLE
不使用JXCategoryTitleView的情况下，第一个itemVc可以展示，后面的itemVc不会被创建

### ISSUE THREAD

**Issue by zhangxiongwen** [pujiaxin33/JXCategoryView#286]
使用JXCategoryListContainerView创建一个容器来展示一些itemVc，如果创建JXCategoryTitleView设置了self.titleView.listContainer = self.listContainerView(关联cotentScrollView)是没有问题的，如果我仅仅只想使用JXCategoryListContainerView创建一个容器来展示一些itemVc，不使用JXCategoryTitleView（没有关联）的情况下，第一个itemVc可以展示，后面的itemVc不会被创建

**Comment by pujiaxin33** [comment]
`JXCategoryListContainerView`算是跟`JXCategoryTitleView`强藕合的类，不建议单独使用。
它需要调用下面两个方法驱动列表的加载：
```Objective-C
- (void)scrollingFromLeftIndex:(NSInteger)leftIndex toRightIndex:(NSInteger)rightIndex ratio:(CGFloat)ratio selectedIndex:(NSInteger)selectedIndex;
- (void)didClickSelectedItemAtIndex:(NSInteger)index;
```

**Comment by zhangxiongwen** [comment]
好吧，谢谢！
