### ISSUE TITLE
提供无障碍支持

### ISSUE THREAD

**Issue by jiasongs** [pujiaxin33/JXCategoryView#287]
**Feature描述**
能否提供一个设置无障碍的接口，目前的做法通过继承的方式实现的。

**参考效果**
无

**其他补充**
无

**Comment by pujiaxin33** [comment]
没做过无障碍，能贴下你的子类核心代码么？

**Comment by jiasongs** [comment]
<img width="963" alt="图片" src="https://user-images.githubusercontent.com/22904757/82390562-a2b56400-9a71-11ea-9e3b-4b4e3d3b2926.png">
关键主要是这三点，这样JXCategoryTitleImageView就简单实现了无障碍

**Comment by pujiaxin33** [comment]
好的，最新代码已经支持voiceover了
