### ISSUE TITLE
titles和images动态形式加减

### ISSUE THREAD

**Issue by yuanxiangyang0528** [pujiaxin33/JXCategoryView#288]
项目使用的是 JXCategoryTitleImageView  和 JXPagerView，设计是category的数据源会在点击tableView的cell后增加 和 点击前置面包屑后递减。
实现效果：
增加时正常，良好
递减时，页面会从第0页滚动到当前页。
尝试将contentScrollViewClickTransitionAnimationEnabled设置为NO，但会发生增加 刷新后，页面不会滚到新页面的问题。

付刷新代码：
self.categoryView.imageNames = imageNames;
self.categoryView.imageTypes = imageTypes;
[self.pagerView reloadData];
[self.categoryView selectItemAtIndex:self.categoryView.titles.count - 1];

**Comment by pujiaxin33** [comment]
当titles发送数据源更新时，在调用reloadData之前设置defaultSelectedIndex可以指定默认显示的页面。你可以去JXPagingView库示例，查看相关示例。
