### ISSUE TITLE
重新刷新数据，数据只有一个标签的时候，列表加载不出来

### ISSUE THREAD

**Issue by QiuXiaochun** [pujiaxin33/JXCategoryView#289]
今天下午测试时发现只有一个标签的有问题。试了下demo，发现也有类似的问题。
使用 git clone + 地址拿的demo。

真机，模拟器均出现类似问题。开始多个标签，刷新为只有一个的时候，出现单个标签页下的VC空白情况。

**截图、GIF**
提供bug出现时的截图或者GIF。
![iShot2020-05-22下午04 39 58](https://user-images.githubusercontent.com/18690958/82649505-e4016b80-9c4b-11ea-9bc5-b4fe5fd1d197.png)

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复。
