### ISSUE TITLE
iPhone 6  iOS  12.0系统，从别的界面返回的收请求数据奔溃

### ISSUE THREAD

**Issue by weizhangCoder** [pujiaxin33/JXCategoryView#292]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
从当前界面A进入别的B界面，返回A后，每次都会请求数据，然后就会出现奔溃,目前只发现iphone 6 奔溃。

**版本号**
1.JXCategoryView版本号：1.5.3
2.手机系统版本号：12.0
3.手机型号：iPhone 6

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerView 第132 行
2.具体的操作步骤是：从当前界面A进入别的B界面，返回A后，每次都会请求数据，然后就会出现奔溃,目前只发现iphone 6 奔溃。

**截图、GIF**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/11644326/83862789-010e6200-a755-11ea-890a-c8f7264cd4fd.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/11644326/83862819-0a97ca00-a755-11ea-9f66-37433ccd1bbf.png">

**Comment by pujiaxin33** [comment]
JXPagerView的版本号呢？

**Comment by weizhangCoder** [comment]
JXCategoryView 1.5.3 版本'JXPagingView/Pager','2.0.3' ，但是iPhone X 以上的又不奔溃，很困惑，

**Comment by weizhangCoder** [comment]
然后升级JXCategoryView 1.5.5 版本'JXPagingView/Pager','2.0.6'  之后，上述描述的bug 消失了，感谢大佬。上线之前本来不敢升最新版本。

**Comment by weizhangCoder** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/11644326/83867261-bb08cc80-a75b-11ea-893e-dd7454528211.png">

**Comment by pujiaxin33** [comment]
恩，之前解决过类似的问题，那就关闭issue了。
