### ISSUE TITLE
退到后台任务管理器页面的刷新问题

### ISSUE THREAD

**Issue by 1506874981** [pujiaxin33/JXCategoryView#293]
当我退到后台任务管理器时，我再次进入时会自动走reload 方法 这是为什么呢

**Comment by pujiaxin33** [comment]
你在reload方法打个断点看看呢？

**Comment by 1506874981** [comment]
> 你在reload方法打个断点看看呢？
我找到问题了 必须要配合titleview使用导致我出现这个问题

**Comment by sensencoder** [comment]
我也遇到了，titleView？是哪个，按照demo做的还是会出现

**Comment by 1506874981** [comment]
你要配合着他的分类标题一起使用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pujiaxin33/JXCategoryView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 下午3:16
收件人:&nbsp;"pujiaxin33/JXCategoryView"<JXCategoryView@noreply.github.com&gt;;
抄送:&nbsp;"蒋标"<543150806@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [pujiaxin33/JXCategoryView] 退到后台任务管理器页面的刷新问题 (#293)





 
我也遇到了，titleView？是哪个，按照demo做的还是会出现
