### ISSUE TITLE
怎么我自定义导航栏之后,使用这个分页,滑动的时候会改变导航栏的样式,但是点击分类卡片又不会改变

### ISSUE THREAD

**Issue by MyRuBI** [pujiaxin33/JXCategoryView#295]
![111](https://user-images.githubusercontent.com/15376688/84102373-d9641600-aa42-11ea-9674-83943919bd5c.gif)

**Comment by pujiaxin33** [comment]
从你的描述无法得知具体原因，你可以检查一下代码，查看是否是其他地方错误修改了导航栏样式
