### ISSUE TITLE
JXCategoryTitleView 搭配 JXCategoryListContainerView使用 侧滑返回不了

### ISSUE THREAD

**Issue by SilenceWater** [pujiaxin33/JXCategoryView#297]
**Feature描述**
请简单描述你想要的效果：？
JXCategoryTitleView 搭配 JXCategoryListContainerView使用 在第一页的时候可以侧滑返回
**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
请参考demo示例代码，你检查一下代码`self.navigationController.interactivePopGestureRecognizer.enabled`是否被错误设置为NO.

**Comment by sauchye** [comment]
@pujiaxin33 
 弱弱的问下，JXCategoryTitleView 的titleLabel 可以左对齐吗，如不居中对齐，如：categoryView.titles = @[@"1", @"2"]
不均分，距离屏幕左右20
![image](https://user-images.githubusercontent.com/4171847/86922874-d3577700-c15f-11ea-95f8-6819e0ef1ced.png)

**Comment by youyoukong** [comment]
我也碰到这个问题, 确认self.navigationController.interactivePopGestureRecognizer.enabled没有设置为NO.
只要不执行[self.view addSubview:self.listContainerView];就可以侧滑.

**Comment by xiaoyao20084321** [comment]
> 我也碰到这个问题, 确认self.navigationController.interactivePopGestureRecognizer.enabled没有设置为NO.
> JXCategoryTitleView区域可以侧滑返回.JXCategoryListContainerView区域不可侧滑返回.
> 只要不执行[self.view addSubview:self.listContainerView];就可以侧滑.

我也遇见了。。你怎么解决的啊

**Comment by youyoukong** [comment]
> > 我也碰到这个问题, 确认self.navigationController.interactivePopGestureRecognizer.enabled没有设置为NO.
> > JXCategoryTitleView区域可以侧滑返回.JXCategoryListContainerView区域不可侧滑返回.
> > 只要不执行[self.view addSubview:self.listContainerView];就可以侧滑.
> 
> 我也遇见了。。你怎么解决的啊
viewController集成了TZScrollViewPopGesture这个扩展.

**Comment by pujiaxin33** [comment]
麻烦在demo上面复现一下，再发给我:317437084@qq.com

**Comment by xiaoyao20084321** [comment]
> 麻烦在demo上面复现一下，再发给我:[317437084@qq.com](mailto:317437084@qq.com)
谢谢，我解决了，少写了一个delegate

**Comment by youyoukong** [comment]
> 麻烦在demo上面复现一下，再发给我:[317437084@qq.com](mailto:317437084@qq.com)

已发,请查收.

**Comment by pujiaxin33** [comment]
@youyoukong 查看你的demo之后，只需要把 "UINavigationController+TZPopGesture.h” 类移除就没有问题了。证明就是这个类swizzle做了一个修改导致了问题。我暂时没有时间看里面代码具体是什么原因，因为不是categoryView直接导致的，所以需要你自己去排查了。

**Comment by youyoukong** [comment]
> @youyoukong 查看你的demo之后，只需要把 "UINavigationController+TZPopGesture.h” 类移除就没有问题了。证明就是这个类swizzle做了一个修改导致了问题。我暂时没有时间看里面代码具体是什么原因，因为不是categoryView直接导致的，所以需要你自己去排查了。


我这边发现的现象是. 自定义了backBarItem后,就出现这个问题.业务上手势代理不能直接返回YES.
后面为了解决问题才引入了UINavigationController+TZPopGesture.对业务也没有影响.
我这边demo运行上删除这个扩展就无法侧滑返回了.Demo里也是把对它的引用方法注释掉的. 取消注释后才能侧滑返回.

**Comment by pujiaxin33** [comment]
@youyoukong 你用示例的`BaseNaviViewController`类解决这个问题。

```
@implementation BaseNavigationViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    self.interactivePopGestureRecognizer.delegate = self;
    self.interactivePopGestureRecognizer.enabled = YES;
}

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
}

- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer {
    if (self.viewControllers.count == 1) {
        return NO;
    }
    return YES;
}

@end
```
这里的代码会解决这个问题
