### ISSUE TITLE
会不会影响自控制器的生命周期

### ISSUE THREAD

**Issue by Liyongcong** [pujiaxin33/JXCategoryView#3]

**Comment by Liyongcong** [comment]
可以在导航栏上添加多个左右滚动的视图么

**Comment by pujiaxin33** [comment]
当然可以，但是导航栏那么小的地方，你确定放得下吗？

**Comment by Liyongcong** [comment]
肯定是跟你另外的一样，是运行左右滑动的，导航栏上面的个数也不一定

**Comment by Liyongcong** [comment]
肯定是跟你其他情况一样的，允许左右滚动的，导航栏上面显示的个数不一定，因为我们现在的项目就有这样的需求

**Comment by pujiaxin33** [comment]
个数是跟着数据源titles走的，你可以先尝试一下，如果具体需求不能实现，可以把细节发给我，我看看有没有办法实现

**Comment by Liyongcong** [comment]
不知道怎么上传图片。。。。
Duplicate of #1

**Comment by pujiaxin33** [comment]
后续准备加入嵌套使用demo
