### ISSUE TITLE
JXCategoryTitleVerticalZoomView 在阿拉伯语RTL适配问题

### ISSUE THREAD

**Issue by linjie321** [pujiaxin33/JXCategoryView#301]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
JXCategoryTitleVerticalZoomView 在适配阿拉伯系统语言时, 设置collectionView.semanticContentAttribute = .forceRightToLeft 不起效果, iOS 10.3 系统无法重写flipsHorizontallyInOppositeLayoutDirection, 所以希望作者能兼容下这个效果, 不然我只能直接修改原代码, 用transform了, 无法使用pod

**版本号**
1.JXCategoryView版本号：1.5.5
2.手机系统版本号：iOS 10.3.3
3.手机型号：iPhone5

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryTitleVerticalZoomView
2.具体的操作步骤是: 将 JXCategoryTitleVerticalZoomView 的 collectionView.semanticContentAttribute = .forceRightToLeft , 点击 title之后, cell的位置又偏向左边, 无法重写flipsHorizontallyInOppositeLayoutDirection效果

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
我在最新demo里面支持了RTL，你下载下来试一试呢？没有问题再发包

**Comment by pujiaxin33** [comment]
你再用最新的1.5.7试一试呢

**Comment by captain-black** [comment]
indicator似乎没适配
