### ISSUE TITLE
在每个子控制器的同一位置显示一个按钮（怎么样直接在父控制器添加UIView并且显示到每个子控制器）

### ISSUE THREAD

**Issue by Ssiswent** [pujiaxin33/JXCategoryView#302]
**Feature描述**
请简单描述你想要的效果：
在每个子控制器的同一位置显示一个按钮（怎么样直接在父控制器添加UIView并且显示到每个子控制器）

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：百度贴吧
2.目标页面路径：进吧
3.目标效果截图：
![image](https://user-images.githubusercontent.com/37449310/84975891-289ffa00-b159-11ea-8787-3aec7c963d26.png)

**其他补充**
关于目标效果的其他说明：
如果在每个子控制器分别添加UIView，切换页面时效果不是很好。

**Comment by pujiaxin33** [comment]
你把右下角的+号按钮添加到UIViewController.view上面试试呢，视图层级确保在最上层即可。

**Comment by Ssiswent** [comment]
搞定了，非常感谢！！！
