### ISSUE TITLE
有个建议，这个问题也不算缺陷吧，就是DEMO里面用到了JXPagerView,但是DEMO里的JXPagerView版本号太旧了

### ISSUE THREAD

**Issue by yaochangliang159** [pujiaxin33/JXCategoryView#304]
**bug描述**
DEMO里面用到了JXPagerView,但是DEMO里面的JXPagerView的版本是1.1.19的，在我的项目引入了最新的2.0.3的JXPagerView以后，由于JXPagerView版本不一样，里面方法发生了变动，导致我在复制本DEMO代码的时候，相当于JXPagerView这部分代码是旧的，就复制到我的新项目了，但是我的项目里面的JXPagerView是新版本的，就出现了initListAtIndex方法只调用了一次。于是我仔细检查了一下代码，做了如下改动，就好了：
将 self.categoryView.contentScrollView = self.pagingView.listContainerView.collectionView;
替换为
 self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagingView.listContainerView;
就好了，之前的那行代码是DEMO里的代码，第二行代码是你github上的教程。所以我的建议是，能不能把DEMO里的JXPagerView的库版本换成新一点的。这样能让别的人少遇到问题。

**版本号**
1.JXCategoryView版本号：1.5.5
2.手机系统版本号：13.5.1
3.手机型号：iphone 6s

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
谢谢反馈，JXPagerView已更新到2.0.6
