### ISSUE TITLE
分割线多个的时候，出现分割线宽度不等的问题

### ISSUE THREAD

**Issue by weizhangCoder** [pujiaxin33/JXCategoryView#308]
使用了cell样式，里面分割线demo的代码？然后发现 分割线宽度不均匀
<img width="266" alt="image" src="https://user-images.githubusercontent.com/11644326/87654529-9dcb1300-c789-11ea-930a-9eeaf9f85cc1.png">
然后就去试demo ,发现demo里面没有问题，并且运行在真机上也没有问题。然后百思不得解，发现主要是3倍像素下会出现这样的问题 iphone 11. 然后就调试设置这个的值
<img width="402" alt="image" src="https://user-images.githubusercontent.com/11644326/87654896-1df17880-c78a-11ea-9add-6a23d845f2ad.png">  调整这个值的或大或小，然后分割线也就时好时坏。

如果宽度是  1/[UIScreen mainScreen].scale  这个x的坐标是否应该减去((1 / [UIScreen mainScreen].scale) / 2) 来保持像素不虚，或者宽度相等。我这个只是真机偶现，当然你的demo 里面是好的。也不知道还有别人遇到没有。
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/11644326/87655174-7aed2e80-c78a-11ea-890b-1c62a6882dc0.png">

**Comment by pujiaxin33** [comment]
我自己在demo上测试，并未复现该问题。
