### ISSUE TITLE
请问能否开放动态修改标题颜色的api

### ISSUE THREAD

**Issue by iOSchuang** [pujiaxin33/JXCategoryView#309]
**Feature描述**
请简单描述你想要的效果：？
内容视图滚动时，会修改JXCategoryView的背景色，此时需要同时修改标题的颜色，请问能否实现

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？
![1](https://user-images.githubusercontent.com/15044460/87909173-5353da00-ca9a-11ea-896f-2b5051479fb8.png)
![2](https://user-images.githubusercontent.com/15044460/87909181-58188e00-ca9a-11ea-8bc9-dcbba01325d5.png)

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你想看一下已有的示例，有没有类似于你需求的。

**Comment by iOSchuang** [comment]
demo中的暂时似乎不能满足，需求效果同喜马拉雅app首页，切换时候，会根据banner效果，修改JXCategoryView的背景色以及标题的颜色

**Comment by pujiaxin33** [comment]
背景色有一个示例可以参考，就是切换背景图那个，你看一下，title颜色，等我下载喜马拉雅看看

**Comment by iOSchuang** [comment]
imageView底部那个，也是切换的整个背景，但是标题的颜色不能随之更换，normal状态下白色字体，假如切换一个背景接近于白色的图片，那么标题颜色与背景色接近，几乎不能看到标题。大神有空看一下喜马拉雅app,或者淘宝的天猫国际板块，都是这种设计.
<img width="513" alt="00" src="https://user-images.githubusercontent.com/15044460/87911479-4cc76180-ca9e-11ea-9629-355670f921d2.png">

**Comment by iOSchuang** [comment]
请问是否有时间处理这个效果，项目多出用到此框架，如果可以暴露api，麻烦告知一下多久可以处理好，如果没时间或者不方便暴露API的话，我再想想别的办法，因为在赶项目。谢谢，麻烦了

**Comment by iOSchuang** [comment]
打扰了，已解决

**Comment by Dannyzheng831** [comment]
> 

请问时怎么解决的呀
