### ISSUE TITLE
怎么更改选中的字体?

### ISSUE THREAD

**Issue by xclidongbo** [pujiaxin33/JXCategoryView#31]
怎么更改选中的字体? 需要把当前title改为粗体.

**Comment by pujiaxin33** [comment]
你好，版本1.0.9新增了titleSelectedFont字段，可以实现你的需求。

**Comment by 624990742** [comment]
你好，我默认titleFont与titleSelectedFont设置的是同一个字体，默认字体的是不加粗，选中的是加粗，结果选中的字体并没有加粗，这个是怎么回事呢？
