### ISSUE TITLE
选中后隐藏图片,但是label怎么居中啊

### ISSUE THREAD

**Issue by syqaxldy** [pujiaxin33/JXCategoryView#310]
![image](https://user-images.githubusercontent.com/13041822/88007274-3540b500-cb40-11ea-9d5b-193989db4365.png)

**Comment by syqaxldy** [comment]
![624C8FA9-59DD-4DC0-960D-F0C6A91F63DB](https://user-images.githubusercontent.com/13041822/88007366-6d47f800-cb40-11ea-8345-532405142a3b.png)

**Comment by syqaxldy** [comment]
![image](https://user-images.githubusercontent.com/13041822/88009206-8ce11f80-cb44-11ea-9ee6-03a316650e75.png)

**Comment by pujiaxin33** [comment]
请最新版本再试一试。
