### ISSUE TITLE
手势问题

### ISSUE THREAD

**Issue by cnzlh** [pujiaxin33/JXCategoryView#311]
作者你好，如果容器里有3个页面，在滑动到第3个页面的时候继续滑动，想push出一个新的页面，应该怎么做呢，望指教

**Comment by pujiaxin33** [comment]
请下载最新的demo，把JXCategoryListContainerView.bounces属性设置为YES，然后实现listContainerViewDidScroll代理方法。监听scrollView.contentOffset.x来处理你想要的逻辑。

**Comment by cnzlh** [comment]
收到，感谢
