### ISSUE TITLE
在iOS13.5.1系统上页面展示有毕现bug

### ISSUE THREAD

**Issue by wangjuniOS6** [pujiaxin33/JXCategoryView#312]
**版本号**
1.JXCategoryView版本号：1.5.5
2.手机系统版本号：13.5.1
3.手机型号：iphone7

**复现步骤**
1. 遇到问题的相关效果、类是：PagingViewController
2.具体的操作步骤是：运行Demo，进入特殊效果-个人主页-个人中心1）当前页面选中的是能力Tab
2）不滑动切换tab，直接点击选择队友tab后，再向左滑动切换到爱好Tab，此时页面会显示空白
此时- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index代理方法未执行
**截图、GIF**

![IMG_5989](https://user-images.githubusercontent.com/2890322/88454626-87b50500-cea3-11ea-9f35-d386492792f5.PNG)

**Comment by wangjuniOS6** [comment]
![IMG_5990](https://user-images.githubusercontent.com/2890322/88454713-f5613100-cea3-11ea-858b-3f76ce45e9f2.PNG)

**Comment by pujiaxin33** [comment]
这个属于JXPagingView库的bug，最新JXPagingView 2.0.10版本已经修复
