### ISSUE TITLE
如何优雅的处理这种业务

### ISSUE THREAD

**Issue by songhongkang** [pujiaxin33/JXCategoryView#313]
![899B77E7-B98A-473F-8A00-E332A483097D](https://user-images.githubusercontent.com/13045795/88457034-c94eab80-ceb5-11ea-8942-4d7feb1484fd.png)

两个子界面的业务都有编辑业务，如何优雅的处理这种业务。
请大佬指导一二，感激不尽

**Comment by pujiaxin33** [comment]
跟JXCategoryView有关系吗？

**Comment by songhongkang** [comment]
没有太大的关系，很多人用JXCategoryView，都会遇到这个业务，大家伙是如何处理的？

**Comment by pujiaxin33** [comment]
那你的问题可以概述为，导航栏右边有一个【编辑】按钮，这个如何优雅处理？

**Comment by pujiaxin33** [comment]
点击了编辑会push到新的页面？

**Comment by songhongkang** [comment]
拿JXCategoryView中的导航栏使用的demo来说。
NaviSegmentedControlViewController下面有两个子控制器分别为ListViewController1和ListViewController2。
【编辑】按钮在NaviSegmentedControlViewController的导航栏右边。
编辑功能可以想象成，可以删除控制器是数据源的业务。
假设当前显示的控制器为ListViewController1，用户点击【编辑】按钮，ListViewController1的tableview具有编辑功能，ListViewController2不具有编辑功能。
假设滚动到ListViewController2，用户点击【编辑】按钮，ListViewController2的tableview具有编辑功能，ListViewController1不具有编辑功能。
当用户点击【编辑】功能，如何禁止JXCategoryView中的UIscrollview的滚动和JXCategoryViewcollectionTitle的点击事件。
当用户点击【编辑】功能，如果不禁止事件，此时用户滚动，业务如何处理？

**Comment by pujiaxin33** [comment]
- 如何禁止JXCategoryView中的UIscrollview的滚动？你的意思是禁止列表容器的左右滚动吗？
JXCategoryListContainerView.scrollView.scrollEnabled = NO;

- 禁止JXCategoryViewcollectionTitle的点击事件

你不处理`- (void)categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex:(NSInteger)index;`代理方法即可。

或者通过`- (BOOL)categoryView:(JXCategoryBaseView *)categoryView canClickItemAtIndex:(NSInteger)index;`代理方法处理。

**Comment by Liyongcong** [comment]
有没有简单点的demo啊，作者这demo有点太复杂

**Comment by songhongkang** [comment]
有没有简单点的demo啊，作者这demo有点太复杂

哪里复杂了，看看就明白了。
难道和我需求一样？

**Comment by Liyongcong** [comment]
作者的demo嵌套的太多，看的有点迷糊，有稍微简单的demo版本么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pujiaxin33/JXCategoryView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 上午10:51
收件人:&nbsp;"pujiaxin33/JXCategoryView"<JXCategoryView@noreply.github.com&gt;;
抄送:&nbsp;"有bug的程序猿"<570703516@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pujiaxin33/JXCategoryView] 如何优雅的处理这种业务 (#313)





 
有没有简单点的demo啊，作者这demo有点太复杂
 
哪里复杂了，看看就明白了。
 难道和我需求一样？

**Comment by songhongkang** [comment]
https://lookin.work/
用这个工具看看demo中控制器和视图的层次结构
https://lookin.work/ 的功能和reveal一样

**Comment by Liyongcong** [comment]
好的我试试，多谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pujiaxin33/JXCategoryView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 上午10:56
收件人:&nbsp;"pujiaxin33/JXCategoryView"<JXCategoryView@noreply.github.com&gt;;
抄送:&nbsp;"有bug的程序猿"<570703516@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pujiaxin33/JXCategoryView] 如何优雅的处理这种业务 (#313)





 
https://lookin.work/
 用这个工具看看demo中控制器和视图的层次结构
 https://lookin.work/ 的功能和reveal一样
