### ISSUE TITLE
这个为什么不能代码选择哪个呢

### ISSUE THREAD

**Issue by ZClee128** [pujiaxin33/JXCategoryView#314]
只有一个默认选择，但是我需要self.jxTitleView.selectedIndex = 0;但是这个是只读的，这样有点问题吧，因为业务肯定有想跳到哪个tabbar

**Comment by littlebear333** [comment]
老弟用self.jxTitleView.defaultSelectedIndex = 0。先看看代码再问

**Comment by littlebear333** [comment]
可以直接用这个方法[self.categoryView selectCellAtIndex:0 selectedType:JXCategoryCellSelectedTypeClick];

**Comment by pujiaxin33** [comment]
调用该方法：
```
/**
 选中目标index的item

 @param index 目标index
 */
- (void)selectItemAtIndex:(NSInteger)index;
```
