### ISSUE TITLE
 [self.listContainerView scrollingFromLeftIndex:leftIndex toRightIndex:rightIndex ratio:ratio selectedIndex:categoryView.selectedIndex]; 方法不存在

### ISSUE THREAD

**Issue by boai** [pujiaxin33/JXCategoryView#315]
**bug描述**
 [self.listContainerView scrollingFromLeftIndex:leftIndex toRightIndex:rightIndex ratio:ratio selectedIndex:categoryView.selectedIndex]; 方法不存在

**版本号**
1.JXCategoryView版本号：Installing JXCategoryView 1.5.6 (was 1.5.5)
2.手机系统版本号：13.5.1
3.手机型号：11

**复现步骤**
- (void)categoryView:(JXCategoryBaseView *)categoryView scrollingFromLeftIndex:(NSInteger)leftIndex toRightIndex:(NSInteger)rightIndex ratio:(CGFloat)ratio {
    [self.listContainerView scrollingFromLeftIndex:leftIndex toRightIndex:rightIndex ratio:ratio selectedIndex:categoryView.selectedIndex];
}

**Comment by pujiaxin33** [comment]
新版本无需调用`[self.listContainerView scrollingFromLeftIndex:leftIndex toRightIndex:rightIndex ratio:ratio selectedIndex:categoryView.selectedIndex]; `方法了

**Comment by mrxiruo** [comment]
好吧
