### ISSUE TITLE
JXCategoryNumberView设置角标number时，如果是个位数，角标不是圆形

### ISSUE THREAD

**Issue by zxFlyer** [pujiaxin33/JXCategoryView#316]
**bug描述**
设置的角标如果是个位数，通过设置numberLabelWidthIncrement无法保证全部个位数字的角标是圆形，建议数字是个位数时将numberLabel的宽度设置为和高度一致。

**版本号**
1.JXCategoryView版本号：1.5.5
**截图、GIF**
提供bug出现时的截图或者GIF。
![5083F093-E2BF-4395-A137-AFE8E57B2C2E](https://user-images.githubusercontent.com/16473716/88878695-0c64a200-d25b-11ea-993a-9dddccd3ab47.png)
![77468949-6B38-451F-A618-10DA00448A1D](https://user-images.githubusercontent.com/16473716/88878696-0e2e6580-d25b-11ea-842e-b16c367c31a1.png)

**Comment by pujiaxin33** [comment]
最新代码添加了shouldMakeRoundWhenSingleNumber属性，设置为YES即可。
