### ISSUE TITLE
关于容器VC控制listVC的问题

### ISSUE THREAD

**Issue by dslcoding** [pujiaxin33/JXCategoryView#318]
我的收藏部分，由CollectVC(容器)和CollectListVC(这个用来展示内容的，按照你的示例代码来弄的)两。我现在
的需求是想在CollectVC加一个导航右侧按钮。做一个多行选择删除的功能。目前遇到的问题是在CollectVC加导航右侧按钮，控制不成CollectlistVC的内容。这该如何操作。请指导一下，谢谢。

**Comment by pujiaxin33** [comment]
请自己持有CollectlistVC，根据selectedIndex选择对应listVC即可。
