### ISSUE TITLE
多列表的时候点击状态栏不会返回到顶部啊，解决一下？

### ISSUE THREAD

**Issue by 396514268** [pujiaxin33/JXCategoryView#32]

**Comment by pujiaxin33** [comment]
// When the user taps the status bar, the scroll view beneath the touch which is closest to the status bar will be scrolled to top, but only if its `scrollsToTop` property is YES, its delegate does not return NO from `-scrollViewShouldScrollToTop:`, and it is not already at the top.
// On iPhone, we execute this gesture only if there's one on-screen scroll view with `scrollsToTop` == YES. If more than one is found, none will be scrolled.
@property(nonatomic) BOOL  scrollsToTop __TVOS_PROHIBITED;          // default is YES.

这是官网解释。就是说页面有多个UIScrollView的时候，必须把其他的scrollsToTop设置为NO，当前显示的UIScrollView设置为YES，才能响应状态栏点击滚动。这个事情需要你自己处理。
