### ISSUE TITLE
我想要滚动期间改变选中和未选中的标题主题色

### ISSUE THREAD

**Issue by abc8312111** [pujiaxin33/JXCategoryView#320]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？
目前公司有一款app，想要在滚动到第三个标题时，标题的选中颜色从原来的白色变成黑色。未选中的变成灰色，请问有这个实现的方案么？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你尝试循环调用`- (void)reloadCellAtIndex:(NSInteger)index;`方法，刷新cell的界面，这不会导致列表容器的变化，也不会中断当前的滚动交互
