### ISSUE TITLE
JXPagerView与JXCategoryView配合使用问题

### ISSUE THREAD

**Issue by HanXiaoTeng** [pujiaxin33/JXCategoryView#322]
也就是Demo中的个人中心demo
如果 - (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index 方法返回的一个view中有webview，滚动webview的时候，headerView不会产生平滑滚动 直接就是跳跃到顶部悬停，如果返回的view中有tableview就没有这个问题 请问怎么解决?

**Comment by pujiaxin33** [comment]
请参考示例，仔细比对代码。比如`- (void)listViewDidScrollCallback:(void (^)(UIScrollView *scrollView))callback;`有没有参考文档正确处理。
