### ISSUE TITLE
pagingView嵌套categoryView样式的使用问题

### ISSUE THREAD

**Issue by ZeroJson** [pujiaxin33/JXCategoryView#325]
**Feature描述**
使用了上面的嵌套后标题怎么分开设置

**参考效果**
想要两个二级title分来设置
目标效果截图：
![96461D26-FCBE-4F6C-A3B8-07FCF899100D](https://user-images.githubusercontent.com/15608700/92342279-fae0a680-f0f2-11ea-8c07-53527f793fb9.png)

**Comment by pujiaxin33** [comment]
请参考【嵌套使用】示例。
