### ISSUE TITLE
滚动切换的第一次不触发viewdidappear 而点击切换的第一次可以触发viewdidAppear

### ISSUE THREAD

**Issue by cnzlh** [pujiaxin33/JXCategoryView#326]
如题

**Comment by mcu1993** [comment]
我也遇到了这问题

**Comment by wenmobo** [comment]
我最近调试时也发现了这个问题

**Comment by wenmobo** [comment]
滑动的时候没有触发子控制器生命周期方法

**Comment by wenmobo** [comment]
![Uploading 截屏2020-10-16 下午1.16.39.png…]()
出现这种情况貌似是这里return了

**Comment by wenmobo** [comment]
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewDidScroll:)]) {
        [self.delegate listContainerViewDidScroll:scrollView];
    }

    if (!scrollView.isDragging && !scrollView.isTracking) {
        return;
    }
    CGFloat ratio = scrollView.contentOffset.x/scrollView.bounds.size.width;
    NSInteger maxCount = round(scrollView.contentSize.width/scrollView.bounds.size.width);
    NSInteger leftIndex = floorf(ratio);
    leftIndex = MAX(0, MIN(maxCount - 1, leftIndex));
    NSInteger rightIndex = leftIndex + 1;
    if (ratio < 0 || rightIndex >= maxCount) {
        [self listDidAppearOrDisappear:scrollView];
        return;
    }
    CGFloat remainderRatio = ratio - leftIndex;
    if (rightIndex == self.currentIndex) {
        //当前选中的在右边，用户正在从右边往左边滑动
        if (self.validListDict[@(leftIndex)] == nil && remainderRatio < (1 - self.initListPercent)) {
            [self initListIfNeededAtIndex:leftIndex];
        }else if (self.validListDict[@(leftIndex)] != nil) {
            if (self.willAppearIndex == -1) {
                self.willAppearIndex = leftIndex;
                [self listWillAppear:self.willAppearIndex];
            }
        }
        if (self.willDisappearIndex == -1) {
            self.willDisappearIndex = rightIndex;
            [self listWillDisappear:self.willDisappearIndex];
        }
    }else {
        //当前选中的在左边，用户正在从左边往右边滑动
        if (self.validListDict[@(rightIndex)] == nil && remainderRatio > self.initListPercent) {
            [self initListIfNeededAtIndex:rightIndex];
        }else if (self.validListDict[@(rightIndex)] != nil) {
            if (self.willAppearIndex == -1) {
                self.willAppearIndex = rightIndex;
                [self listWillAppear:self.willAppearIndex];
            }
        }
        if (self.willDisappearIndex == -1) {
            self.willDisappearIndex = leftIndex;
            [self listWillDisappear:self.willDisappearIndex];
        }
    }
    [self listDidAppearOrDisappear:scrollView];
}

出现这种情况貌似是这里return调了 导致下面方法不执行
if (!scrollView.isDragging && !scrollView.isTracking) {
        return;
    }

**Comment by wenmobo** [comment]
if (!scrollView.isDragging && !scrollView.isTracking && !scrollView.isDecelerating) {
        return;
    }
这样改我这里就没有问题了

**Comment by pujiaxin33** [comment]
就是滑动列表切换吗？我怎么没有复现，能再详细描述一下步骤吗？

**Comment by wenmobo** [comment]
可以将initListPercent值设置大一点，然后滑动距离小一点，触发系统的pageEnabled的自动滑动下一个，应该就能复现的

**Comment by pujiaxin33** [comment]
@wenmobo 感谢反馈与代码指正，已按照你的建议修复。

**Comment by cnzlh** [comment]
@wenmobo 感觉修复
