### ISSUE TITLE
iOS 14 AutoLayout 死循环导致栈溢出崩溃

### ISSUE THREAD

**Issue by joriwang** [pujiaxin33/JXCategoryView#329]
**bug描述**
使用 AutoLayout 后设置 `titleImageView.imageTypes = @[@(JXCategoryTitleImageType_TopImage), @(JXCategoryTitleImageType_TopImage), @(JXCategoryTitleImageType_TopImage)];` 后，会导致无限调用 `layoutSubViews` 方法，导致栈溢出

**版本号**
1.JXCategoryView版本号：1.5.6
2.手机系统版本号：iOS 14
3.手机型号：iPhone 11

**复现步骤**
```
categoryTitleView.imageNames = @[@"MainTabHomeNormal", @"MainTabClassifyNormal", @"MainTabLocalNormal"];
categoryTitleView.imageTypes = @[@(JXCategoryTitleImageType_TopImage), @(JXCategoryTitleImageType_TopImage), @(JXCategoryTitleImageType_TopImage)];
categoryTitleView.selectedImageNames = @[@"MainTabHomeNormal", @"MainTabClassifyNormal", @"MainTabLocalNormal"];
categoryTitleView.titleImageSpacing = 5;
categoryTitleView.cellSpacing = 0;

[self.view addSubview:self.categoryTitleView];
[categoryTitleView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.height.equalTo(@(60));
    make.left.equalTo(self.view).offset(24);
    make.right.equalTo(self.view).offset(-24);
    make.bottom.equalTo(self.view).offset(-15);
}];
```

**截图、GIF**
界面会一直卡在启动页面。原因是此时会无限次调用 `JXCategoryTitleCell` 及其子类的 `- (void)layoutSubviews`。

当 imageTypes 属性中有 `JXCategoryTitleImageType_TopImage` 值时，在 `JXCategoryTitleCell` 的 `- (void)layoutSubviews` 中会把 `self.titleLabelCenterY.constant` 置为 **0**。紧接着会在 `JXCategoryTitleImageCell` 的 `- (void)refreshTitleLabelCenter:(CGPoint)center` 方法中将 `self.titleLabelCenterY.constant` 置为非零值，并调用 `[self.contentView setNeedsLayout];[self.contentView layoutIfNeeded];`

**PS**

因为还没有完全理清框架逻辑，非常抱歉还不能提供补丁代码。望早日修复

@maltsugar @sclcoder @hstdt @pujiaxin33 @YanPengImp

**Comment by codingiran** [comment]
+1

**Comment by uncleRX** [comment]
+ 1

**Comment by lumianie** [comment]
+1

**Comment by joriwang** [comment]
在 `layoutSubviews` 里更新约束条件是一个错误的行为。应该是在约束所依赖的条件发生变化时才去自动更新。

titleCell 和 titleImageCell 的约束更新都依赖于 `cellModel` 的参数。正确做法是：1. 设置 cellModel 时把这个参数 copy 保存；2. 同时根据最新的 cellModel 更新约束参数。

我会在国庆假期推送 pr，如果哪位大神有时间希望能早点推送

**Comment by CcgKaneki** [comment]
这个bug太严重了，不知道什么时候修复？

**Comment by joriwang** [comment]
已使用 Swift 版替代

**Comment by pujiaxin33** [comment]
正在修复，晚上能搞定。

**Comment by pujiaxin33** [comment]
目前的仓库代码，已经修复了iOS循环layoutSubviews的crash。有空的朋友可以帮忙测试一下。只是目前有一个问题就是会导致JXCategoryTitleLabelAnchorPointStyle失效。考虑到此次crash问题的严重性和JXCategoryTitleLabelAnchorPointStyle特性的使用率应该不高。可以往后搁置一下。

**Comment by pujiaxin33** [comment]
@codingiran @lumianie @uncleRX @CcgKaneki
感谢大家的及时反馈，已经发布了1.5.7版本修复该问题。

**Comment by pujiaxin33** [comment]
大家先去最新仓库测试一下，自测是没有问题了，更新库之后，最好clean之后再编译一次项目

**Comment by joriwang** [comment]
> 大家先去最新仓库测试一下，自测是没有问题了，更新库之后，最好clean之后再编译一次项目

使用 `UIStackView` 是个非常好的思路。

这里我有一个疑问。titleImageCell 中 把 titleLabel 从父视图移除后其对应的约束也就失效了，这个时候父类 titleCell 中设置的 `titleLabelCenterY` 也就会失效，这样 `titleLabelAnchorPointStyle` 就只修改了 `anchorPoint` 这样会不会造成错位？

**Comment by pujiaxin33** [comment]
titleimage不支持锚点
