### ISSUE TITLE
使用JXCategoryTitleView时希望给Title添加阴影

### ISSUE THREAD

**Issue by MrBugDou** [pujiaxin33/JXCategoryView#330]
**Feature描述**
在JXCategoryTitleView中给每个title添加字体阴影

**参考效果**
![image](https://user-images.githubusercontent.com/12947653/93754353-2d7eb900-fc34-11ea-8ebc-e60e79979e26.png)
设计稿长这样😂

**其他补充**
关于目标效果的其他说明：？
想要一个思路，目前要改的话只能改源码，想问问现有代码是否支持添加这种阴影

**Comment by weizhangCoder** [comment]
> **Feature描述**
> 在JXCategoryTitleView中给每个title添加字体阴影
> 
> **参考效果**
> ![image](https://user-images.githubusercontent.com/12947653/93754353-2d7eb900-fc34-11ea-8ebc-e60e79979e26.png)
> 设计稿长这样😂
> 
> **其他补充**
> 关于目标效果的其他说明：？
> 想要一个思路，目前要改的话只能改源码，想问问现有代码是否支持添加这种阴影

你看自定义里面，应该都是可以支持的

**Comment by pujiaxin33** [comment]
继承成JXCategoryTitleView，然后给titleLabel加上shaow属性即可。就是参考自定义示例，稍微自己修改一下即可。
