### ISSUE TITLE
JXCategoryIndicatorBackgroundView  希望可以支持选中背景和未选中背景可以同时设置？

### ISSUE THREAD

**Issue by fengshuo1992** [pujiaxin33/JXCategoryView#332]
![效果图 ](https://user-images.githubusercontent.com/15105920/94388478-be4b1c80-017f-11eb-902f-1c429c8def5a.png)
**Feature描述**
请简单描述你想要的效果：？

我看了源码 好像现在不能设置这样的样式 希望大佬能看到我这个

**Comment by weizhangCoder** [comment]
你看自定义里面有一个title背景cell，应该可以满足你的需求。

**Comment by weizhangCoder** [comment]
> ![效果图 ](https://user-images.githubusercontent.com/15105920/94388478-be4b1c80-017f-11eb-902f-1c429c8def5a.png)
> **Feature描述**
> 请简单描述你想要的效果：？
> 
> 我看了源码 好像现在不能设置这样的样式 希望大佬能看到我这个

你看自定义里面有一个title背景cell，应该可以满足你的需求。

**Comment by fengshuo1992** [comment]
谢谢了大兄弟

**Comment by fengshuo1992** [comment]
> > ![效果图 ](https://user-images.githubusercontent.com/15105920/94388478-be4b1c80-017f-11eb-902f-1c429c8def5a.png)
> > **Feature描述**
> > 请简单描述你想要的效果：？
> > 我看了源码 好像现在不能设置这样的样式 希望大佬能看到我这个
> 
> 你看自定义里面有一个title背景cell，应该可以满足你的需求。

谢谢大兄弟
