### ISSUE TITLE
1.5.6及以上版本JXCategoryTitleView显示问题

### ISSUE THREAD

**Issue by woxihejinghao** [pujiaxin33/JXCategoryView#334]
**bug描述**
在系统版本为iOS 10.3.3的手机上，JXCategoryView在1.5.6及以上JXCategoryTitleView显示无效，看了图层结构，CollectionVIew是在的，但是里面的item没有，在1.5.5及一下版本表现正常

**版本号**
1.JXCategoryView版本号：1.5.6及以上
2.手机系统版本号：10.3.3
3.手机型号：iPhone6p

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryTitleView显示失效
2.具体的操作步骤是：JXCategoryTitleView设置为navigationItem.leftBarButtonItem

**截图、GIF**
![IMG_0302](https://user-images.githubusercontent.com/21906803/95645620-9484e480-0af3-11eb-8683-aa079370d561.PNG)
![IMG_0303](https://user-images.githubusercontent.com/21906803/95645621-977fd500-0af3-11eb-94bf-50f53738fc52.PNG)

**Comment by woxihejinghao** [comment]
第一个截图是1.5.7版本的 第二个是1.5.5的

**Comment by pujiaxin33** [comment]
能提供关键代码吗？

**Comment by woxihejinghao** [comment]
self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc]initWithCustomView:self.myCategoryView];
    self.navigationItem.titleView = [UIView new];
    self.myCategoryView.defaultSelectedIndex = self.currentIndex;
    self.myCategoryView.titles = @[@"手表",@"体脂秤"];
    self.myCategoryView.frame = CGRectMake(0, 0, 160, 30);
    self.myCategoryView.titleLabelZoomScale = 1.18;
    self.myCategoryView.cellSpacing = 15;
    self.myCategoryView.titleColorGradientEnabled = true;
    self.myCategoryView.titleLabelZoomEnabled = true;
    self.myCategoryView.contentEdgeInsetLeft = 5;
    self.myCategoryView.titleSelectedColor = WYHexColor(0x32343C);
    self.myCategoryView.titleColor = WYHexColor(0x8A8B90);
    self.myCategoryView.titleFont = [UIFont fontWithName:@"PingFangSC-Semibold" size:17];
    self.myCategoryView.delegate = self;
    self.myCategoryView.listContainer = self.listContainerView;
    
    [self.view addSubview:self.listContainerView];
    if (@available(iOS 11.0, *)) {
        self.listContainerView.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    } else {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }

**Comment by woxihejinghao** [comment]
两个版本代码一样

**Comment by woxihejinghao** [comment]
我曾经尝试注释了相关的样式设置，依然有同样的问题

**Comment by pujiaxin33** [comment]
我将示例demo里面的类`NaviSegmentedControlViewController`，里面的配置代码修改为：
```
 //    self.navigationItem.titleView = self.myCategoryView;
        self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:self.myCategoryView];
```
以实现和你一样的配置再导航栏左边的效果。在iOS13.1、14.0模拟器上面，均没有出现你说的问题。

麻烦你按照上面同样的配置，在你iOS10.3.3系统测试一下呢？

**Comment by woxihejinghao** [comment]
有个比较尴尬的问题是，在iOS 10.3.3系统上 运行Demo，进入任何一个示例都出现一下问题了。iOS14系统上没有问题.我看到了你的源码确实做了系统版本判断，但是依然出现了这个问题。
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIScrollView setContentInsetAdjustmentBehavior:]: unrecognized selector sent to instance 0x10089ac00'

**Comment by woxihejinghao** [comment]
![image](https://user-images.githubusercontent.com/21906803/95649529-62ce4680-0b10-11eb-9704-70a2461449bb.png)

**Comment by woxihejinghao** [comment]
<img width="1400" alt="QQ20201010-155148@2x" src="https://user-images.githubusercontent.com/21906803/95649566-8d200400-0b10-11eb-837d-f8d708e49535.png">
这个是iOS 10.3.3 上面的调用

**Comment by pujiaxin33** [comment]
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIScrollView setContentInsetAdjustmentBehavior:]: unrecognized selector sent to instance 0x10089ac00'

这个我也遇到了，总感觉是新版本XCode的bug，明明是有版本判断的，却还是调用了11版本的代码，十分费解。

**Comment by pujiaxin33** [comment]
你把setContentInsetAdjustmentBehavior相关代码注释掉，暂时跑起来看看。

**Comment by woxihejinghao** [comment]
嗯 我运行Demo似乎没有问题，就是会有一个跳位的奇怪动画，myCategoryView在导航栏完全进入后有一个位置偏移，不显示的问题我按照Demo看看怎么调整一下

**Comment by LiuSky** [comment]
我也是遇到一摸一样的问题。重点是我直接给到view都不行

**Comment by LiuSky** [comment]
<img width="1115" alt="截屏2020-10-24 上午11 23 50" src="https://user-images.githubusercontent.com/3087745/97066970-6b804b80-15eb-11eb-8520-ed50ce629c10.png">
最骚的是。10.3.1系统上。这段会不执行，但是明明有数量。在11上面确实没问题。看来xcode12.2 bug了

**Comment by pujiaxin33** [comment]
@LiuSky 最新的仓库代码已经修复这个问题了。
