### ISSUE TITLE
设置defaultSelectedIndex进入控制器时不按照index加载自定义view

### ISSUE THREAD

**Issue by IsTheGrass** [pujiaxin33/JXCategoryView#336]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：最新
2.手机系统版本号：iOS14
3.手机型号：iPhone7

**复现步骤**
1. 遇到问题的相关效果、类是：categoryView和pagerView联动的时候，我设置defaultSelectedIndex每次进入控制器- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index这个方法会加载两次，
2.具体的操作步骤是：实际代码和demo中的PagingViewController使用场景一模一样，只是我设置了defaultSelectedIndex，然后进入控制器的时候会在上述方法中走两次，打断点调试，发现第一次的index=3，第二次index=1，但是两次初始化的居然是index=1时初始化的view, 我打印的有didAppear

**截图、GIF**
提供bug出现时的截图或者GIF。
![WeChatf16d3765d1e217c346d4858b52d58bf3](https://user-images.githubusercontent.com/28552508/96092985-2a5aae00-0efe-11eb-993b-401163e981e5.png)

**Comment by pujiaxin33** [comment]
需要
```
self.categoryView.defaultSelectedIndex = 1;
self.pagingView.defaultSelectedIndex = 1;
```
需要同时设置为相同值
