### ISSUE TITLE
个人中心demo的问题

### ISSUE THREAD

**Issue by 295060456** [pujiaxin33/JXCategoryView#338]
1、建议所有的demo用懒加载；
2、个人中心的demo我就说为什么会崩，原来写的有问题，没有 [self.view addSubview:_userHeaderView]; 和 [self.view addSubview:_categoryView];  编译器自动调整了，自动纠错。但是我要在后面加一个按钮，就加不上会崩，原因在此。

**Comment by pujiaxin33** [comment]
1、即使不使用懒加载也不会造成问题，只要再使用前正确初始化；
2、麻烦把问题描述清楚一点。

**Comment by 295060456** [comment]
是这样的：
1、我个人习惯是masonry+懒加载，看起来是一个方法块，用alpha = 1调用；其中发现
        _categoryTitleView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(11111110, 0, [UIScreen mainScreen].bounds.size.width, JXheightForHeaderInSection)];

其实只对宽和高做了限定，xy值后面会被冲掉，自动调整，个人觉得不严谨，因为里面有图后面会被撑开，你也在viewDidLayoutSubviews里面写了方法，这个方法是刷新时候调用，我还是推崇懒加载，要不代码太乱了；
2、MVVM的一个思路是，一个vc对应一个vm，那么下面的子控件，我觉得还是原来的VC比较好，而不是处理成view；
3、这里面就有差异了。       _categoryTitleView.listContainer = (id<JXCategoryViewListContainer>)self.pagingView.listContainerView;

  而一般的是： _categoryTitleView.listContainer = self.listContainerView;
就相当于中间加了一层；
那么相对应的就不能像普通模式那样:
#pragma mark - JXCategoryListContainerViewDelegate
-(id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView
                                         initListForIndex:(NSInteger)index{
    return self.childVCsMutArr[index];
}

- (NSInteger)numberOfListsInlistContainerView:(JXCategoryListContainerView *)listContainerView {
    return self.titlesMutArr.count;
}

但是这个地方
- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index 
你是写了接口的，相当于我可以返回一个vc，只不过这个vc要实现协议JXPagerViewListViewDelegate


好了 入侵性来了。
我希望我的vc是个干干净净的而不是有很多插件的痕迹 ，这样移植性要好很多
现在我必须实现JXPagerViewListViewDelegate，关键是有个必须实现的协议：
#pragma mark - JXPagingViewListViewDelegate

- (UIScrollView *)listScrollView {
    return self.tableView;
}


可问题是，我不一定是tableView覆盖在子控件上面


相对应的，你的JXCategoryListContentViewDelegate我是这么写的：
======.h======
#import <UIKit/UIKit.h>
#import "JXCategoryView.h"

NS_ASSUME_NONNULL_BEGIN

@interface UIViewController (JXCategoryListContentViewDelegate)
<
JXCategoryListContentViewDelegate
>

/**
 如果列表是VC，就返回VC.view
 如果列表是View，就返回View自己

 @return 返回列表视图
 */
- (UIView *)listView;

@end

NS_ASSUME_NONNULL_END


=====.m========
#import "UIViewController+JXCategoryListContentViewDelegate.h"

@implementation UIViewController (JXCategoryListContentViewDelegate)

/**
 如果列表是VC，就返回VC.view
 如果列表是View，就返回View自己

 @return 返回列表视图
 */
- (UIView *)listView{
    return self.view;
}

@end


所以，我就很头疼...你懂我的意思吧？


demo建议全部写成懒加载，这样好看一些，而不单是东一句西一句

**Comment by 295060456** [comment]
//        _categoryTitleView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(11111110, 0, [UIScreen mainScreen].bounds.size.width, JXheightForHeaderInSection)];

这个地方，反正你设置xy都会被冲掉，你就直接写
        _categoryTitleView.mj_w = MAINSCREEN_WIDTH;
        _categoryTitleView.mj_h = JXheightForHeaderInSection;

这样用户也会很好接受

masonry直接照之前的你写的来改写，就直接定死在一个位置。不能masonry  或者适当的时候 iflayout..没必要，不优雅

**Comment by pujiaxin33** [comment]
1、` _categoryTitleView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(11111110, 0, [UIScreen mainScreen].bounds.size.width, JXheightForHeaderInSection)];`这句代码是有点欠妥。因为category最终会被放到paging的sectionHeader方法，所以就像你说的只需要指定宽高就可以了。所以，在不引入第三方库的情况下，我改为下面的代码：
```
    _categoryView = [[JXCategoryTitleView alloc] init];
    self.categoryView.bounds = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, JXheightForHeaderInSection);
```

**Comment by pujiaxin33** [comment]
> 2、MVVM的一个思路是，一个vc对应一个vm，那么下面的子控件，我觉得还是原来的VC比较好，而不是处理成view；

不太清楚你想表达什么，但是对于列表来说，无论是vc还是view都可以。

**Comment by pujiaxin33** [comment]
3、这个问题涉及到的问题比较多，我大概明白你的意思，但是，可能事情没有那么简单。

首先，category和paging是完全解耦的两个库，又因为他们的listContainer逻辑完全一致，所以，最后通过`_categoryTitleView.listContainer = (id)self.pagingView.listContainerView;`的方法来关联，你尝试把他们分为两个不同的库来思考一下。

然后就是列表的封装逻辑，只有通过一个JXPagerViewListViewDelegate协议，来对列表进行解耦。达到不管你的列表是什么类，只要遵从协议内容即可。

**Comment by 295060456** [comment]
> > 2、MVVM的一个思路是，一个vc对应一个vm，那么下面的子控件，我觉得还是原来的VC比较好，而不是处理成view；
> 
> 不太清楚你想表达什么，但是对于列表来说，无论是vc还是view都可以。

因为，一个vc对应一个vm对应一个请求，网络请求只对vc而不是view，我觉得是一个很好的规范。

**Comment by 295060456** [comment]
我写了个。希望可以加到你的代码里面：

========.h===========
#import <UIKit/UIKit.h>
#if __has_include(<JXPagingView/JXPagerView.h>)
#import <JXPagingView/JXPagerView.h>
#else
#import "JXPagerView.h"
#endif

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface UIViewController (JXPagerViewListViewDelegate)
<
JXPagerViewListViewDelegate,
UIScrollViewDelegate
>

@property(nonatomic,strong)UIScrollView *scrollView;
@property(nonatomic,copy)void(^scrollCallback)(UIScrollView *scrollView);

@end

NS_ASSUME_NONNULL_END


========.m=========

#import "UIViewController+JXPagerViewListViewDelegate.h"

@implementation UIViewController (JXPagerViewListViewDelegate)

static char *UIViewController_JXPagingViewListViewDelegate_scrollView = "UIViewController_JXPagingViewListViewDelegate_scrollView";
static char *UIViewController_JXPagingViewListViewDelegate_scrollCallback = "UIViewController_JXPagingViewListViewDelegate_scrollCallback";

@dynamic scrollView;
@dynamic scrollCallback;

#pragma mark —— UIScrollViewDelegate
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    self.scrollCallback(scrollView);
}

#pragma mark —— JXPagerViewListViewDelegate
- (UIScrollView *)listScrollView {
    return self.scrollView;
}

- (void)listViewDidScrollCallback:(void (^)(UIScrollView *))callback {
    self.scrollCallback = callback;
}

- (UIView *)listView {
    return self.view;
}
#pragma mark —— @property(nonatomic,strong)UIScrollView *scrollView;
-(UIScrollView *)scrollView{
    UIScrollView *ScrollView = objc_getAssociatedObject(self, UIViewController_JXPagingViewListViewDelegate_scrollView);
    if (!ScrollView) {
        ScrollView = UIScrollView.new;
        ScrollView.delegate = self;
        [self.view addSubview:ScrollView];
        objc_setAssociatedObject(self,
                                 UIViewController_JXPagingViewListViewDelegate_scrollView,
                                 ScrollView,
                                 OBJC_ASSOCIATION_RETAIN_NONATOMIC);
        [ScrollView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.edges.equalTo(self.view);
        }];
    }return ScrollView;
}

-(void)setScrollView:(UIScrollView *)scrollView{
    objc_setAssociatedObject(self,
                             UIViewController_JXPagingViewListViewDelegate_scrollView,
                             scrollView,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}
#pragma mark —— @property(nonatomic,copy)void(^scrollCallback)(UIScrollView *scrollView);
-(void)setScrollCallback:(void (^)(UIScrollView * _Nonnull))scrollCallback{
    objc_setAssociatedObject(self,
                             UIViewController_JXPagingViewListViewDelegate_scrollCallback,
                             scrollCallback,
                             OBJC_ASSOCIATION_COPY_NONATOMIC);
}

-(void (^)(UIScrollView * _Nonnull))scrollCallback{
    return objc_getAssociatedObject(self, UIViewController_JXPagingViewListViewDelegate_scrollCallback);
}

@end


用的时候：

- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView
                             initListAtIndex:(NSInteger)index {
//    TestListBaseView *list = [[TestListBaseView alloc] init];
//    if (index == 0) {
//        list.dataSource = @[@"橡胶火箭", @"橡胶火箭炮", @"橡胶机关枪", @"橡胶子弹", @"橡胶攻城炮", @"橡胶象枪", @"橡胶象枪乱打", @"橡胶灰熊铳", @"橡胶雷神象枪", @"橡胶猿王枪", @"橡胶犀·榴弹炮", @"橡胶大蛇炮", @"橡胶火箭", @"橡胶火箭炮", @"橡胶机关枪", @"橡胶子弹", @"橡胶攻城炮", @"橡胶象枪", @"橡胶象枪乱打", @"橡胶灰熊铳", @"橡胶雷神象枪", @"橡胶猿王枪", @"橡胶犀·榴弹炮", @"橡胶大蛇炮"].mutableCopy;
//    }else if (index == 1) {
//        list.dataSource = @[@"吃烤肉", @"吃鸡腿肉", @"吃牛肉", @"各种肉"].mutableCopy;
//    }else if (index == 2) {
//        list.dataSource = @[@"【剑士】罗罗诺亚·索隆", @"【航海士】娜美", @"【狙击手】乌索普", @"【厨师】香吉士", @"【船医】托尼托尼·乔巴", @"【船匠】 弗兰奇", @"【音乐家】布鲁克", @"【考古学家】妮可·罗宾", @"【船匠】 弗兰奇", @"【音乐家】布鲁克", @"【考古学家】妮可·罗宾", @"【船匠】 弗兰奇", @"【音乐家】布鲁克", @"【考古学家】妮可·罗宾", @"【船匠】 弗兰奇", @"【音乐家】布鲁克", @"【考古学家】妮可·罗宾"].mutableCopy;
//    }
//    return list;
    return self.childVCsMutArr[0];
}

-(NSMutableArray<UIViewController *> *)childVCsMutArr{
    if (!_childVCsMutArr) {
        _childVCsMutArr = NSMutableArray.array;
        [_childVCsMutArr addObject:DynamicVC.new];
        [_childVCsMutArr addObject:ForecastVC.new];
        [_childVCsMutArr addObject:VideoVC.new];
        [_childVCsMutArr addObject:ReleaseVC.new];
        [_childVCsMutArr addObject:CommentVC.new];
    }return _childVCsMutArr;
}

**Comment by 295060456** [comment]
> 1、` _categoryTitleView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(11111110, 0, [UIScreen mainScreen].bounds.size.width, JXheightForHeaderInSection)];`这句代码是有点欠妥。因为category最终会被放到paging的sectionHeader方法，所以就像你说的只需要指定宽高就可以了。所以，在不引入第三方库的情况下，我改为下面的代码：
> 
> ```
>     _categoryView = [[JXCategoryTitleView alloc] init];
>     self.categoryView.bounds = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, JXheightForHeaderInSection);
> ```
不用mj的，你也可以定义一个类啊：

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface UIView (Measure)

@property(nonatomic,assign)CGFloat x;
@property(nonatomic,assign)CGFloat y;
@property(nonatomic,assign,readonly) CGFloat maxX;
@property(nonatomic,assign,readonly) CGFloat maxY;
@property(nonatomic,assign)CGFloat width;
@property(nonatomic,assign)CGFloat height;
@property(nonatomic,assign)CGFloat centerX;
@property(nonatomic,assign)CGFloat centerY;
@property(nonatomic,assign)CGSize size;
@property(nonatomic,assign)CGPoint origin;
@property(nonatomic,assign)CGFloat left;
@property(nonatomic,assign)CGFloat right;
@property(nonatomic)CGFloat top;
@property(nonatomic,assign)CGFloat bottom;

@end

NS_ASSUME_NONNULL_END


#import "UIView+Measure.h"

@implementation UIView (Measure)

-(CGFloat)top {
    return CGRectGetMinY(self.frame);
}

- (void)setTop:(CGFloat)y {
    CGRect frame = self.frame;
    frame.origin.y = y;
    self.frame = frame;
}

- (void)setX:(CGFloat)x{
    CGRect frame = self.frame;
    frame.origin.x = x;
    self.frame = frame;
}

- (void)setY:(CGFloat)y{
    CGRect frame = self.frame;
    frame.origin.y = y;
    self.frame = frame;
}

- (CGFloat)x{
    return self.frame.origin.x;
}

- (CGFloat)y{
    return self.frame.origin.y;
}

-(void)setMaxX:(CGFloat)maxX{
    
}

-(CGFloat)maxX{
    return CGRectGetMaxX(self.frame);
}

-(void)setMaxY:(CGFloat)maxY{
    
}

-(CGFloat)maxY{
    return CGRectGetMaxY(self.frame);
}

-(void)setCenterX:(CGFloat)centerX{
    CGPoint center = self.center;
    center.x = centerX;
    self.center = center;
}

-(CGFloat)centerX{
    return self.center.x;
}

-(void)setCenterY:(CGFloat)centerY{
    CGPoint center = self.center;
    center.y = centerY;
    self.center = center;
}

-(CGFloat)centerY{
    return self.center.y;
}

-(void)setWidth:(CGFloat)width{
    CGRect frame = self.frame;
    frame.size.width = width;
    self.frame = frame;
}

-(void)setHeight:(CGFloat)height{
    CGRect frame = self.frame;
    frame.size.height = height;
    self.frame = frame;
}

-(CGFloat)height{
    return self.frame.size.height;
}

-(CGFloat)width{
    return self.frame.size.width;
}

-(void)setSize:(CGSize)size{
    CGRect frame = self.frame;
    frame.size = size;
    self.frame = frame;
}

-(CGSize)size{
    return self.frame.size;
}

-(void)setOrigin:(CGPoint)origin{
    CGRect frame = self.frame;
    frame.origin = origin;
    self.frame = frame;
}

-(CGPoint)origin{
    return self.frame.origin;
}

-(CGFloat)getX{
    return CGRectGetMaxX(self.frame);
}

-(CGFloat)left {
    return self.frame.origin.x;
}

-(CGFloat)getY{
    return CGRectGetMaxY(self.frame);
}

-(CGFloat)right {
    return self.frame.origin.x + self.frame.size.width;
}

-(void)setLeft:(CGFloat)x {
    CGRect frame = self.frame;
    frame.origin.x = x;
    self.frame = frame;
}

-(void)setRight:(CGFloat)right {
    CGRect frame = self.frame;
    frame.origin.x = right - frame.size.width;
    self.frame = frame;
}

-(CGFloat)bottom {
    return self.frame.origin.y + self.frame.size.height;
}

-(void)setBottom:(CGFloat)bottom {
    CGRect frame = self.frame;
    frame.origin.y = bottom - frame.size.height;
    self.frame = frame;
}



@end



mj的对center 没有写

**Comment by pujiaxin33** [comment]
非常感谢你的扩展建议，但是，我想让demo尽量减少各种扩展，通过bounds赋值，我觉得已经符合情景了。

**Comment by pujiaxin33** [comment]
关于`(id)pagerView:(JXPagerView *)pagerView
initListAtIndex:(NSInteger)index`希望你可以看一下相关注释，这个是需要根据index懒加载，不是懒加载childVCsMutArr。

**Comment by pujiaxin33** [comment]
> 因为，一个vc对应一个vm对应一个请求，网络请求只对vc而不是view，我觉得是一个很好的规范。

因为历史原因，有些项目就是封装了一个view来实现了逻辑，所以，你的mvvm建议是好的，但是需要考虑老mvc项目用户的需求。而且demo初期就是用listView来搭建的，所以，你的mvvm建议非常好，如果只是一个全新的项目，我会首先考虑的。

**Comment by 295060456** [comment]
> > 因为，一个vc对应一个vm对应一个请求，网络请求只对vc而不是view，我觉得是一个很好的规范。
> 
> 因为历史原因，有些项目就是封装了一个view来实现了逻辑，所以，你的mvvm建议是好的，但是需要考虑老mvc项目用户的需求。而且demo初期就是用listView来搭建的，所以，你的mvvm建议非常好，如果只是一个全新的项目，我会首先考虑的。

主要是考虑到view就只管显示数据，数据怎么处理和获取他不关心，不管是mvp 还是mvvm都是这样 view就单纯一点，否则很臃肿；懒加载主要是考虑到代码块规范性的问题，用不用他直接注销/放开一句代码即可。我都这么用的。

**Comment by pujiaxin33** [comment]
问题有点讨论偏了，我再拉回主题哈。你说的mvp、mvvm我都懂。我这里的列表封装是可以使用vc的，所以就不会有你说的问题。但是因为上面说的历史原因，有很大一部分人，他们的列表逻辑就是在一个view里面。所以，为了支持他们无缝使用paging库（不可能让他们为了用paging库，就必须把一个个列表view转成vc），所以，示例也顺便就用了listView来做了示例。

不晓得这样表达，能否解答你的问题。

**Comment by 295060456** [comment]
我又发现了一个问题。就是个人中心那个demo，我如果要定义某一个子view或者是子vc，在上下拖动的时候JXCategoryDotView不跟着动，怎么处理？
纵观全局，滑动的处理是以下协议方法：
- (void)pagerView:(JXPagerView *)pagerView
mainTableViewDidScroll:(UIScrollView *)scrollView{
    [self.userHeaderView scrollViewDidScroll:scrollView.contentOffset.y];
}

我也打印了pagerView和scrollView的subviews。发现那些子view没有包含在里面。那我怎么做现在？

**Comment by pujiaxin33** [comment]
JXPagingView不支持header不跟着动。
