### ISSUE TITLE
藏了nav后，下个界面又显示nav，之后返回nav动画问题

### ISSUE THREAD

**Issue by xiamoweinuan** [pujiaxin33/JXCategoryView#341]
UIViewController中隐藏了nav
self.navigationController.navigationBarHidden = YES;
之后跳转到其他界面显示了nav，点击返回时候nav动画的问题，看图，

![](https://user-images.githubusercontent.com/7007749/96975528-2574aa80-154d-11eb-9177-d44cc6b315a1.jpg)
，设置了subvc的nav后，动画还是不行。
要不然就是这种方式，viewDidAppear后导航条又消失了

(void)viewDidLoad {
[super viewDidLoad];
self.navigationController.navigationBarHidden = YES;
}
(void)viewDidAppear:(BOOL)animated {
[super viewDidAppear:animated];
self.navigationController.navigationBarHidden = YES;
}
(void)viewWillDisappear:(BOOL)animated {
[super viewWillDisappear:animated];
self.navigationController.navigationBarHidden = NO;
}

![](https://user-images.githubusercontent.com/7007749/96976897-f3644800-154e-11eb-8dd6-43fe990114e8.jpg)

**Comment by pujiaxin33** [comment]
这个是系统特性
