### ISSUE TITLE
JXPagerSmoothView第一次加载后，往下滑动一段距离后，切换子页面会闪退

### ISSUE THREAD

**Issue by Style-Tender** [pujiaxin33/JXCategoryView#343]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
当页面加载完成后，页面往下滑动一段距离后，切换子页面会闪退。如果不往下滑动则不会闪退。

**版本号**
1.JXCategoryView版本号：2.0.13
2.手机系统版本号：13.5.1
3.手机型号：XR

**复现步骤**
1. 遇到问题的相关效果、类是：
使用的是JXPagerSmoothView类
第一次加载完成之后，往下滑动一段距离，再切换子页面会闪退。相关效果见下图

2.具体的操作步骤是：
第一次加载完成之后，往下滑动一段距离，再切换子页面

**截图、GIF**
提供bug出现时的截图或者GIF。
闪退时，定位到的代码位置
![image](https://user-images.githubusercontent.com/22140088/97400537-401e9900-192a-11eb-9d9f-577456614681.png)
伴随了一个警告
![image](https://user-images.githubusercontent.com/22140088/97400572-4e6cb500-192a-11eb-8357-33589b14bdb4.png)

**Comment by pujiaxin33** [comment]
建议使用最新的JXPagingView，然后就是请到JXPagingView库提交相关issue
