### ISSUE TITLE
希望既能JXCategoryTitleBackgroundView 又能 JXCategoryDotView

### ISSUE THREAD

**Issue by 295060456** [pujiaxin33/JXCategoryView#345]
能自定义每一个按钮的背景图和背景色
又能在右上角出现原点

**Comment by 295060456** [comment]
希望既能JXCategoryDotView 又能实现JXCategoryTitleImageView的imageNames和selectedImageNames

**Comment by 295060456** [comment]
能不能对外只暴露一个类，里面可选属性决定JXCategoryDotView、JXCategoryTitleBackgroundView等的特性？

**Comment by pujiaxin33** [comment]
基于现在通过继承的实现原理，暂时满足不了你的需求。如果底层是通过组合的形式实现，就可以了。基于两者的差异过大，实在是改不动了。
