### ISSUE TITLE
在不改动源码的情况下为每一个JXCategoryBaseCell及其子类添加背景图的解决方案

### ISSUE THREAD

**Issue by 295060456** [pujiaxin33/JXCategoryView#347]
static const NSInteger DefaultShow = 1;//默认显示第几号

-(void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];
    
    for (int i = 0; i < self.titlesMutArr.count; i++) {
        JXCategoryTitleImageCell *lastCell = (JXCategoryTitleImageCell *)[self.categoryTitleView.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:i inSection:0]];
        
        Ivar ivar = class_getInstanceVariable([JXCategoryTitleImageCell class], "_stackView");//必须是下划线接属性
        UIStackView *stackView = object_getIvar(lastCell, ivar);
        
        UIImageView *unSelectedBgimgV = UIImageView.new;
        unSelectedBgimgV.tag = 999;
        unSelectedBgimgV.image = KIMG(@"未选中背景");
        
        if (DefaultShow == i) {
            unSelectedBgimgV.alpha = 0;
        }else{
            unSelectedBgimgV.alpha = 1;
        }
        
        [stackView insertSubview:unSelectedBgimgV atIndex:0];
        [unSelectedBgimgV mas_makeConstraints:^(MASConstraintMaker *make) {
            make.edges.equalTo(stackView);
        }];
    }
}

#pragma mark - JXCategoryViewDelegate
-(void)categoryView:(JXCategoryBaseView *)categoryView
didSelectedItemAtIndex:(NSInteger)index {//终值
    
    for (int i = 0; i < self.titlesMutArr.count; i++) {
        JXCategoryTitleImageCell *lastCell = (JXCategoryTitleImageCell *)[self.categoryTitleView.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:i inSection:0]];
        
        Ivar ivar = class_getInstanceVariable([JXCategoryTitleImageCell class], "_stackView");//必须是下划线接属性
        UIStackView *stackView = object_getIvar(lastCell, ivar);
        
        UIView *subView = [stackView viewWithTag:999];
        if (index == i) {
            subView.alpha = 0;
        }else{
            subView.alpha = 1;
        }
    }
    [self.listContainerView didClickSelectedItemAtIndex:index];
}

**Comment by pujiaxin33** [comment]
非常厉害，但还是建议通过继承的方式更为妥当一点。
