### ISSUE TITLE
刷新数据+列表自定义，嵌套tableview和webview

### ISSUE THREAD

**Issue by QionglinFu1024** [pujiaxin33/JXCategoryView#351]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：1.5.7
2.手机系统版本号：14
3.手机型号：6p

**复现步骤**
1. 遇到问题的相关效果、类是：刷新数据+列表自定义，嵌套一个tableview和一个webview，从tableview滑动到webview可以，但是webview页面就滑不回去了
2.具体的操作步骤是：大佬指导一下这种手势冲突怎么解决。。。

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
webview的contentsize.width是不是比列表宽度大，这样可能就只会响应webview，手势无法传递到外部。
