### ISSUE TITLE
怎么根据当前的索引值去获取对应的控制器呢？

### ISSUE THREAD

**Issue by 624990742** [pujiaxin33/JXCategoryView#356]
怎么根据当前的索引值去获取对应的控制器呢？

**Comment by CQHO** [comment]
在父类控制器里持有 容器内的子控制器，子控制器里包含UITextView时，引发闪退

**Comment by pujiaxin33** [comment]
需要自己缓存记录，比如通过字典key就是index，value就是列表控制器。加载了哪个列表，就记录哪个列表。
