### ISSUE TITLE
父ViewController持有带UITextView子控制器点击闪退

### ISSUE THREAD

**Issue by CQHO** [pujiaxin33/JXCategoryView#358]
**bug描述**
使用场景是一个父ViewController + 两个子控制器，通过JXCategoryListContainerView加载，其中一个控制器内有UITextView.
如果在父控制器里持有 带有UITextView的哪个子控制器，运行起来，点击UITextView,键盘弹不出来。闪退
// 返回各个列表菜单下的实例，该实例需要遵守并实现 <JXCategoryListContentViewDelegate> 协议
- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index {
    if(index == 0){
        XSRecordInputDraftViewController *inputVC = [[XSRecordInputDraftViewController alloc]init];
        inputVC.draft_title = self.draft_title;
        inputVC.draft_content = self.draft_content;
        inputVC.draft_id = self.draft_id;
        inputVC.delegate = self;
        self.inputViewController = inputVC;//持有子控制器，注掉这行则不会有问题。

**版本号**
1.JXCategoryView版本号:1.5.6
2.手机系统版本号：13.6.1
3.手机型号：8 P

**复现步骤**
1. 遇到问题的相关效果、类是：点击UITextView ，键盘弹出来以前闪退
2.具体的操作步骤是：
注掉上面那行持有子类的代码则一切正常

**Comment by pujiaxin33** [comment]
可以发送一个能复现问题的demo工程吗？
