### ISSUE TITLE
JXCategoryIndicatorView frame 位置不正确

### ISSUE THREAD

**Issue by maomaoxiansheng** [pujiaxin33/JXCategoryView#36]
![ladpdgq9qswalmtmtm0e2g_1242_180 jpg_620x10000q90g](https://user-images.githubusercontent.com/8021663/46777984-3ecea380-cd44-11e8-8c29-ecf4cf5b5a4e.jpg)
![Uploading lADPDgQ9qSWalMTMtM0E2g_1242_180.jpg_620x10000q90g.jpg…]()
<img width="419" alt="2018-10-11 10 53 33" src="https://user-images.githubusercontent.com/8021663/46777985-3f673a00-cd44-11e8-9c7d-f35cd89933a8.png">

我在JXCategoryIndicatorView.m的- (void)refreshState{}函数最后面添加了
JXCategoryIndicatorCell *selectedCell = (JXCategoryIndicatorCell *)[self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:self.selectedIndex inSection:0]];
    //是否点击了相对于选中cell左边的cell
    JXCategoryCellClickedPosition clickedPosition = JXCategoryCellClickedPosition_Left;
    CGRect clickedCellFrame = [self getTargetCellFrame:self.selectedIndex];
    for (UIView<JXCategoryIndicatorProtocol> *component in self.indicators)
    {
        [component jx_selectedCell:selectedCell.frame clickedRelativePosition:clickedPosition];
        if ([component isKindOfClass:[JXCategoryIndicatorBackgroundView class]]) {
            CGRect maskFrame = component.frame;
            maskFrame.origin.x = maskFrame.origin.x - clickedCellFrame.origin.x;
            selectedCellModel.backgroundViewMaskFrame = maskFrame;
        }
    }

并且修改了- (BOOL)selectCellAtIndex:(NSInteger)index {}函数
[selectedCell reloadData:selectedCellModel];写在了循环刷新Frame的前面
如果在刷新前面遍历写Frame，当cell的宽度太长时，会出现偏差。所以我写在了后面。

修改原因：JXCategoryIndicatorView位置不正确
可能是第一个选项显示cell宽度太长，导致我选中第二个的时候回自动滚动第二个到可见位置，然而JXCategoryIndicatorView获取的是滚动之前的cell的位置，导致JXCategoryIndicatorView位置显示不正确。

我暂时解决了问题，如果您进行了修改，我会重新Pod进工程，谢谢。

**Comment by pujiaxin33** [comment]
在未修改源码前，你出现这个问题是如何配置的？是不是把第一个cell的宽度设置大一点就会出现？

**Comment by pujiaxin33** [comment]
还在么？能否把你出现问题是否的配置，发给我一下吗？我需要先重现问题的场景

**Comment by pujiaxin33** [comment]
如果能加qq：317437084，把示例demo，发给我最好了

**Comment by maomaoxiansheng** [comment]
我们最好UI改掉了。就删除了。没再注意了。尴尬😅。

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
