### ISSUE TITLE
如果我希望能够在 titleview 底部加一条边线，请问我可以怎么处理？

### ISSUE THREAD

**Issue by szmichaelyb** [pujiaxin33/JXCategoryView#360]
**bug描述**

**如果我希望能够在 titleview 底部加一条边线，请问我可以怎么处理？**

![demo](https://upload-images.jianshu.io/upload_images/563374-da537e8d893a2fd6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

图片地址：https://upload-images.jianshu.io/upload_images/563374-da537e8d893a2fd6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**版本号**
1.JXCategoryView版本号：2.0.13

**截图、GIF**

如果我希望能够在 titleview 底部加一条边线，请问我可以怎么处理？

![demo](https://upload-images.jianshu.io/upload_images/563374-da537e8d893a2fd6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

图片地址：https://upload-images.jianshu.io/upload_images/563374-da537e8d893a2fd6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by Michaelyb520** [comment]
## 希望将 JXCategoryListContainerViewDelegate 协议中ScrollView中的代理方法扩展多一点

> 另外，希望将 JXCategoryListContainerViewDelegate 协议中ScrollView中的代理方法扩展多一点，有些特定需求，有些特定需求可能还是会用得上。

```Objective-C

@optional
- (void)listContainerViewWillBeginDragging:(UIScrollView *)scrollView;
- (void)listContainerViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate;
- (void)listContainerViewWillBeginDecelerating:(UIScrollView *)scrollView;
- (void)listContainerViewDidEndDecelerating:(UIScrollView *)scrollView;
- (void)listContainerViewDidScroll:(UIScrollView *)scrollView;

```

- 实现

```Objective-C

- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
    //滑动到一半又取消滑动处理
    if (self.willDisappearIndex != -1) {
        [self listWillAppear:self.willDisappearIndex];
        [self listWillDisappear:self.willAppearIndex];
        [self listDidAppear:self.willDisappearIndex];
        [self listDidDisappear:self.willAppearIndex];
        self.willDisappearIndex = -1;
        self.willAppearIndex = -1;
    }
    
    if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewDidEndDecelerating:)]) {
        [self.delegate listContainerViewDidEndDecelerating:scrollView];
    }
}

- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewWillBeginDragging:)]) {
        [self.delegate listContainerViewWillBeginDragging:scrollView];
    }
}
- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewDidEndDragging:willDecelerate:)]) {
        [self.delegate listContainerViewDidEndDragging:scrollView willDecelerate:decelerate];
    }
}
- (void)scrollViewWillBeginDecelerating:(UIScrollView *)scrollView
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewWillBeginDecelerating:)]) {
        [self.delegate listContainerViewWillBeginDecelerating:scrollView];
    }
}

```

**Comment by dulifu** [comment]
我也遇到了一样的问题，JXCategoryTitleView添加底部线条View，这个View会盖住indicator，只能设置indicator往上偏移，稍微有点尴尬

**Comment by dulifu** [comment]
@szmichaelyb  titleView添加底部线条的问题，我这边最终使用的方法是给titleView设置背景颜色为透明，然后在它的父视图相同位置添加了线条

**Comment by szmichaelyb** [comment]
> @szmichaelyb titleView添加底部线条的问题，我这边最终使用的方法是给titleView设置背景颜色为透明，然后在它的父视图相同位置添加了线条

目前我也是这么处理的，不过用的是 layer，减少容器视图。

**Comment by pujiaxin33** [comment]
> @szmichaelyb titleView添加底部线条的问题，我这边最终使用的方法是给titleView设置背景颜色为透明，然后在它的父视图相同位置添加了线条

就是这么解决

**Comment by pujiaxin33** [comment]
> ## 希望将 JXCategoryListContainerViewDelegate 协议中ScrollView中的代理方法扩展多一点
> > 另外，希望将 JXCategoryListContainerViewDelegate 协议中ScrollView中的代理方法扩展多一点，因为我发现，有些特定需求，可能还是会用得上。
> 
> * 扩展协议
> 
> ```objc
> @optional
> - (void)listContainerViewWillBeginDragging:(UIScrollView *)scrollView;
> - (void)listContainerViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate;
> - (void)listContainerViewWillBeginDecelerating:(UIScrollView *)scrollView;
> - (void)listContainerViewDidEndDecelerating:(UIScrollView *)scrollView;
> - (void)listContainerViewDidScroll:(UIScrollView *)scrollView;
> ```
> 
> * 实现
> 
> ```objc
> - (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
>     //滑动到一半又取消滑动处理
>     if (self.willDisappearIndex != -1) {
>         [self listWillAppear:self.willDisappearIndex];
>         [self listWillDisappear:self.willAppearIndex];
>         [self listDidAppear:self.willDisappearIndex];
>         [self listDidDisappear:self.willAppearIndex];
>         self.willDisappearIndex = -1;
>         self.willAppearIndex = -1;
>     }
>     
>     if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewDidEndDecelerating:)]) {
>         [self.delegate listContainerViewDidEndDecelerating:scrollView];
>     }
> }
> 
> - (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView
> {
>     if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewWillBeginDragging:)]) {
>         [self.delegate listContainerViewWillBeginDragging:scrollView];
>     }
> }
> 
> - (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate
> {
>     if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewDidEndDragging:willDecelerate:)]) {
>         [self.delegate listContainerViewDidEndDragging:scrollView willDecelerate:decelerate];
>     }
> }
> 
> - (void)scrollViewWillBeginDecelerating:(UIScrollView *)scrollView
> {
>     if (self.delegate && [self.delegate respondsToSelector:@selector(listContainerViewWillBeginDecelerating:)]) {
>         [self.delegate listContainerViewWillBeginDecelerating:scrollView];
>     }
> }
> ```

感谢反馈，已添加
