### ISSUE TITLE
当JXCategoryBaseView中collectionView的Frame改变时，其子视图(cell，indicator)的Frame没有得到响应

### ISSUE THREAD

**Issue by jiasongs** [pujiaxin33/JXCategoryView#361]
**bug描述**
业务场景为「横竖屏切换」，「iPad分屏模式切换」，「macOS转制版改变窗口大小」等，当JXCategoryBaseView中collectionView的Frame改变时，只有第一次改变会触发子视图(cell，indicator)的布局，如下图：

<img width="925" alt="图片" src="https://user-images.githubusercontent.com/22904757/103183032-07c81680-48eb-11eb-9296-4c659a5339af.png">

后续collectionView的Frame改变时，并不会触发子视图的布局，导致布局不符合预期，应该需要添加一行代码，如下图：

<img width="799" alt="图片" src="https://user-images.githubusercontent.com/22904757/103183065-39d97880-48eb-11eb-8ef0-370e75836138.png">

因为collectionView的Frame或者bounds改变，往往会引起其子视图(cell，indicator)的Frame或bounds改变，如不更新布局，那么将会停留再之前布局的状态，显然不符合预期

**版本号**
1.JXCategoryView版本号：1.5.8
2.手机系统版本号：14.2
3.手机型号：模拟器

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryBaseView
2.具体的操作步骤是：如「bug描述」所述

**截图、GIF**
没有执行`[self refreshState]`的情况如下：

https://user-images.githubusercontent.com/22904757/103183537-149a3980-48ee-11eb-9ad2-49e88a1f1371.mp4

执行`[self refreshState]`的情况如下：

https://user-images.githubusercontent.com/22904757/103183562-2bd92700-48ee-11eb-9c96-2a8f6c837847.mp4

**Comment by pujiaxin33** [comment]
感谢你的反馈，已按照你的方案进行了优化。
