### ISSUE TITLE
可以做类似于小米商城分类中滑动联动效果么

### ISSUE THREAD

**Issue by DotaAntiMagic** [pujiaxin33/JXCategoryView#362]
**Feature描述**
请简单描述你想要的效果：？
类似于小米商城或者饿了么中的分类联动效果么
**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？小米商城分类选项卡
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

https://user-images.githubusercontent.com/13567812/103255847-dec88400-49c5-11eb-8ed3-ffebc6ef0116.mp4

![1609211142407792 video_thumb](https://user-images.githubusercontent.com/13567812/103255849-e25c0b00-49c5-11eb-9dd5-53cfbb3df3ba.jpg)

**Comment by pujiaxin33** [comment]
这个需要自己实现，暂不支持
