### ISSUE TITLE
列表是UIView类，把父vc的navigationcontroller传给view持有，会造成循环引用

### ISSUE THREAD

**Issue by JimmyCJJ** [pujiaxin33/JXCategoryView#364]
<img width="1752" alt="WeChateccc225f9301e5542178ab083d1794a9" src="https://user-images.githubusercontent.com/45547234/103737565-65680b80-502d-11eb-8e54-b804417ab79b.png">

**Comment by QuintGao** [comment]
用weak修饰

**Comment by JimmyCJJ** [comment]
> 用weak修饰

right
