### ISSUE TITLE
JXCategoryImageView不能设置图片垂直方向缩放时的基准位置

### ISSUE THREAD

**Issue by MQTwist** [pujiaxin33/JXCategoryView#365]
JXCategoryImageView不能像JXCategoryTitleView一样设置图片垂直方向缩放时的基准位置。
希望添加类似JXCategoryTitleView属性【titleLabelVerticalOffset】、【titleLabelAnchorPointStyle】。
JXCategoryTitleImageView有同样的需求

**Comment by pujiaxin33** [comment]
欢迎你提交相关的feature PR
