### ISSUE TITLE
storyboard里创建JXCategoryListContainerView，无法设置代理

### ISSUE THREAD

**Issue by czl0325** [pujiaxin33/JXCategoryView#367]
**Feature描述**
请简单描述你想要的效果：
JXCategoryListContainerView是在storyboard里创建的，所以无需调用initWithType方法，导致无法设置代理。

**参考效果**
如果你想要实现一个其他APP已有的效果：
请单独提出设置代理和type的方法。

**其他补充**
关于目标效果的其他说明：无

**Comment by pujiaxin33** [comment]
暂不支持xib初始化
