### ISSUE TITLE
在页面上下滑动的过程中修改pagingView的frame,最后一个选项的数据就会变成倒数第二个选项的数据

### ISSUE THREAD

**Issue by weiwei1991** [pujiaxin33/JXCategoryView#368]
最新版本；
在页面上下滑动的过程中修改pagingView的frame,最后一个选项的数据就会变成倒数第二个选项的数据：
self.pagingView.frame = CGRectMake(0, kNavBarHeight+(KISIphoneX ? 20:0), SCREEN_WIDTH, SCREEN_HEIGHT - kNavBarAndStatusBarHeight-(KISIphoneX ? 60 : 30))
<img width="1034" alt="WX20210121-175851@2x" src="https://user-images.githubusercontent.com/7012340/105335297-d9e8a000-5c12-11eb-99d6-763b032f3d65.png">

**Comment by pengzishang** [comment]
我也出现了这个问题,页面之间的内容完全串了

**Comment by pujiaxin33** [comment]
请使用JXPagingView库最新版本，再尝试一下，建议JXPagingView库的问题，请到https://github.com/pujiaxin33/JXPagingView 这里提交

**Comment by powfulhong** [comment]
单纯用JXCategoryView也会出现这个现象，不一定能复现，但以下步骤复现的概率很高：快速左右滑，然后在某个页面，突然向上滑，这时，内容会是某个页面的内容，而category却不是显示内容的index。
