### ISSUE TITLE
[JXCategoryBaseView(UISubclassingBaseHooks) contentOffsetOfContentScrollViewDidChanged:] 646 某些情况下数组越界，导致Crash

### ISSUE THREAD

**Issue by chnFrchn** [pujiaxin33/JXCategoryView#369]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
后台收集到一些数组越界Crash，看起来是滑动时触发了源码内部的一处数组越界，但没复现出来。堆栈如下，关键词：[JXCategoryBaseView(UISubclassingBaseHooks) contentOffsetOfContentScrollViewDidChanged:] 646 

NSException *** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array
Thread 0 name: com.apple.main-thread
0CoreFoundation
___exceptionPreprocess (in CoreFoundation)
3CoreFoundation
-[__NSArrayM objectAtIndexedSubscript:] (in CoreFoundation)
4XSFM
-[JXCategoryBaseView(UISubclassingBaseHooks) contentOffsetOfContentScrollViewDidChanged:] (in XSFM) JXCategoryBaseView.m:646
5XSFM
-[JXCategoryIndicatorView contentOffsetOfContentScrollViewDidChanged:] (in XSFM) JXCategoryIndicatorView.m:98
6XSFM
-[JXCategoryBaseView observeValueForKeyPath:ofObject:change:context:] (in XSFM) JXCategoryBaseView.m:225
7Foundation
_NSKeyValueNotifyObserver (in Foundation)
8Foundation
_NSKeyValueDidChange (in Foundation)
9Foundation
-[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] (in Foundation)
10Foundation
-[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] (in Foundation)
11Foundation
__NSSetPointValueAndNotify (in Foundation)
12UIKitCore
-[UIScrollView _updatePanGesture] (in UIKitCore)
13UIKitCore
-[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] (in UIKitCore)
14UIKitCore
__UIGestureRecognizerSendTargetActions (in UIKitCore)
15UIKitCore
__UIGestureRecognizerSendActions (in UIKitCore)
16UIKitCore
-[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] (in UIKitCore)
17UIKitCore
__UIGestureEnvironmentUpdate (in UIKitCore)
18UIKitCore
-[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] (in UIKitCore)
19UIKitCore
-[UIGestureEnvironment _updateForEvent:window:] (in UIKitCore)
20UIKitCore
-[UIWindow sendEvent:] (in UIKitCore)
21UIKitCore
-[UIApplication sendEvent:] (in UIKitCore)
22UIKitCore
___dispatchPreprocessedEventFromEventQueue (in UIKitCore)
23UIKitCore
___handleEventQueueInternal (in UIKitCore)
24UIKitCore
___handleHIDEventFetcherDrain (in UIKitCore)
25CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ (in CoreFoundation)
26CoreFoundation
___CFRunLoopDoSource0 (in CoreFoundation)
27CoreFoundation
___CFRunLoopDoSources0 (in CoreFoundation)
28CoreFoundation
___CFRunLoopRun (in CoreFoundation)
29CoreFoundation
_CFRunLoopRunSpecific (in CoreFoundation)
30GraphicsServices
_GSEventRunModal (in GraphicsServices)
31UIKitCore
_UIApplicationMain (in UIKitCore)
32XSFM
main (in XSFM) main.m:43
33libdyld.dylib
_start (in libdyld.dylib)

**版本号**
1.JXCategoryView版本号：1.5.2
2.手机系统版本号：无集中特征
3.手机型号：无集中特征

**复现步骤**
1. 遇到问题的相关效果、类是：？ JXCategoryBaseView(UISubclassingBaseHooks) contentOffsetOfContentScrollViewDidChanged
2.具体的操作步骤是：？暂时没复现

**截图、GIF**
提供bug出现时的截图或者GIF。
![image](https://user-images.githubusercontent.com/51433415/106260306-3b37f100-625b-11eb-94b1-4843f9ad67f7.png)

**Comment by pujiaxin33** [comment]
感谢反馈，已对dataSource为空进行了优化
