### ISSUE TITLE
 selectItemAtIndex 或 setDefaultSelectedIndex 问题

### ISSUE THREAD

**Issue by jozdee** [pujiaxin33/JXCategoryView#373]
在初始化后调用   selectItemAtIndex 或 setDefaultSelectedIndex  能否自动滚动到中心位置，现在发现会正确设置，但是如果分组栏目过多，在屏幕外的话，他不会滑到到屏幕显示范围内

**Comment by pujiaxin33** [comment]
selectItemAtIndex是初始化之后，即视图已经显示出来之后，调用才会生效。
初始化的时候，设置defaultSelectedIndex属性，即可配置默认选择的index。
