### ISSUE TITLE
每次都会调用该方法

### ISSUE THREAD

**Issue by wxgwxgwxg** [pujiaxin33/JXCategoryView#374]
**Feature描述**
调用一次listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index这个方法以后，我左滑动 也想再次调用

这个改项目的效果图
![IMG_0826](https://user-images.githubusercontent.com/81205747/112085007-b3b88f80-8bc4-11eb-9daf-f8062f1d5f37.PNG)

我要做一个筛选根据两个条件来得到相应的数据，我现在只用一个条件是没有问题，但在加一个条件以后。在下来刷新这个时候就不对呢

**Comment by pujiaxin33** [comment]
调用reloadData方法刷新整个数据
