### ISSUE TITLE
设置了titleSelectedFont 后 JXCategoryViewAutomaticDimension 不准确问题

### ISSUE THREAD

**Issue by charlesYun** [pujiaxin33/JXCategoryView#375]
设置了titleSelectedFont 后 JXCategoryViewAutomaticDimension 不准确问题

**Comment by charlesYun** [comment]
修改了这个方法 
- (CGFloat)preferredCellWidthAtIndex:(NSInteger)index {
    if (self.cellWidth == JXCategoryViewAutomaticDimension) {
        if (self.titleDataSource && [self.titleDataSource respondsToSelector:@selector(categoryTitleView:widthForTitle:)]) {
            return [self.titleDataSource categoryTitleView:self widthForTitle:self.titles[index]];
        } else {
            return ceilf([self.titles[index] boundingRectWithSize:CGSizeMake(MAXFLOAT, self.bounds.size.height) options:NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading attributes:@{NSFontAttributeName : self.titleSelectedFont} context:nil].size.width);
        }
    } else {
        return self.cellWidth;
    }
}

**Comment by pujiaxin33** [comment]
感谢你的反馈，如果需要cell宽度动态变化，请参考《大小缩放+Cell宽度缩放》示例。

**Comment by pujiaxin33** [comment]
如果没有开启cellWidthZoomEnabled属性，那么cell宽度都是固定的，变化的就只能是cell里面的内容，目前的设计思路就是这样的。
