### ISSUE TITLE
JXCategoryView 竖直效果

### ISSUE THREAD

**Issue by xiaoyao20084321** [pujiaxin33/JXCategoryView#376]
**Feature描述**
想要竖直效果

**参考效果**
1.目标效果截图：？
![image](https://user-images.githubusercontent.com/10344550/113684629-02534700-96f8-11eb-8505-92628f1f86c4.png)

**Comment by pujiaxin33** [comment]
通过UITableView即可实现，无需JXCategoryView支持。
