### ISSUE TITLE
标题列表数据源的动态更新

### ISSUE THREAD

**Issue by DZflycat** [pujiaxin33/JXCategoryView#377]
**Feature描述**
JXCategoryTitleView作为二级菜单，根据一级菜单动态更新。

**参考效果**
一个页面，左侧是纵向的tableview作为一级菜单，右侧顶部将JXCategoryTitleView作为二级菜单横向滚动，二级菜单的标题是动态根据左侧一级菜单来变化的。

问题：初始化之后，再次调用[self.subCategoryTitleView setTitles:@"aaa",@"bbb",@"ccc",@"ddd"];更新JXCategoryTitleView没有变化。

**Comment by pujiaxin33** [comment]
重复Issue
