### ISSUE TITLE
和UIPageViewController一起结合使用遇到的问题

### ISSUE THREAD

**Issue by kakashilw** [pujiaxin33/JXCategoryView#38]
首先感谢提供了这么好的一个库哈，很方便！

然后我们集成的时候，是把这个和UIPageViewController一起结合使用的，最开始我们在UIPageViewController里面获取到UIScrollView，命名为theScrollView，然后想通过

    self.categoryView.contentScrollView = self.theScrollView;

实现两者结合，发现滑动的时候很怪，经常滑动了一下，而标题栏那里就滑动了2个，而且不太好追踪问题所在。

后来我们就想分开实现，首先实现当滑动之后，标题栏移动到相应的栏目上面，这个没问题，通过    [self.categoryView selectCellAtIndex:index];这个方法解决了，如下代码：

- (void)viewPager:(ViewPagerController *)viewPager didChangeTabToIndex:(NSUInteger)index {

    [self.categoryView selectCellAtIndex:index];

}

然后我们想移动的过程中，有跟随动画，然后我们研究了源代码，然后结合你们源代码里对UIScrollview那样

   [self.theScrollView addObserver:self forKeyPath:@"contentOffset" options:NSKeyValueObservingOptionNew context:nil];
    
#pragma mark - KVO

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context
{
    
    if ([keyPath isEqualToString:@"contentOffset"] && (self.theScrollView.isTracking || self.theScrollView.isDecelerating)) {
        //用户滚动引起的contentOffset变化，才处理。
        CGPoint contentOffset = [change[NSKeyValueChangeNewKey] CGPointValue];

        [self.categoryView contentOffsetOfContentScrollViewDidChanged:contentOffset];
    }
}

主要是调用这个方法        [self.categoryView contentOffsetOfContentScrollViewDidChanged:contentOffset];

然后就怎么都没有反应。所以想请教一下这种和UIPageViewController结合使用的时候，想实现有跟随动画的话，有什么好的解决方法吗？

**Comment by pujiaxin33** [comment]
请问你现在使用demo验证的吗？
建议你加入QQ群： 112440151
把你的demo发给我
直接用你的demo来调试，不然我不知道具体是什么问题

**Comment by pujiaxin33** [comment]
你好，经过自己测试，发现UIPageViewController内部实现比较特殊，当我在ios12上面，创建只有一个VC的UIPageViewController时，它的布局信息如下：
```
<_UIQueuingScrollView: 0x7fbf7b03e200; frame = (-1 0; 416 656); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600001f52580>; layer = <CALayer: 0x600001137e60>; contentOffset: {416, 0}; contentSize: {1248, 656}; adjustedContentInset: {0, -416, 0, -416}>
```
可以看到它的contentSize是宽度的三倍，并且adjustedContentInset.left和.right都是-416。
UIPageViewController本身支持多种切换效果，所以系统对它持有的scrollView做了特殊处理。
结论就是JXCategoryView不适合跟UIPageViewController配合使用，建议你使用UIScrollView处理。
