### ISSUE TITLE
标题缩放状态或者选中字体大小不一致，能否设置左对齐

### ISSUE THREAD

**Issue by GKWenBo** [pujiaxin33/JXCategoryView#381]
**Feature描述**
项目中我使用了JXCategoryTitleImageView指示器样式，选中标题字号要大于未选中字号，_categoryView.contentEdgeInsetLeft = 15;出现了左边内容间距不是我设置的间距情况，有没有方法使选中状态也是15的间距呢

**参考效果**
如果你想要实现一个其他APP已有的效果：
![WechatIMG19071](https://user-images.githubusercontent.com/25070098/116027272-02a38a00-a687-11eb-9cb2-dfb857ba572f.jpeg)
![WechatIMG19072](https://user-images.githubusercontent.com/25070098/116027277-06cfa780-a687-11eb-9186-352fbcfc6041.jpeg)
![截屏2021-04-26 下午12 00 04](https://user-images.githubusercontent.com/25070098/116027284-0b945b80-a687-11eb-8165-acd4a36e965d.png)

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
建议参考《大小缩放+Cell宽度缩放》示例实现你想要的效果。
示例代码如下：
```Objective-C
        titleCategoryView.titleColorGradientEnabled = YES;
        titleCategoryView.titleLabelZoomEnabled = YES;
        titleCategoryView.titleLabelZoomScale = 1.3;
        titleCategoryView.titleLabelStrokeWidthEnabled = YES;
        titleCategoryView.selectedAnimationEnabled = YES;
        titleCategoryView.cellWidthZoomEnabled = YES;
        titleCategoryView.cellWidthZoomScale = 1.3;
```

**Comment by GKWenBo** [comment]
好的，感谢解答
