### ISSUE TITLE
JXCategoryView 1.5.8 版本，当从服务器更新title时，调用reloadData 进行更新，会闪一下屏，可能是因为标题发生了改变，listContainer 容器需要重新创建的问题，能否进行优化

### ISSUE THREAD

**Issue by PengYang1991** [pujiaxin33/JXCategoryView#382]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXCategoryView版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
应该是reloadData导致了列表的重新创建，然后列表请求数据到显示中间有一个时间，所以导致了你说的“闪一下屏”。建议参考《删除、增加、重新排序不重复创建列表》示例，当title是已有的，就复用之前的列表。应该就能解决你说的问题。
