### ISSUE TITLE
如何让标题栏JXCategoryTitleView内容居左显示？

### ISSUE THREAD

**Issue by cityleaf** [pujiaxin33/JXCategoryView#383]
**Feature描述**
项目中需要标题栏居左显示，目前是剧中显示。

**参考效果**
<img width="706" alt="image" src="https://user-images.githubusercontent.com/15885391/117603348-6b116180-b185-11eb-9e7c-9df839a104f7.png">

需要在哪里做设置或能否提供在何处更改的思路呢

**Comment by naijoug** [comment]
设置 dataSource 属性 `isItemSpacingAverageEnabled = false`

**Comment by Liyongcong** [comment]
> 设置 dataSource 属性 `isItemSpacingAverageEnabled = false`

这是哪个属性呀，没找到呀
