### ISSUE TITLE
JXCategoryTitleImageView怎么分别调整title和image的垂直位置

### ISSUE THREAD

**Issue by a1906404** [pujiaxin33/JXCategoryView#385]
![image](https://user-images.githubusercontent.com/13724610/119596473-cc863100-be11-11eb-853d-8279cd785bb9.png)
JXCategoryTitleImageView怎么分别调整title和image的垂直位置，titleLabelVerticalOffset设置这个属性不管用 位置不变。

**Comment by pujiaxin33** [comment]
设置titleImageSpacing
