### ISSUE TITLE
在代理- (void)categoryView:(JXCategoryBaseView *)categoryView scrollingFromLeftIndex:(NSInteger)leftIndex toRightIndex:(NSInteger)rightIndex ratio:(CGFloat)ratio中,是否可以加入滑动方向左右的属性?

### ISSUE THREAD

**Issue by pengzishang** [pujiaxin33/JXCategoryView#388]
**Feature描述**
请简单描述你想要的效果：？

一开始想通过监听categoryView的collectview代理进行方向的左右判断,后来发现这个代理被占用了,还有其他方法吗?
**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你可以通过当前categoryView的selectedIndex和leftIndex、rightIndex判断，就知道左右滑动方向了。
