### ISSUE TITLE
listContainerView中加入滑动视图之后，按钮需要点击两次才生效

### ISSUE THREAD

**Issue by Mrrabbitbaby** [pujiaxin33/JXCategoryView#396]
**bug描述**
当listContainerView中使用了uicollectionView，在collectionView中添加UICollectionReusableViewFooter, footer中添加按钮，此时我滑动视图，点击事件第一次不能响应，需要连续点击两次才能响应。

**版本号**
1.JXCategoryView版本号：1.5.9
2.手机系统版本号：14.6（应该无关）
3.手机型号：iPhone XS Max 

**复现步骤**
1. 遇到问题的相关效果、类是：listContainerView中的控制器
2.具体的操作步骤是：listContainerView中使用一个控制器或view都可以，这个视图中使用 uicollectionView展示数据，在uicollectionView中加入UICollectionReusableViewFooter， footer中添加一个按钮，然后当数据数量达到时，点击一次按钮，然后滑动这个collectionView，再次点击无效，不响应，需要点击两次才会响应，不滑动没有问题。

**Comment by pujiaxin33** [comment]
你发一个复现问题的项目。

**Comment by Mrrabbitbaby** [comment]
我大概知道原因了，是因为滑动listContainerView中的子视图时，滑动动画完成之后，大概有1秒左右的迟疑，也就是说，我们看到视图滑动已经停止，但是实际上并不是，所以再次点击时，它默认的动作是要子视图停止滚动，而不是响应点击事件。这个问题不止发生在footerview上，只要你要在listContainerView中的子视图中滑动，当它停下来的时候，立即去点击不管是button，cell,都不会响应点击事件，实际是做的是停止子视图滚动的动作。我们的项目马上发版本，明后天就可以查看问题所在，【网上老年大学】首页的【推荐】底部有个【换一换】按钮可复现问题。

**Comment by pujiaxin33** [comment]
你分析的很到位，列表只要在滚动，上面的按钮，点击第一次都无法响应

**Comment by sauchye** [comment]
@pujiaxin33 发现相似问题，我已更新最新版本JXCategoryView 1.5.9 半屏显示collectionView列表，发现部分手机不响应点击事件，如：iPhone 11 滑动切换几次后再次点击一个按钮，此时响应以下方法，但依旧上一个选中按钮，滑动切换正常，多次点击当前按钮，此时可以点击切换到第一个按钮，iPhone 8正常，同iOS 14.6
```
- (void)categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex:(NSInteger)index {
    NSLog(@"didSelectedItemAtIndex");
}

- (void)categoryView:(JXCategoryBaseView *)categoryView didClickSelectedItemAtIndex:(NSInteger)index{
    NSLog(@"didClickSelectedItemAtIndex");
}
```

**Comment by pujiaxin33** [comment]
我这边没有办法复现，所以，没办法找到问题原因。
