### ISSUE TITLE
子vc 的 push 问题

### ISSUE THREAD

**Issue by zeroccDeNA** [pujiaxin33/JXCategoryView#40]
子 vc 无法使用 nav 的push啦？是我使用姿势问题吗

**Comment by pujiaxin33** [comment]
因为子VC没有在导航栏栈里面，当然获取不到它的navi。建议给子VC新增一个naviController（自己取一个类似名字就行）的属性。把父VC的navi赋值给子VC，然后子VC用naviController进行push操作
