### ISSUE TITLE
你好，可以把categoryView 的selectItemAtIndex方法 把是否显示动画开出来吗，我们应用内有的地方不想展示滚动动画效果

### ISSUE THREAD

**Issue by EdwinXiang** [pujiaxin33/JXCategoryView#400]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
selectedAnimationEnabled设置为NO即可。

**Comment by rggsix** [comment]
categoryTitleView.isContentScrollViewClickTransitionAnimationEnabled = false
