### ISSUE TITLE
JXCategoryTitleView在使用的时候，无法在异步网络请求中赋值。

### ISSUE THREAD

**Issue by taojeff** [pujiaxin33/JXCategoryView#405]
我现在有个页面想用到JXCategoryTitleView的视图，然后创建完成后，在网络请求的成功里写titles的赋值无效。而在方法外面写的却能正常赋值，在进行断点查看后，发现如果是在异步方法中使用赋值的话，则JXCategoryTitleView中titles拿到的数据则为nil
![1](https://user-images.githubusercontent.com/19642626/130794113-75003919-d87a-4e75-a52b-5aa16afef7c7.jpg)
![2](https://user-images.githubusercontent.com/19642626/130794125-961c55bc-fb0c-46a9-98e1-c9204317dbad.png)

**Comment by michaelyht** [comment]
> 异步设置titles后要调用categoryView的reloadData方法

这样一来，title是刷新了；但是页面确实空白的，请问如何破解

**Comment by pujiaxin33** [comment]
异步设置titles后要调用categoryView的reloadData方法，会重新生成list。
