### ISSUE TITLE
关于嵌套使用问题

### ISSUE THREAD

**Issue by Mrrabbitbaby** [pujiaxin33/JXCategoryView#406]
目前有特殊的使用，类似于【嵌套使用】这个例子，但是例子顶部是固定的，我现在想实现的功能是：顶部是一个HeaderView（上面带有CategoryTitleView），然后子视图中还带有CategoryTitleView，目前根据Demo中的来实现，但是效果不尽人意，请问能否给一个Demo？？

如果可以，请上传到Demo中或者私发我15570879240@163.com，感谢！！！

**Comment by pujiaxin33** [comment]
你看一下这个库是否有你想要的效果：https://github.com/pujiaxin33/JXPagingView

**Comment by Liyongcong** [comment]
> 目前有特殊的使用，类似于【嵌套使用】这个例子，但是例子顶部是固定的，我现在想实现的功能是：顶部是一个HeaderView（上面带有CategoryTitleView），然后子视图中还带有CategoryTitleView，目前根据Demo中的来实现，但是效果不尽人意，请问能否给一个Demo？？
> 
> 如果可以，请上传到Demo中或者私发我[15570879240@163.com](mailto:15570879240@163.com)，感谢！！！

我也想要实现这样的效果，嵌套悬停，这个你怎么做的
