### ISSUE TITLE
在 ios15 系统上的问题

### ISSUE THREAD

**Issue by 986138497** [pujiaxin33/JXCategoryView#408]
在 ios15 上
plain类型的UITableView增加默认的section高度
    UITableView新增了一个新属性：sectionHeaderTopPadding，默认值为automaticDimension，当我们使用UITableViewStylePlain 初始化tableView的时候，sectionHeaderTopPadding会给section header默认增加高度，解决方案是把sectionHeaderTopPadding属性设置为0即可：

**Comment by 1275053499** [comment]
我刚刚尝试了一下发现并没有解决啊

**Comment by 19aneng** [comment]
亲测有效。2021年10月20日。
JXPagerView.m文件里面初始化tableview的时候添加就可以了

if (@available(iOS 15.0, *)) {
        self.mainTableView.sectionHeaderTopPadding = 0;
    }

**Comment by pujiaxin33** [comment]
JXPagerView最新版本已经修复
