### ISSUE TITLE
ios15 type频繁快速点击ScrollView错乱

### ISSUE THREAD

**Issue by MissTGao** [pujiaxin33/JXCategoryView#409]
如图
![Uploading 39191632909064_.pic.jpg…]()

Uploading 1632909128893612.mp4…

**Comment by MissTGao** [comment]
https://user-images.githubusercontent.com/15083680/135246478-498eb024-09e9-4a7b-ae90-2d758cc8c4be.mp4

**Comment by pujiaxin33** [comment]
你这是iphone mini系统手机吗？
