### ISSUE TITLE
是否可以考虑增加一个获取cellWidth和scrollView.contentOffset.x的delegate

### ISSUE THREAD

**Issue by hstdt** [pujiaxin33/JXCategoryView#41]
目前我使用下面这种方式获取的cellWidth，感觉可以增加一个获取`cellWidth`和`contentOffset`的delegate。(我的应用场景是用CategoryView做表头，通过`cellWidth`绘制表格，然后和通过KVO获取的`scrollView.contentOffset.x`做表格和表头同步滚动的效果😓)。

```
JXCategoryBaseCellModel *model = self.categoryTitleView.dataSource[0];
CGFloat cellWidth = model.cellWidth;
```

**Comment by pujiaxin33** [comment]
- 通过KVO获取scrollView.contentOffset.x不行吗？
- 而且contentScrollView，本身就是你自己创建的，你可以实现它的`scrollViewDidScroll`方法啊
- 然后cellWidth就是数据源的数据，怎么用delegate方法来实现呢？难道你想说的是类似于UITableView的dataSource代理方法？但是CategoryView没有必要用这个啊，代码是要集成在内部的。

**Comment by hstdt** [comment]
@hstdt 
1. 是可以拿到，但是我怕之后如果控件结构调整了，就可能会出问题。
2. 这个没问题，可以自己实现。
3. 这个我说的不对，应该是一个通过index获取cellWidth的方法更好些。

**Comment by pujiaxin33** [comment]
1、版本很稳定了，不会有结构调整了，除非大重构，显然可能性很小了。
3、数据源属性dataSource都暴露出来了，为什么还要通过index获取cellWidth呢？对于后去cellWidth是便利了，但是api却稍显多余。
