### ISSUE TITLE
iOS 15 maintableview 里面 header和 JXCategoryTitleView 之间有一个空隙，怎么去除

### ISSUE THREAD

**Issue by guangyaofaw** [pujiaxin33/JXCategoryView#412]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/91005557/138816889-ea8f858c-dbf1-48a5-9b52-6fefafd5f5bb.png">
如截图，在header和titleview中间有一个间隙，怎么去除呢，求解，谢谢

**Comment by 19aneng** [comment]
ios 15的问题

**Comment by 19aneng** [comment]
https://github.com/pujiaxin33/JXCategoryView/issues/408

**Comment by RiberWang** [comment]
if (@available(iOS 15.0, *)) {
            _tableView.sectionHeaderTopPadding = 0;
        }

**Comment by guangyaofaw** [comment]
fix, thanks!
