### ISSUE TITLE
最新版本demo项目跑不起来？（低版本Xcode报错修复）

### ISSUE THREAD

**Issue by szmichaelyb** [pujiaxin33/JXCategoryView#413]
**bug描述**
### 最新版本项目Example跑不起来？

**版本号**
1.JXCategoryView版本号：1.5.9

**截图、GIF**
![image](https://user-images.githubusercontent.com/9857312/139533047-f6e3a396-4cd3-4aa5-9db4-e2b8b63c6bc3.png)

**Comment by szmichaelyb** [comment]
## 修复低版本Xcode报错问题

![image](https://user-images.githubusercontent.com/9857312/139800944-5a361e2e-5af1-4f3d-bfe1-dc84aaa93141.png)

**Comment by pujiaxin33** [comment]
使用`JXPagingView/Pager`2.1.2版本已经修复
