### ISSUE TITLE
发现有非常严重的内存泄露问题（请务必重视）

### ISSUE THREAD

**Issue by szmichaelyb** [pujiaxin33/JXCategoryView#414]
**bug描述**
测试发现有非常严重的内存泄露问题。请务必重视！

**版本号**
1. JXCategoryView版本号：1.5.9
2. 测试环境：Xcode、模拟器

**复现步骤**
1. 测试发现有非常严重的内存泄露问题。
2. 具体的操作步骤是：控制器点击导航栏“返回”时，控制器controller并未被销毁，并未调delloc函数。

**截图、GIF**

![image](https://user-images.githubusercontent.com/9857312/139566199-a5cc3fbb-9bc2-404b-9bd7-e01d32938c1f.png)

![image](https://user-images.githubusercontent.com/9857312/139566234-046945d5-9eed-435f-99b2-343f1da844f2.png)

![image](https://user-images.githubusercontent.com/9857312/139566248-9c1acfbb-1fea-4602-9ecb-fa5478ef2608.png)

![image](https://user-images.githubusercontent.com/9857312/139566419-2d895509-1f24-4d44-8b75-8adcc18363cc.png)

![image](https://user-images.githubusercontent.com/9857312/139566565-3a6d4535-f1a8-4edc-81ab-a1fdb9526bc4.png)

**Comment by pujiaxin33** [comment]
在最新demo运行项目，并未发现你说的内存泄漏。建议使用最新demo验证。

**Comment by heyimhuman** [comment]
emm 不是dealloc吗。

**Comment by sysworker** [comment]
哈哈哈哈

**Comment by sysworker** [comment]
哈哈哈～～～delloc

**Comment by CoderWeng** [comment]
> 哈哈哈～～～delloc

delloc 是什么 ？

**Comment by Lovezysong** [comment]
我也不知道他这个delloc函数是怎么敲出来的啊~~~，系统没提示吗😂

**Comment by fuchenxi** [comment]
会不会复制粘贴的= =
