### ISSUE TITLE
警告

### ISSUE THREAD

**Issue by lzc1022** [pujiaxin33/JXCategoryView#42]
Unbalanced calls to begin/end appearance transitions for <LoadDataListBaseViewController: 0x7fca2042b8b0>

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复

**Comment by lzc1022** [comment]
![45a1c99f-38ac-4aa4-ad64-1288697561b8](https://user-images.githubusercontent.com/9947322/47889967-8c43b980-de87-11e8-9d6c-ebeabebb896b.png)

如上图 ，重复点击某一个选项   也会打印Unbalanced calls to begin/end appearance transitions ，望修复

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复
