### ISSUE TITLE
titleView如何实现不悬停效果

### ISSUE THREAD

**Issue by wyk190576528** [pujiaxin33/JXCategoryView#421]
初步效果是，上划时，titleView跟随滑动，画出屏幕或划入屏幕；
进一步效果，如演示视频中，在初步效果中，上下滑操作，隐藏或显示titleView
![titleView3](https://user-images.githubusercontent.com/13128838/144535666-a3021cea-2d11-4328-855d-8c1e43145221.gif)

**Comment by wyk190576528** [comment]
效果视频是来自奇乐直播APP

**Comment by pujiaxin33** [comment]
无法实现
