### ISSUE TITLE
JXCategoryTitleImageView中，loadImageBlock回调不起作用

### ISSUE THREAD

**Issue by ahehehehe** [pujiaxin33/JXCategoryView#426]
**bug描述**
JXCategoryTitleImageView中，使用 网络图片+文字模式，loadImageBlock回调不起作用

**版本号**
.JXCategoryView版本号：1.5.9

解决方案：
需要在- (void)refreshCellModel:(JXCategoryBaseCellModel *)cellModel index:(NSInteger)index里，
新增这行代码：myCellModel.loadImageBlock = self.loadImageBlock;

dealloc同时新增self.loadImageBlock = nil;

**Comment by fanyuecheng** [comment]
对的 我也发现了 目前好像只能用旧方法

**Comment by ahehehehe** [comment]
已经收到，谢谢啦！

**Comment by pujiaxin33** [comment]
最新版本会修复该问题。
