### ISSUE TITLE
会多次回调didSelectedItemAtIndex这个方法

### ISSUE THREAD

**Issue by linjiaxing1992** [pujiaxin33/JXCategoryView#43]
如，我JXCategoryTitleView添加了三个标题，也就是三个按钮

第一个和第三个不会多次回调，但是第二个按钮，只要轻轻的拖拽一下（不是直接拖动到其他按钮），就会执行四次代理，

**Comment by pujiaxin33** [comment]
thanks，已修复

**Comment by pujiaxin33** [comment]
谢谢反馈
