### ISSUE TITLE
想要提供加载全部页面的方法

### ISSUE THREAD

**Issue by Tony9527i** [pujiaxin33/JXCategoryView#434]
**Feature描述**
需求1、想要同时加载好所有控制器，因为个别需求只有两三个控制器，想要同时加载效果
需求2、比如我点了第4个tab，前三个自动加载完成

**参考效果**
上边第2个需求，参考百度贴吧首页

感谢作者的分享，十分感谢

**Comment by pujiaxin33** [comment]
可以自己初始化所有的页面，然后在initListAtIndex方法返回已经创建好的对象即可。
