### ISSUE TITLE
最新版demo，刷新数据+列表自定义中，设置默认索引为1时，控制器也是显示第1个，但数据却是加载第0个控制器的。

### ISSUE THREAD

**Issue by 15155969360** [pujiaxin33/JXCategoryView#435]
最新版demo，刷新数据+列表自定义中，设置默认索引为1时，控制器也是显示第1个，但数据却是加载第0个控制器的。
self.categoryView.defaultSelectedIndex = 1;
JXCategoryView最新版。

**Comment by CoderLGL** [comment]
遇到同样的问题
