### ISSUE TITLE
顶部有多余的空隙

### ISSUE THREAD

**Issue by guangyaofaw** [pujiaxin33/JXCategoryView#438]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/91005557/165661224-cb67e08b-1389-4ec6-8e44-0163df8fa156.png">

**Comment by guangyaofaw** [comment]
15.0级以上 顶部有多余的空隙，别的版本没有，怎么解决一下，谢谢

**Comment by lefengxu** [comment]
> 
设置一下sectionHeaderTopPadding = 0

**Comment by pujiaxin33** [comment]
目前设置`_pagingView.mainTableView.sectionHeaderTopPadding = 0;`，后续会更新JXPagingView来解决。
