### ISSUE TITLE
是否考虑下生命周期的问题

### ISSUE THREAD

**Issue by linjiaxing1992** [pujiaxin33/JXCategoryView#44]
我发现 创建页面的时候，是一次性全部创建，所有的控制器都先执行了ViewDidLoad,和ViewWillAppear的方法

如果一次性创建多个控制器，会不会对性能有所影响？

**Comment by linjiaxing1992** [comment]
之前有用过XLPagerTabStrip，他的方法是当滑动到该控制器，才会去执行ViewDidLoad的方法

不知这两种方法各有什么优势

**Comment by pujiaxin33** [comment]
谢谢你的提问：
1、“如果一次性创建多个控制器，会不会对性能有所影响？”
我的建议是不要在viewDidLoad里面做数据加载，我的示例代码是移动到`loadDataForFirst`方法里面，就是滚动视图将要出现的时候调用，属于延迟加载。如果vc的视图较复杂，视图创建也建议移动到这个方法里面。所以最开始创建的vc，就只是一个空壳vc，不会有太多性能消耗。
2、“之前有用过XLPagerTabStrip，他的方法是当滑动到该控制器，才会去执行ViewDidLoad的方法”
我的示例也只是一个建议而已，每个方案都有优缺点。如果我的方案出现了性能问题，我会考虑研究一下XLPagerTabStrip的方案。

**Comment by pujiaxin33** [comment]
感谢你的提问，经过时间的考验，发现确实需要延迟加载列表。
在1.1.7版本加入了`JXCategoryListContainerView`类，支持以下特性：
- 高度封装contentScrollView逻辑，只需少量代码即可完成列表容器逻辑；
- 列表懒加载，当通过滚动、点击选中显示某个列表的时候，才进行列表初始化，性能更优；

[JXCategoryListContainerView的详细使用说明](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/JXCategoryListContainerView%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)
