### ISSUE TITLE
imageInfoArray和selectedImageInfoArray属性的使用问题

### ISSUE THREAD

**Issue by 295060456** [pujiaxin33/JXCategoryView#442]
因为文档指示：下面的属性将会被弃用，请使用`imageInfoArray`、`selectedImageInfoArray`、`loadImageBlock`属性完成需求。
但是我搜索Demo，也没看到使用的过程
![image](https://user-images.githubusercontent.com/13795605/168535608-b9193b3e-ed33-4294-805f-903737475e7f.png)
![image](https://user-images.githubusercontent.com/13795605/168535655-9ba2d87e-7af4-4ef1-a994-acc00dfe7f28.png)
可以看到搜索出来3个文件，其中2个位于h文件，一个位于JXCategoryTitleImageView内部

所以对于@property (nonatomic, copy) void(^loadImageBlock)(UIImageView *imageView, id info);的使用我需要demo示例

**Comment by sysworker** [comment]
是的，确实有这个问题，具体因为没有设置回调导致的，
具体在这个方法里面设置，和loadImageCallback 一样，赋值一下
`- (void)refreshCellModel:(JXCategoryBaseCellModel *)cellModel index:(NSInteger)index`

**Comment by pujiaxin33** [comment]
感谢反馈，已经修复并更新了示例。
