### ISSUE TITLE
能否增加title文字的水平居中显示设置?

### ISSUE THREAD

**Issue by FzyJanm** [pujiaxin33/JXCategoryView#443]
title文字分类少的时候2个或者三个的时候无法居中显示,有没有一个设置,能让title文字居中排版的?

**Comment by pujiaxin33** [comment]
并没有，你可以自己计算categoryView内容的宽度，然后用（屏幕宽度-categoryView内容的宽度）/2，得到的值赋值给contentEdgeInsetLeft，就能实现类似的居中效果。
