### ISSUE TITLE
JXCategoryIndicatorView 的 indicators 能给不同cell 添加不同的效果吗?? 或者追加一个新属性

### ISSUE THREAD

**Issue by damu-mu** [pujiaxin33/JXCategoryView#444]
**Feature描述**
`@property (nonatomic, strong) NSArray <UIView<JXCategoryIndicatorProtocol> *> *indicators;`
能支持 不同的 `JXCategoryTitleView` 的Cell 使用不同的指示器吗??  特别是 `JXCategoryIndicatorImageView` 这中图片指示器, 因为  `JXCategoryTitleView` 的内容宽度不同, 导致 `JXCategoryIndicatorImageView` 所使用的 图片 大小也不一致

**Comment by pujiaxin33** [comment]
`@property (nonatomic, strong) NSArray <UIView<JXCategoryIndicatorProtocol> *> *indicators;`
这里的indicator是要左右滑动的。你想要的效果可以参考`TitleBackgroundExampleViewController`示例类，给cell添加背景内容。
