### ISSUE TITLE
悬浮如何自定义类似下面的悬浮cell，类似下面两种的

### ISSUE THREAD

**Issue by Liyongcong** [pujiaxin33/JXCategoryView#445]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？
![WechatIMG16](https://user-images.githubusercontent.com/13864468/170913725-118ba1bc-f4d6-49cd-bb92-b699bf6f6c08.jpeg)

**其他补充**
关于目标效果的其他说明：？

**Comment by Liyongcong** [comment]
![WechatIMG21](https://user-images.githubusercontent.com/13864468/170932564-9f4cd0d4-2745-461a-a7e3-17c55122349a.jpeg)

**Comment by pujiaxin33** [comment]
categoryView下面悬浮的选择栏视图，应该是每一个listView自己的header。你参考这个思路实现呢?

**Comment by Liyongcong** [comment]
> 

你意思是自定义一个header吗

**Comment by Lovezysong** [comment]
> 因为不知道具体的效果，如果左右滑动标签也跟着滑动，那么就是作者的那个意思（悬浮的标签应该不是在Pager的header上而是在每个控制器列表的悬浮header上，例如加在UICollectionReusableView上）如果标签不更随页面左右切换，那就自定义header，然后动态更新header的高度

**Comment by Lovezysong** [comment]
> 因为不知道具体的效果，如果左右滑动标签也跟着滑动，那么就是作者的那个意思（悬浮的标签应该不是在Pager的header上而是在每个控制器列表的悬浮header上，例如加在UICollectionReusableView上）如果标签不更随页面左右切换，那就自定义header，然后动态更新header的高度

**Comment by Liyongcong** [comment]
> 因为不知道具体的效果，如果左右滑动标签也跟着滑动，那么就是作者的那个意思（悬浮的标签应该不是在Pager的header上而是在每个控制器列表的悬浮header上，例如加在UICollectionReusableView上）如果标签不更随页面左右切换，那就自定义header，然后动态更新header的高度

https://user-images.githubusercontent.com/13864468/184264749-509b5848-1805-467f-9726-ca4f4f9bc43d.mp4

要实现这样的一个效果
