### ISSUE TITLE
title没有！！！

### ISSUE THREAD

**Issue by 295060456** [pujiaxin33/JXCategoryView#447]
**bug描述**
请简单描述你的bug现象：
我划了红线的这句话打开，就没有标题，不知道什么原因，望作者辅助排查
下面我将提交一个文件👇🏻供你检查

**版本号**
1.JXCategoryView版本号：最新版本
2.手机系统版本号：最新系统
3.手机型号：模拟器以及真机

**截图、GIF**
![image](https://user-images.githubusercontent.com/13795605/171586970-9ac056d6-ce3f-468f-b612-0b58a3909661.png)
![image](https://user-images.githubusercontent.com/13795605/171587144-04c13e6f-3499-4da9-a40b-d312235e836e.png)
![image](https://user-images.githubusercontent.com/13795605/171587303-5a0143df-4bf9-4fe6-a4da-50f631ebed51.png)
![image](https://user-images.githubusercontent.com/13795605/171587380-b3201549-3fc4-439c-8694-5652888fc74d.png)
[归档.zip](https://github.com/pujiaxin33/JXCategoryView/files/8822063/default.zip)
👆🏻，一些不重要的地方，涉及到引用，作者自行处理，我这里就只呈现核心问题。

**Comment by pujiaxin33** [comment]
无法复现，能够放一个可以复习的demo呢？
