### ISSUE TITLE
如果我要实现类似于这个界面，我应该怎么做呢？

### ISSUE THREAD

**Issue by 295060456** [pujiaxin33/JXCategoryView#448]
![image](https://user-images.githubusercontent.com/13795605/173566536-54828b26-6da0-44f7-a1c6-e1d3e4a9d832.png)

**Comment by 295060456** [comment]
目前我只能想到这个方案：
-(void)transformByRadians:(CGFloat)radians{
    self.transform = CGAffineTransformMakeRotation(M_PI * radians);
    // 使用:例如逆时针旋转40度
    // [setTransform:40/180 forLable:label]
}

**Comment by 295060456** [comment]
1、不用JXCategory我知道怎么做；
2、我就想偷懒+探究到底JXCategory存在与否这个可能性去实现它；

结论：不行🚫

原因：
1、所有的自定义操作都是集中于@interface JXCategoryBaseView : UIView里面的@property (nonatomic, strong, readonly) JXCategoryCollectionView *collectionView;
但是我拿cell很不方便，众所周知，只能在-(void)viewDidAppear:(BOOL)animated里面才可以拿到cell
不管你是
//    JXCategoryBaseCell *cell = (JXCategoryBaseCell *)[self.categoryView.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:2 inSection:0]];
//
//    id dd = self.categoryView.categoryBaseCellMutArr;

都只能在-(void)viewDidAppear:(BOOL)animated才会有值。
拿不到Cell就做不了事情

我的原定计划是直接套用JXCategory框架，然后进行view的旋转，事实上也是可以，算坐标比较头疼，这里的旋转就等于左右互换，宽高互换，这都不是重点，重点是：-(void)viewDidAppear:(BOOL)animated这个方法要顿一秒左右，有个肉眼可见的旋转过程，这肯定不行！！！

我在：https://github.com/295060456/JobsBaseConfig里面有demo，有兴趣你们download下来研究
![image](https://user-images.githubusercontent.com/13795605/173736091-a2f7b68d-a498-4640-8416-8a849de38e93.png)
为此我还专门开辟了另外一个问题：
![telegram-cloud-photo-size-5-6143095555035869112-y](https://user-images.githubusercontent.com/13795605/173736268-4f02f799-170a-40c9-a465-5fbd0ae127c9.jpg)

还是那句话，拿不到cell 一切完蛋。只能从根上去寻求突破。

**Comment by 295060456** [comment]
写完了：
https://github.com/295060456/JobsBaseConfig
![image](https://user-images.githubusercontent.com/13795605/173829513-75a92fa3-31f7-4252-bbf9-67b4055172ff.png)
https://user-images.githubusercontent.com/13795605/173829545-0be24ec4-30d6-494b-b18f-8a0f85ccfaef.mp4

**Comment by Liyongcong** [comment]
你好，想咨询下，我们这种效果，用它这个怎么实现

https://user-images.githubusercontent.com/13864468/174049267-cf074abc-cf9c-4535-9423-2fadd0989baf.mp4

**Comment by 295060456** [comment]
> 你好，想咨询下，我们这种效果，用它这个怎么实现
> 
>  1655286665603335.mp4

就是一个嵌套啊！他的demo里面有啊

**Comment by Liyongcong** [comment]
(上面可以控制下面的改变，下面也能控制上面的改变)
他这个就是点击上面的北京市，关注，全国下面的东西不变，点击下面的查找附近的人，导航栏上面的数据变，然后，点击相册和发布底部的发现和查找附近的人变成编辑和预览，点击查看时，在变成发现和查找附近的人

**Comment by Liyongcong** [comment]
用他那个没有具体的思路，能指点下么

**Comment by pujiaxin33** [comment]
@295060456 不支持你想要的效果
