### ISSUE TITLE
特殊效果里面->垂直滚动缩放效果，怎么实现我录制的视频这种效果，上面标题是变化的

### ISSUE THREAD

**Issue by Liyongcong** [pujiaxin33/JXCategoryView#449]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

https://user-images.githubusercontent.com/13864468/174048215-0ce50fea-6bea-4cef-bc1c-140d4bb67577.mp4

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
看视频，没有用到垂直缩放的效果呢？应该参考嵌套使用示例。
