### ISSUE TITLE
调用didSelectedItemAtIndex还有一个小问题

### ISSUE THREAD

**Issue by linjiaxing1992** [pujiaxin33/JXCategoryView#45]
https://picture-1257939908.cos.ap-shanghai.myqcloud.com/QQ20181102-093425.gif

左右两测的按钮轻微滑动不会调用，中间按钮只要有滑动到，松开就会再次调用。

不知道是不是本设计如此嘛？

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复
