### ISSUE TITLE
类似BOSS直聘带标签的切换的效果

### ISSUE THREAD

**Issue by Tony9527i** [pujiaxin33/JXCategoryView#452]
作者您好，类似BOSS直聘带标签的切换的效果，标签跟随标题缩放

参考APP名字：BOSS直聘

效果视频如下：

https://user-images.githubusercontent.com/13429875/176638308-80a89e42-e8eb-4fd7-8cd6-335c7c355a4e.mp4

**Comment by 986138497** [comment]
> 作者您好，类似BOSS直聘带标签的切换的效果，标签跟随标题缩放
> 
> 参考APP名字：BOSS直聘
> 
> 效果视频如下：
> 
>  1656579874533335.mp4

demo 自己下载看, 有缩放效果

**Comment by pujiaxin33** [comment]
主标题缩放效果已经支持了。只是右上角的标题你可以参考numberView去自定义实现。就是把现有numberLabel的样式给修改一下。
