### ISSUE TITLE
titleSelectedColor 没有起作用

### ISSUE THREAD

**Issue by LAnqxpp** [pujiaxin33/JXCategoryView#458]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
设置主题颜色，没有变化
NaviSegmentedControlViewController
**版本号**
1.JXCategoryView版本号：1.5.9 
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
修改64行代码如下  发现这样修改不起做
  JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
    lineView.indicatorColor = [UIColor colorWithHexString:@"#FF1A9A"];
    lineView.indicatorWidth = 28;
    lineView.indicatorHeight = 2;
    self.myCategoryView.indicators = @[lineView];

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by Lovezysong** [comment]
你没进对控制器吧？你在NaviSegmentedControlViewController里设置，运行的时候点的是“导航栏使用”吗？

**Comment by Lovezysong** [comment]
titleLabelMaskEnabled与JXCategoryIndicatorBackgroundView是配合使用的，只使用JXCategoryIndicatorLineView就应当把titleLabelMaskEnabled设置为NO

**Comment by LAnqxpp** [comment]
> titleLabelMaskEnabled与JXCategoryIndicatorBackgroundView是配合使用的，只使用JXCategoryIndicatorLineView就应当把titleLabelMaskEnabled设置为NO

感谢，改好了
