### ISSUE TITLE
请问大神，此库中有没有方法实现我上传的视频那样的效果？

### ISSUE THREAD

**Issue by heliang219** [pujiaxin33/JXCategoryView#459]
**Feature描述**
请简单描述你想要的效果：如上传的视频推荐栏目那样的效果

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：今日头条
2.目标页面路径：
3.目标效果截图：如视频所示，像推荐栏目那样的效果

**其他补充**
关于目标效果的其他说明：

https://user-images.githubusercontent.com/795426/186121497-82aef094-c80d-4969-a695-67a1e1f0d681.mp4

**Comment by Lovezysong** [comment]
今日头条这个“推荐”就是另写了一个按钮盖在菜单上，滚动时计算下偏移然后动态隐藏与显示而已，只不过看起来像悬浮一样

**Comment by pujiaxin33** [comment]
> 今日头条这个“推荐”就是另写了一个按钮盖在菜单上，滚动时计算下偏移然后动态隐藏与显示而已，只不过看起来像悬浮一样

请参考该思路自定义实现。
