### ISSUE TITLE
JXCategoryTitleView支持左对齐

### ISSUE THREAD

**Issue by tipshot** [pujiaxin33/JXCategoryView#461]
**Feature描述**
JXCategoryTitleView 希望支持左/右对齐效果，当CategoryTitleView  选项卡内容不能满足填充屏幕宽度时候，当前是值全屏宽度平分。不能选择左对齐或者有对齐。

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：数字心动  
2.目标页面路径：运动页
3.目标效果截图： 
![image](https://user-images.githubusercontent.com/18547353/187584649-78aa328f-c4c8-49b6-bb3d-cb6ed8d51b8d.png)

**其他补充**
关于目标效果的其他说明：其实想要目标效果为，支持可以左右对齐。

**Comment by Liyongcong** [comment]
设置self.categoryView.averageCellSpacingEnabled = NO;

**Comment by tipshot** [comment]
GET！！！
