### ISSUE TITLE
期望 CZCategoryTitleView支持 访问cell 内控件

### ISSUE THREAD

**Issue by tipshot** [pujiaxin33/JXCategoryView#462]
[**Feature描述**
期望 CZCategoryTitleView支持 访问cell 内控件，以方便对控件（如imageView）进行直接赋值，当前情况下，如果是私有库使用，是无法对图片进行赋值的，因为在私有库内，无法直接通过[UIImage inageNamed]进行赋值图片，无法访问私有库bundle资源。还望支持。

**Comment by pujiaxin33** [comment]
目前都是通过datasource驱动的，没有办法范围cell中的imageView。
