### ISSUE TITLE
延迟赋值以及初始化，会发出警告

### ISSUE THREAD

**Issue by cheng-ren** [pujiaxin33/JXCategoryView#469]
**bug描述**
弹出异常警告，

**版本号**
1.JXCategoryView版本号： 最新版本Demo
2.手机系统版本号：所有版本
3.手机型号：所有型号

**复现步骤**
1. 遇到问题的相关效果、类是：TitleViewController
2.具体的操作步骤是：

将TitleViewController的init和viewDidload改成如下形式，会报出警告。
Unbalanced calls to begin/end appearance transitions for <ListViewController: 0x7fb45fc22570>.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/21993578/200995013-35c3e69d-2217-4594-96e1-2468c42eca42.png">

**Comment by lookingforfanyunfei** [comment]
重写这两个方法，什么也不做

- (void)beginAppearanceTransition:(BOOL)isAppearing animated:(BOOL)animated {
}

- (void)endAppearanceTransition {
}

**Comment by lookingforfanyunfei** [comment]
> **bug描述** 弹出异常警告，
> 
> **版本号** 1.JXCategoryView版本号： 最新版本Demo 2.手机系统版本号：所有版本 3.手机型号：所有型号
> 
> **复现步骤**
> 
> 1. 遇到问题的相关效果、类是：TitleViewController
>    2.具体的操作步骤是：
> 
> 将TitleViewController的init和viewDidload改成如下形式，会报出警告。 Unbalanced calls to begin/end appearance transitions for <ListViewController: 0x7fb45fc22570>.
> 
> <img alt="image" width="882" src="https://user-images.githubusercontent.com/21993578/200995013-35c3e69d-2217-4594-96e1-2468c42eca42.png">

重写这两个方法，什么也不做

(void)beginAppearanceTransition:(BOOL)isAppearing animated:(BOOL)animated {
}

(void)endAppearanceTransition {
}
