### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by tongwanming** [pujiaxin33/JXCategoryView#476]
![1677638904892](https://user-images.githubusercontent.com/11530256/222032343-21111ea2-674b-4a3b-928c-f125ad750d77.jpg)
大神 能实现截图中的功能么

**Comment by lumianie** [comment]
你这个是标签视图，不是一个功能

**Comment by pujiaxin33** [comment]
是的，你截图中的功能和category view 提供的功能不一样。
