### ISSUE TITLE
点击JXCategoryTitleView的item选项时，不走listContainerView:initListForIndex:代理方法

### ISSUE THREAD

**Issue by 13923927013** [pujiaxin33/JXCategoryView#479]
JXCategoryTitleView有两个titleItem，进入页面时默认选中第一个item，对应第一个列表会加载。但是，当点击第二个titleItem时，却不会走listContainerView:initListForIndex:代理方法，而通过滑动到第二个titleItem时却会走这个代理方法。

经排查问题如下图：
![image](https://user-images.githubusercontent.com/23549473/231049302-4cde1283-f953-4d89-b800-e31759f28d01.png)

**Comment by ExchangeMe** [comment]
+1 我也遇到了

**Comment by xiaowei-dreame** [comment]
![image](https://github.com/user-attachments/assets/0cd6bf27-bf30-4a2b-b08e-a4d3f95f6057)
使用 contentScrollView 会有这个问题吧？
