### ISSUE TITLE
使用了RTL布局，JXCategoryTitleCell的蒙版会有显示Bug

### ISSUE THREAD

**Issue by Rogue24** [pujiaxin33/JXCategoryView#484]
如图所示：
![81688115167_ pic](https://github.com/pujiaxin33/JXCategoryView/assets/13127665/1d2cbde5-f56e-4635-95cb-b4cec5e665ef)

需要对蒙版的x值做镜像处理，修正后：
![91688115168_ pic](https://github.com/pujiaxin33/JXCategoryView/assets/13127665/e91b0110-d59d-43e0-aa7c-5e3c881dcc6d)

已PR，望采纳：https://github.com/pujiaxin33/JXCategoryView/pull/483

**Comment by pujiaxin33** [comment]
非常感谢！已merge！
