### ISSUE TITLE
1.6.1的Demo运行报错

### ISSUE THREAD

**Issue by shengxianghong** [pujiaxin33/JXCategoryView#496]
Xcode14.2 ，1.6.1的demo运行报错，提示pod里边少文件是红的,1.6.0是可以运行的。
Example/Pods/Target Support Files这里会比原来多俩文件。

**Comment by asd26187** [comment]
我的也运行不起来，pod install报错 
[!] No podspec found for `JXCategoryView` in `../../JXCategoryView`

**Comment by pujiaxin33** [comment]
可以尝试在example目录下执行`pod install`之后，再运行demo。
