### ISSUE TITLE
希望增加一个可以刷新角标的方法

### ISSUE THREAD

**Issue by steed9200** [pujiaxin33/JXCategoryView#497]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
可以提交PR进行支持。
