### ISSUE TITLE
 关于切换动画

### ISSUE THREAD

**Issue by hweibo** [pujiaxin33/JXCategoryView#5]
因为公司设计师也是参照闲鱼出的设计图，然后我发现闲鱼点击bar切换的时候scrollview没有明显的滚动动画，体验会好一点点

**Comment by pujiaxin33** [comment]
你能加入QQ群：112440151，发一下具体截图，并指明位置吗？

**Comment by pujiaxin33** [comment]
麻烦在QQ群告知，issue先关闭了
