### ISSUE TITLE
如果不允许滚动，只能点击该怎么做

### ISSUE THREAD

**Issue by lzc1022** [pujiaxin33/JXCategoryView#50]

**Comment by pujiaxin33** [comment]
1、你把contentScrollView的scrollEnable设置为false；
2、不赋值contentScrollView，然后在点击回调的代理方法里面，设置contentScrollView的contentOffset.x.

**Comment by lzc1022** [comment]
能不能暴露出来一个属性设置

**Comment by pujiaxin33** [comment]
都已经暴露给你，配置一下即可。

**Comment by WangGuibin** [comment]
I got it
