### ISSUE TITLE
如何只支持点击切换栏目，禁止左右滑动来切换

### ISSUE THREAD

**Issue by blooming2017** [pujiaxin33/JXCategoryView#501]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by soober** [comment]
+1

**Comment by melo30** [comment]
self.listContainerView.scroll.scrollEnabled = NO;

**Comment by pujiaxin33** [comment]
> self.listContainerView.scroll.scrollEnabled = NO;

请参考。
