### ISSUE TITLE
有1.5.0之后的版本更新说明么?

### ISSUE THREAD

**Issue by sheep-mie-mie** [pujiaxin33/JXCategoryView#502]
**bug描述**
我在嵌套使用JXCategoryView时, 添加了一个折叠视图, 用直接下载的Demo配置运行时没有问题, 但是到自己项目中出现问题, 把Demo中的案例复制到项目中依然存在, 然后把Demo中的JXCategoryView版本升级到1.5.9-1.6.1的版本是同样复现了问题, 然后指定1.5.5版本该问题消失.
1.使用的是隐藏导航栏+嵌套模式
2.在嵌套JXCategoryView中添加了一个折叠视图, 当页面滑动到安全距离位置是修改折叠视图的frame, 然后遍历`self.listContainerView.validListDict.allValues`, 改变frame `UIView *listView = [list listView];
        listView.frame = CGRectMake(0, 0, self.listContainerView.frame.size.width, self.listContainerView.frame.size.height);`
使用1.5.5版本显示没有问题, 使用1.6.1版本时, tableview的frame显示会缩小折叠视图缩小的大小, 手动修改frame也不生效

**版本号**
1.JXCategoryView版本号：1.6.1

**复现步骤** 使用1.5.5版本和1.6.1版本会产生不同效果
[PagingNestCategoryListViewController_h.txt](https://github.com/pujiaxin33/JXCategoryView/files/14429986/PagingNestCategoryListViewController_h.txt)

**截图、GIF**
提供bug出现时的截图或者GIF。 
图2是使用1.5.5版本我想要的效果, 图3是1.6.1版本修改折叠视图后tableview的frame就和listContainerView的frame不一致了
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-28 at 14 41 47](https://github.com/pujiaxin33/JXCategoryView/assets/17465895/609602d9-18da-4b33-84d7-8360178d8e07)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-28 at 14 41 52](https://github.com/pujiaxin33/JXCategoryView/assets/17465895/79a4335a-2ac0-40fb-9d9c-575652db3743)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-28 at 14 43 20](https://github.com/pujiaxin33/JXCategoryView/assets/17465895/43787037-3471-426e-aa05-15dd6a776ee6)
以下是我在Demo中修改的案例, 使用1.5.5版本和1.6.1版本会出现不同效果
[PagingNestCategoryListViewController_m.txt](https://github.com/pujiaxin33/JXCategoryView/files/14429987/PagingNestCategoryListViewController_m.txt)
[PagingNestCategoryViewController_h.txt](https://github.com/pujiaxin33/JXCategoryView/files/14429988/PagingNestCategoryViewController_h.txt)
[PagingNestCategoryViewController_m.txt](https://github.com/pujiaxin33/JXCategoryView/files/14429990/PagingNestCategoryViewController_m.txt)
[TestNestListViewController_h.txt](https://github.com/pujiaxin33/JXCategoryView/files/14429992/TestNestListViewController_h.txt)
[TestNestListViewController_m.txt](https://github.com/pujiaxin33/JXCategoryView/files/14429993/TestNestListViewController_m.txt)

**Comment by pujiaxin33** [comment]
只能去看git commit记录了，但是我无法定位是那个commit导致的差异，如果老版本可用，建议先用老版本。
