### ISSUE TITLE
列表左右滑动存在Bug!会导致UIViewController生命周期错误!!!

### ISSUE THREAD

**Issue by Arthas-cn** [pujiaxin33/JXCategoryView#505]
**bug描述**
列表左右滑动存在Bug!会导致UIViewController生命周期错误!

**版本号**
1.JXCategoryView版本号：1.6.3
2.手机系统版本号：any
3.手机型号：any

**复现步骤**
遇到问题的相关效果、类是：
1.有一个UIViewController作为父容器称作ContainerA，父容器ContainerA有三个子视图UIViewController，B、C、D。

2.先选中中间视图C，然后稍微向右滑动(露出B视图，JXCategoryListContainerView)，再松手（还是显示C视图），B执行了viewWillAppear，C执行了viewWillDisappear。没有执行后续操作了，会导致子视图的生命UIViewController周期执行不正确；

3.正确行为应该是，当再松手（还是显示C视图）时，B要执行一次UIViewController生命周期消失的操作（viewWillDisappear、viewDidDisappear），C要执行一次UIViewController生命周期出现的操作（viewWillAppear、viewDidAppear）

**截图、GIF**
无

**Comment by pujiaxin33** [comment]
可以上传一个demo吗？
