### ISSUE TITLE
 categoryView 是否可以隐藏

### ISSUE THREAD

**Issue by tipshot** [pujiaxin33/JXCategoryView#508]
categoryView 是否可以隐藏？
设置了categoryView.isHidden = true 不起作用，是无法设置隐藏，还是需要使用其他的方法？

**Comment by pujiaxin33** [comment]
可以隐藏categoryView 是 UIView的子视图，你可以把它当做普通的UIView对待。categoryView.isHidden = true 是可以隐藏的，建议检查其他代码。或者设置alpha = 0
