### ISSUE TITLE
当设置未选中和选中字体不一致且选中标签title过长显示有问题

### ISSUE THREAD

**Issue by wxw962530118** [pujiaxin33/JXCategoryView#509]
**bug描述**
当设置普通和未选中字体不一致且选中标签title过长显示有问题

**版本号**
1.JXCategoryView版本号：1.6.3
2.手机系统版本号：17.4
3.手机型号：iPhone15 Pro

**复现步骤**
1. 使用的类是：JXCategoryTitleView
2.具体的操作步骤：使用的官方Demo，只是把titleFont和titleSelectedFont分别设置成[UIFont systemFontOfSize:14]和[UIFont systemFontOfSize:18 weight:UIFontWeightBold]就会出现截图所示问题，看了一下源码，计算cell宽度的时候用的是titleFont而并不是titleSelectedFont

**截图**
![Simulator Screenshot - iPhone 15 Pro - 2024-04-23 at 11 10 41](https://github.com/pujiaxin33/JXCategoryView/assets/19562349/5b29bbda-899b-4ae4-a7ef-0e126f4447cc)

**Comment by pujiaxin33** [comment]
可以参考【大小缩放+Cell宽度缩放】示例，同步把cell大小也给变大。
JXCategoryTitleView *titleCategoryView = (JXCategoryTitleView *)testVC.categoryView;
        titleCategoryView.titleColorGradientEnabled = YES;
        titleCategoryView.titleLabelZoomEnabled = YES;
        titleCategoryView.titleLabelZoomScale = 1.3;
        titleCategoryView.titleLabelStrokeWidthEnabled = YES;
        titleCategoryView.selectedAnimationEnabled = YES;
        titleCategoryView.cellWidthZoomEnabled = YES;
        titleCategoryView.cellWidthZoomScale = 1.3;

**Comment by wxw962530118** [comment]
按照示例代码发现新的问题，就是在文字比较长的的时候，cell整体宽度会比label的实际宽度多出很多，具体可以看下截图（复现的🌹只需要将标题文字改长一点即可）
<img width="462" alt="Snipaste_2024-07-11_11-24-17" src="https://github.com/pujiaxin33/JXCategoryView/assets/19562349/8882255d-939c-4e0e-9b98-1e8293e1fe87">
<img width="465" alt="Snipaste_2024-07-11_11-24-48" src="https://github.com/pujiaxin33/JXCategoryView/assets/19562349/49e47681-39cd-4794-8e0f-5ad85ef97934">
