### ISSUE TITLE
你好  能否修改下子控制器显示时再加载  目前您的机制是一次性加载所有的控制器

### ISSUE THREAD

**Issue by xuhuaping** [pujiaxin33/JXCategoryView#51]

**Comment by pujiaxin33** [comment]
请参考：
[关于视图全部加载问题#25](https://github.com/pujiaxin33/JXCategoryView/issues/25)
[是否考虑下生命周期的问题 #44](https://github.com/pujiaxin33/JXCategoryView/issues/44)

再补充一点，我目前的vc加载机制，只是我目前的用法建议，你可以自己修改为显示时再加载，因为ContentSCrollView这一块逻辑，完全是你可以自定义的

**Comment by pujiaxin33** [comment]
@xuhuaping 新包里面新增列表懒加载LazyLoadViewController示例，里面的实现原理就是，显示的时候才加载。
如果需要的话，可以参照里面的代码。
最后重申一下，列表如何加载完全由你控制，所有的方案都只是参考。

**Comment by pujiaxin33** [comment]
感谢你的提问，经过时间的考验，发现确实需要延迟加载列表。
在1.1.7版本加入了`JXCategoryListContainerView`类，支持以下特性：
- 高度封装contentScrollView逻辑，只需少量代码即可完成列表容器逻辑；
- 列表懒加载，当通过滚动、点击选中显示某个列表的时候，才进行列表初始化，性能更优；

[JXCategoryListContainerView的详细使用说明](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/JXCategoryListContainerView%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)
