### ISSUE TITLE
didSelectedItemAtIndex代理方法不触发

### ISSUE THREAD

**Issue by losedMemory** [pujiaxin33/JXCategoryView#510]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
当我设置
```    
self.categoryView.frame = CGRectMake(0, 0, self.view.bounds.size.width * 0.7, [self preferredCategoryViewHeight]);
self.listContainerView.frame = CGRectMake(0, [self preferredCategoryViewHeight], self.view.bounds.size.width * 0.7, self.view.bounds.size.height);
```
第一次滑动页面时`categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex`代理方法没有触发

**版本号**
1.JXCategoryView版本号：1.6.3
2.手机系统版本号：17.2
3.手机型号：iPhone 15

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
建议参考demo来布局页面，就不会出现这个问题。如果依然有问题，可以提供一个可以复现问题的demo link吗？

**Comment by losedMemory** [comment]
[JXCategoryView-master.zip](https://github.com/pujiaxin33/JXCategoryView/files/15360439/JXCategoryView-master.zip)
我直接下载的demo，JXCategoryView的版本是1.6.3 ，然后在`ContentBaseViewController`类中将宽度改成self.view.bounds.size.width * 0.7， 第一次滑动就不会触发代理方法
