### ISSUE TITLE
滑动闪屏 

### ISSUE THREAD

**Issue by yangfangxue** [pujiaxin33/JXCategoryView#513]
![output](https://github.com/pujiaxin33/JXCategoryView/assets/16777241/0ca4e013-25f0-4795-8035-7fe8e2945f3f)

**Comment by yangfangxue** [comment]
划上去之后就划不下来了

**Comment by pujiaxin33** [comment]
你这是使用JXPagingView库吗？如果是，请参考JXPagingView配置好list view的滚动处理。
