### ISSUE TITLE
选中回调中，直接调用[categoryView selectItemAtIndex:3]导致下滑线对应不上

### ISSUE THREAD

**Issue by lzqok** [pujiaxin33/JXCategoryView#514]
**bug描述**  
在选中回调didSelectedItemAtIndex 方法中直接调用[categoryView selectItemAtIndex:3];选中下滑线对应不上选中item，通过源码分析在JXCategoryIndicatorView中先调用了父类选中方法。
![IMG_4418](https://github.com/pujiaxin33/JXCategoryView/assets/3359828/b9cd4245-03d7-4cb2-abe3-8f0da5029317)

**业务描述**  
某个选项需要登录才能展示，如果当前没有登录，选中需要回退到上一个选中项目

**版本号**
1.JXCategoryView版本号:  1.6.3
2.手机系统版本号：
3.手机型号：

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryIndicatorView,JXCategoryBaseView
2.具体的操作步骤是：选中回调中调用[categoryView selectItemAtIndex:3]

**Comment by pujiaxin33** [comment]
建议加上一个延迟再调用[categoryView selectItemAtIndex:3]
