### ISSUE TITLE
1.1.3版本的有循环引用

### ISSUE THREAD

**Issue by daizim** [pujiaxin33/JXCategoryView#58]

**Comment by pujiaxin33** [comment]
我用Xcode的View Memory Graph Hierarchy工具，并没有看到循环引用。你能指明哪里有循环引用吗？

**Comment by snilwx** [comment]
我也出现了循环引用，APP直接崩溃了

**Comment by pujiaxin33** [comment]
循环引用也不至于崩溃啊，有崩溃截图吗

**Comment by pujiaxin33** [comment]
直接把截图粘贴到输入框，等它自己上传就行

**Comment by pujiaxin33** [comment]
直接用我的demo可以复现吗？具体的设备型号和系统版本呢？

**Comment by pujiaxin33** [comment]
@snilwx 能看下你在OrderController的- (void)categoryView:(JXCategoryBaseView *)categoryView didScrollSelectedItemAtIndex:(NSInteger)index方法里面，调用了什么代码么？

**Comment by pujiaxin33** [comment]
不要在categoryView的选中回调里面，再调用selectItemWithIndex方法。
