### ISSUE TITLE
JXCategoryIndicatorImageView 指示器图片如何与cell等宽

### ISSUE THREAD

**Issue by feihuang89** [pujiaxin33/JXCategoryView#59]
你好，目前我在切换item的时候修改指示器宽度，会导致指示器的动画异常，从0滑动出现，有好的解决方案嘛

**Comment by pujiaxin33** [comment]
JXCategoryIndicatorImageView目前无法与cell等宽，什么样的设计会让JXCategoryIndicatorImageView与cell等宽呢？

**Comment by pujiaxin33** [comment]
“切换item的时候修改指示器宽度”，指示器线默认是与cell等宽的，为什么需要点击的时候修改指示器宽度呢？能贴一下代码么？

**Comment by feihuang89** [comment]
![image](https://user-images.githubusercontent.com/14228319/49570933-e77b3700-f972-11e8-98b1-6a5e5dfde36f.png)
类似这样的分栏切换，宽度不一致，点击放大，我设置了cell宽度缩放，所以IndicatorImageView宽度需要跟随着修改，代码如下：
```
- (void)categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex:(NSInteger)index {
    JXCategoryIndicatorImageView *indicatorImageView = (JXCategoryIndicatorImageView *)self.segmentView.indicators[0];
    CGFloat width = [categoryView preferredCellWidthAtIndex:index];
    width *= 1.3;
    indicatorImageView.indicatorImageViewSize = CGSizeMake(width, 50);
    [indicatorImageView jx_refreshState:CGRectMake(0, 0, width, 50)];
}
```

**Comment by feihuang89** [comment]
后来用JXCategoryIndicatorLineView  解决了
