### ISSUE TITLE
滚动位置时，怎么让标题对应到自己的控制器

### ISSUE THREAD

**Issue by Liyongcong** [pujiaxin33/JXCategoryView#62]

**Comment by pujiaxin33** [comment]
你参考下示例代码呢

**Comment by Liyongcong** [comment]
感觉用起来不是太方便，有点复杂

**Comment by Liyongcong** [comment]
可以参考下这个标题和控制器一对一的情况，感觉用起来比较直观方便SGPagingView:https://github.com/kingsic/SGPagingView

**Comment by pujiaxin33** [comment]
谢谢推荐，有空去拜读一下

**Comment by pujiaxin33** [comment]
@Liyongcong 我看了一下SGPagingView的源码，title是一个数组，childVCS一个数组，两个数组而以。跟我的思路是一样的，并没有什么一对一的概念。

**Comment by Liyongcong** [comment]
嗯，是的，但我感觉他那样的写法更直观，我看你的源码，有点摸不着头脑，不知道该怎么下手，感觉有点乱，估计是我技术不行吧，哈哈。

**Comment by pujiaxin33** [comment]
这个到没有这么夸张，每个库的实现逻辑不一样，写法不一样。每个人对不同库的看法也不一样，这跟技术没多大关系
