### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by BflyT** [pujiaxin33/JXCategoryView#64]
手机语言切换到阿拉伯语后，只有在一个标题的时候布局是对的，大于一个的方向都不对。阿拉伯语是从右往左的。

**Comment by pujiaxin33** [comment]
不好意思，该控件不支持阿拉伯语的从右往左

**Comment by BflyT** [comment]
如果要修改，可以在哪里修改适配

**Comment by pujiaxin33** [comment]
我也不知道啊，没有做过阿拉伯语言适配 -_-

**Comment by BflyT** [comment]
就是要改变布局，在base里面修改吗

**Comment by pujiaxin33** [comment]
collectionView在baseView里面
