### ISSUE TITLE
如果不指定self.edgesForExtendedLayout = UIRectEdgeNone;，显示会异常

### ISSUE THREAD

**Issue by wblzu** [pujiaxin33/JXCategoryView#68]

**Comment by pujiaxin33** [comment]
能截图一下

**Comment by pujiaxin33** [comment]
建议参考这篇文章[edgesForExtendedLayout浅淡](https://www.jianshu.com/p/ca3c5a94c32b)
如果你设置`self.edgesForExtendedLayout = UIRectEdgeAll;`那么vc.view就是整个屏幕了，你的视图布局就需要做调整，y值为0就是屏幕顶部，而不是导航栏底部了。
这个属性跟JXCategoryView无关，完全是视图布局所用！
