### ISSUE TITLE
仿汽车之家版本慢慢的滑动起来感觉有点卡顿的感觉

### ISSUE THREAD

**Issue by GeekZP** [pujiaxin33/JXCategoryView#69]
仿汽车之家版本慢慢的滑动，标题文字看起来感觉有点卡顿

**Comment by pujiaxin33** [comment]
主要是文字有位置的抖动现象，保存汽车之家也有这个问题。只是它的情况好些。这个目前优化不了，没得其他思路了。

**Comment by GeekZP** [comment]
有些APP这个样式滑动起来几乎看不出抖动，不知道他们的实现方式

**Comment by pujiaxin33** [comment]
还有哪些app呢？

**Comment by pujiaxin33** [comment]
现在已经修改为通过transform对字体进行缩放，不会有抖动问题了
