### ISSUE TITLE
ios12，iPhone5S偏移问题

### ISSUE THREAD

**Issue by chengongwen** [pujiaxin33/JXCategoryView#70]
![image](https://user-images.githubusercontent.com/9940006/50267743-35a83400-0463-11e9-96ea-766305a0db3d.png)

附上代码：
// 滑动菜单
    self.categoryView = [[JXCategoryTitleView alloc] init];
    self.categoryView.frame = CGRectMake(0, kNaviBarHeight, width , kSliderButtonHeadViewHeight);
    self.categoryView.delegate = self;
    self.categoryView.backgroundColor = kWhiteColor;
    self.categoryView.contentScrollView = self.scrollView;
    
    self.categoryView.titleFont = [UIFont systemFontOfSize:kScaleDesginMaxSize(15)];
    self.categoryView.averageCellSpacingEnabled = YES; // 均分categoryView
    self.categoryView.titles = titleDataList;
    self.categoryView.titleColor = kColorWithHex(@"83858A");
    self.categoryView.titleSelectedColor = kMasterColor;
    self.categoryView.titleColorGradientEnabled = YES;
    self.categoryView.titleLabelZoomEnabled = NO; // 选中放大效果
    
    JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
    lineView.indicatorLineWidth = JXCategoryViewAutomaticDimension;
    lineView.indicatorLineViewHeight = 2.0f;
    lineView.indicatorLineViewColor = kMasterColor;
    self.categoryView.indicators = @[lineView];
    [self.view addSubview:self.categoryView];
    [self.categoryView reloadData];

**Comment by pujiaxin33** [comment]
1、同样的代码，在其他系统有问题吗？
2、可以截图下视图层级吗？
3、你设置categoryView的宽度为kScreenWidth - 60，但是界面上确是满屏的，这是一个很大的疑点。

**Comment by chengongwen** [comment]
![image](https://user-images.githubusercontent.com/9940006/50268507-07782380-0466-11e9-964b-fe5d528fdc2d.png)

视图层级截图

**Comment by pujiaxin33** [comment]
同样的代码，在其他系统有问题吗？

**Comment by pujiaxin33** [comment]
截图这个你把宽度设置为和屏幕同宽了？

**Comment by chengongwen** [comment]
对，只有iPhone5S才有，iPhone 7plus，iPhone X都是正常的

上面的代码我改了：
self.categoryView.frame = CGRectMake(0, kNaviBarHeight, width , kSliderButtonHeadViewHeight);

**Comment by chengongwen** [comment]
![image](https://user-images.githubusercontent.com/9940006/50269250-adc52880-0468-11e9-815c-5013d31ebbf8.png)
![image](https://user-images.githubusercontent.com/9940006/50269268-bfa6cb80-0468-11e9-8a22-26738cfc848a.png)

**Comment by pujiaxin33** [comment]
能麻烦你用你的5s，跑一下我的demo吗？看看我的demo工程是否也有同样的问题

**Comment by pujiaxin33** [comment]
实现不行，你可以把相关代码拿出来，新建一个demo工程发给我，我看下问题。这个系统差异性问题，可能只有运行起来才能解决。如果需要可以加我的qq:317437084

**Comment by pujiaxin33** [comment]
确保加了下面的代码哟
```
self.automaticallyAdjustsScrollViewInsets = NO;
    if (@available(iOS 11.0, *)) {
        self.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    }
```

**Comment by QOIKINGCHUNG** [comment]
我也遇到这个问题了。
self.automaticallyAdjustsScrollViewInsets = NO;
    if (@available(iOS 11.0, *)) {
        self.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    }
这几行代码在哪里加？

**Comment by pujiaxin33** [comment]
加在UIViewController里面

**Comment by chengongwen** [comment]
floor(49.0f)); // 对高度向下取整即可,5s偏移的问题

**Comment by pujiaxin33** [comment]
@chengongwen 感谢的补充，确保JXCategoryView的frame是整数。不要是浮点数，类似于30.14939203940这种。

**Comment by QOIKINGCHUNG** [comment]
> floor(49.0f)); // 对高度向下取整即可,5s偏移的问题
谢谢指点，确实按你说的解决了问题。

**Comment by QOIKINGCHUNG** [comment]
> @chengongwen 感谢的补充，确保JXCategoryView的frame是整数。不要是浮点数，类似于30.14939203940这种。

我看了半天您的代码，然而没发现代码有问题。没想到是frame😆，问题已解。
