### ISSUE TITLE
非第一个子页面Push,Present返回之后,页面自动回滚到第一个View,标题还保持在子View 对应标题

### ISSUE THREAD

**Issue by ZZKll** [pujiaxin33/JXCategoryView#72]
非第一个子页面Push,Present返回之后,页面自动回滚到第一个View,标题还保持在子View 对应标题

**Comment by pujiaxin33** [comment]
你是用demo测试的结果吗？

**Comment by ZZKll** [comment]
不是 ,我自己写的.我把self.categoryView.contentScrollView = self.bigScrollView; 这个self.bigScrollView 写成懒加载了,它就会自动回到第一个.现在改了,就好了 . 请教一下,这是啥原因 ?

**Comment by pujiaxin33** [comment]
不知道啊
