### ISSUE TITLE
支持默认不选中cell吗

### ISSUE THREAD

**Issue by pianxian** [pujiaxin33/JXCategoryView#74]
项目中遇到需要默认不选中cell 的需求 源码里defaultSelectedIndex默认为0 默认就选中了第一个

**Comment by pujiaxin33** [comment]
没有任何一个被选中，这是什么状态。

**Comment by pianxian** [comment]
比如说 有一个列表 是 进行中 已完成 项目需求是 初次进入这个页面是要加载全部 就不能选中进行中和已完成 然后点击进行中或者已完成再加载对应的数据，我是在本地的源码里添加了一个defaultSelectedIndex为-1的状态暂时实现了那个需求 不知道作者有没别的好的方法

**Comment by pujiaxin33** [comment]
依然不太明白产品的要求。这种及其特殊自己fork处理吧，如果把这个引入库里面，只会增加使用复杂度。

**Comment by Au12th0psav** [comment]
我也遇到类似的需求了。我的解决方案是设置normal和selected的属性一模一样，通过index小于零时，再特殊处理。

**Comment by humbleAna** [comment]
> 比如说 有一个列表 是 进行中 已完成 项目需求是 初次进入这个页面是要加载全部 就不能选中进行中和已完成 然后点击进行中或者已完成再加载对应的数据，我是在本地的源码里添加了一个defaultSelectedIndex为-1的状态暂时实现了那个需求 不知道作者有没别的好的方法

大佬咋改的
