### ISSUE TITLE
JXCategoryListContainerView 修改 frame 

### ISSUE THREAD

**Issue by zhaoxuezhi** [pujiaxin33/JXCategoryView#75]
JXCategoryListContainerView 修改了 frame ，添加到 scrollView 上的子 view frame没有跟随改变，希望可以重写 frame 方法

**Comment by YanPengImp** [comment]
现在的是在第一次layoutSubviews的时候会去对当前的子view设置frame。你是想要在后续自己重新修改JXCategoryListContainerView的frame的时候也修改子view的frame吗

**Comment by zhaoxuezhi** [comment]
是的呢，还有就是 JXCategoryListContainerView 不能传入自定义 scrollview，因此不能手势滑动返回上个页面

**Comment by pujiaxin33** [comment]
@zhaoxuezhi 把scrollView设置为readwrite这个方案风险很大。新建一个初始化方法：`- (instancetype)initWithParentVC:(UIViewController *)parentVC delegate:(id<JXCategoryListContainerViewDelegate>)delegate scrollViewClass:(class)scrollViewClass;`，允许传入一个自定义UIScrollView的class。你觉得这样子可以解决你的需求不？

**Comment by pujiaxin33** [comment]
> JXCategoryListContainerView 修改了 frame ，添加到 scrollView 上的子 view frame没有跟随改变，希望可以重写 frame 方法

这个问题已经修改了

**Comment by zhaoxuezhi** [comment]
> @zhaoxuezhi 把scrollView设置为readwrite这个方案风险很大。新建一个初始化方法：`- (instancetype)initWithParentVC:(UIViewController *)parentVC delegate:(id<JXCategoryListContainerViewDelegate>)delegate scrollViewClass:(class)scrollViewClass;`，允许传入一个自定义UIScrollView的class。你觉得这样子可以解决你的需求不？

可以的，我这边采用的临时解决方案是继承 JXCategoryListContainerView ，重写了 setFrame 和 initializeViews 方法，通过 KVC 给scrollView 赋值一个自定义的 scrollView

**Comment by pujiaxin33** [comment]
自定义scrollView最终方案为，新增下面的代理方法：
```
/**
 返回自定义UIScrollView实例
 某些特殊情况需要自己处理UIScrollView内部逻辑。比如项目用了FDFullscreenPopGesture，需要处理手势相关代理。

 @param listContainerView JXCategoryListContainerView
 @return 自定义UIScrollView实例
 */
- (UIScrollView *)scrollViewInlistContainerView:(JXCategoryListContainerView *)listContainerView;
```

**Comment by RCLOVETMH** [comment]
> scrollViewClass

大佬，请问你是怎么FDFullscreenPopGesture手势滑动的， 我JXCategoryListContainerViewDelegate这个代理一直不调用，请教一下大佬
