### ISSUE TITLE
发现第一个cell的下划线，宽度会变化一下

### ISSUE THREAD

**Issue by LinJiaXing1102** [pujiaxin33/JXCategoryView#76]
视乎宽度会少掉1pt，我是设置了圆角，滑到第二个cell的时候就恢复正常，可以在第一个cell和第二个
cell间滑动测试一下，好像第一个cell的下划线右侧会少掉一些

**Comment by YanPengImp** [comment]
具体是哪种样式出现的这种情况呢？下划线固定宽度的那种还是和cell等宽但是你两个cell的字是一样多？

**Comment by YanPengImp** [comment]
能否看下你是怎么设置indicators的吗，如果设置的固定长度，应该是不会变化的。我也按照你说的设置3个视图来回滑动没有复现。

**Comment by LinJiaXing1102** [comment]
我用的是最新的Demo直接测试,只是设置了高度

```objc
//固定宽度
testVC.isNeedIndicatorPositionChangeItem = YES;
titleCategoryView.titleColorGradientEnabled = YES;
JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
lineView.indicatorLineWidth = 40;
lineView.indicatorLineViewHeight = 20;
titleCategoryView.indicators = @[lineView];
```
具体操作可看下图，可明显看到第一个cell的下划线，当停止滑动后，宽度突然变小了一点
![image](https://ios-1257939908.cos.ap-shanghai.myqcloud.com/Jietu20190109-150504-HD.gif)

**Comment by YanPengImp** [comment]
原谅我不是UI，没有看出有啥差别，我也按照你设置的然后打印了frame，看到宽度没有变化，不知道是不是iOS11上会有问题，我下个11的模拟器再看一下，你试下其他系统的看还有你说的问题吗,或者你下载源码在里面自己打印看下frame的变化。

**Comment by LinJiaXing1102** [comment]
输出的frame是没有问题的，就是在屏幕上面显示就会出现这个小问题，而且有且仅有在三个控制器的时候

6s iOS12.1 和 iOS11.4 都出现

输出控件的frame没问题，但是屏幕上看就会这样 我也自己看了半天没发现哪里出现问题

**Comment by LinJiaXing1102** [comment]
可能这个gif不清晰，不过你仔细看这个gif的第24 和 25 张，会发现有一些轻微的变化，我看能不能搞个高清的

**Comment by YanPengImp** [comment]
看了24和25的图，25相对于24其实左右两边都往左移动了一小段距离。在模拟器上渲染会有一点失真，你试下在真机上跑呢。

**Comment by LinJiaXing1102** [comment]
我也有在真机上试过，也是一样，本来以为是宽度被改变了，打了断点发现并没有，就是找不出问题的点出在哪里

**Comment by YanPengImp** [comment]
那这个问题就有点玄学了，你设置宽度为其他值看会不会有同样的问题

**Comment by LinJiaXing1102** [comment]
其他也是一样，而且好像还不是移动一段距离，而是直接切掉。
因为我设置了圆角，明显感觉到右侧的半圆 不圆

**Comment by YanPengImp** [comment]
我盯着那个线条一直看，眼睛都看花了还是没看出啥东西。不好意思哈，可能有点帮不到你了。☺
