### ISSUE TITLE
调用 [self.myCategoryView selectItemAtIndex:2]; 不起作用

### ISSUE THREAD

**Issue by Antduo** [pujiaxin33/JXCategoryView#77]
当我用上面的方法，默认选中2时，似乎没有作用

**Comment by Xianyus** [comment]
> 有具体的代码逻辑吗，默认选中的话是defaultSelectedIndex，然后你调用你上面代码的时机是什么时候呢。
在该demo中 DotViewController 类里面，调用该方法
```
#import "DotViewController.h"
#import "JXCategoryDotView.h"

@interface DotViewController () <JXCategoryViewDelegate>
@property (nonatomic, strong) NSMutableArray *dotStates;
@property (nonatomic, strong) NSArray *titles;
@property (nonatomic, strong) JXCategoryDotView *myCategoryView;
@end

@implementation DotViewController

- (void)viewDidLoad {
    _titles = @[@"螃蟹", @"麻辣小龙虾", @"苹果", @"营养胡萝卜", @"葡萄", @"美味西瓜", @"香蕉", @"香甜菠萝", @"鸡肉", @"鱼", @"海星"];

    [super viewDidLoad];

    UIBarButtonItem *reloadItem = [[UIBarButtonItem alloc] initWithTitle:@"刷新" style:UIBarButtonItemStylePlain target:self action:@selector(reloadDot)];
    self.navigationItem.rightBarButtonItem = reloadItem;

    _dotStates = @[@YES, @YES, @NO, @NO, @YES, @YES, @YES, @NO, @YES, @YES, @NO].mutableCopy;

    self.myCategoryView.titles = self.titles;
    self.myCategoryView.dotStates = self.dotStates;
    
    [self.myCategoryView selectItemAtIndex:2];
    JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
    self.myCategoryView.indicators = @[lineView];
}
```

**Comment by pujiaxin33** [comment]
初始化的时候，通过defaultSelectedIndex指定默认index。这个时候selectItemAtIndex方法不会起作用。
初始化之后，通过交互可以通过selectItemAtIndex切换index

**Comment by wufengshou** [comment]
设置初始化下标无效

**Comment by wufengshou** [comment]
}else if ([title isEqualToString:@"Cell背景色渐变"]) {

        TitleViewController *testVC = [[TitleViewController alloc] init];
        testVC.title = title;
        JXCategoryTitleView *titleCategoryView = (JXCategoryTitleView *)testVC.categoryView;
        titleCategoryView.titleColorGradientEnabled = YES;
        titleCategoryView.cellBackgroundColorGradientEnabled = YES;
        titleCategoryView.cellSpacing = 0;
        titleCategoryView.cellWidthIncrement = 20;
        titleCategoryView.defaultSelectedIndex = 3;
        testVC.myCategoryView.defaultSelectedIndex = 3;
//        [testVC.myCategoryView selectItemAtIndex:3];
//        [testVC.listContainerView didClickSelectedItemAtIndex:3];
我在github下载的demo  通过以上方式 无法设置下标

**Comment by pujiaxin33** [comment]
selectItemAtIndex方法不是初始化的时候用，而是用户点击了某个自定义按钮，通过代码进行切换。
而且只需要调用`[testVC.myCategoryView selectItemAtIndex:3];`这一句。不需要调用`[testVC.listContainerView didClickSelectedItemAtIndex:3];`

**Comment by wufengshou** [comment]
你好  我直接设置  defaultSelectedIndex = 3 也是无效的  跟下标有关的都尝试了  但是都没有成功

**Comment by pujiaxin33** [comment]
是demo基类ContentBaseViewController重载了index，我刚修复了，你更新下仓库即可
