### ISSUE TITLE
子vc用xib创建，在viewDidLoad中不能得到正确的布局，想问下有解决的方法吗？？

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXCategoryView#80]
子vc用xib创建，在viewDidLoad中不能得到正确的布局，想问下有解决的方法吗？？
在viewDidLoad中布局，不能得到view正确的frame。。
![simulator screen shot - iphone xs max - 2019-01-14 at 14 41 03](https://user-images.githubusercontent.com/16876013/51099256-a3e5d980-180a-11e9-9b06-33651b51e892.png)

**Comment by ptlCoder** [comment]
-(void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
}
在这里面布局

**Comment by pujiaxin33** [comment]
@ptlCoder 感谢你的回答，感谢和该提问者沟通。确实是tableView自身的布局问题。已提供解决方法修复了

**Comment by daobao777** [comment]
请问下具体怎么解决的，现在同样碰到这个问题
