### ISSUE TITLE
有很多代码是没有必要的

### ISSUE THREAD

**Issue by YanweiLi** [pujiaxin33/JXCategoryView#86]
比如：
- (void)mainTableViewDidScroll:(UIScrollView *)scrollView 函数中的
``CGFloat topContentY = [self getTopContentHeight];
    if (scrollView.contentOffset.y >= topContentY) {
        //当滚动的contentOffset.y大于了指定sectionHeader的y值，且还没有被添加到self.view上的时候，就需要切换superView
        if (self.pinCategoryView.superview != self) {
            [self addSubview:self.pinCategoryView];
        }
    }else if (self.pinCategoryView.superview != self.listContainerCell.contentView) {
        //当滚动的contentOffset.y小于了指定sectionHeader的y值，且还没有被添加到sectionCategoryHeaderView上的时候，就需要切换superView
        [self.listContainerCell.contentView addSubview:self.pinCategoryView];
    }

1. 我只需要控制 mainTableView 的大小，自然就可以控制 pinCategoryView 的位置。
2. tab 切换的时候，太多改变 scroll view 的代码了。 建议收敛一下，这样子代码更加简洁。

**Comment by pujiaxin33** [comment]
1、你上面复制的代码，是`VerticalListViewController`示例里面的，知道你怎么放到`mainTableViewDidScroll`方法里面去了。
2、 pinCategoryView就是放在tableView的headerView里面的，自然要指定pinCategoryView的大小。
3、
> tab 切换的时候，太多改变 scroll view 的代码了。 建议收敛一下，这样子代码更加简洁。
不知道你说的具体是那一块代码？
