### ISSUE TITLE
JXCategoryListVCContainerView  没有复用机制内存有爆掉的风险。

### ISSUE THREAD

**Issue by QOIKINGCHUNG** [pujiaxin33/JXCategoryView#87]
JXCategoryListVCContainerView 这个类是用UIScrollView实现的吗？
UIScrollView 没有复用机制，作者能不能用collectionview来实现一遍呢？
我遇到的场景是这样的，我有很多个item，每个item是个tableview，都放进JXCategoryListVCContainerView里，跟你的demo类似，但是如果item多了内存有爆掉的风险。

实现了这个delegate：
` - (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index`

图片是您的demo：

![f64a5def-63ee-4007-87bd-4688d562c56e](https://user-images.githubusercontent.com/11383308/52761649-256d9900-304f-11e9-8bb3-7227d96d368d.png)

**Comment by pujiaxin33** [comment]
1.JXCategoryListVCContainerView类已经被弃用删除了，新版本请使用JXCategoryListContainerView；
2.你要知道UICollectionView的复用机制，就是cell的UI模板是固定的，只是不同的index用不同的数据去赋值给页面。即使JXCategoryListContainerView用UICollectionView实现，也避免不了内存问题。因为实际情况每个列表的UI布局不可能完全一样（除个别情况列表都一个造型，只是数据不同，但是因为是开源库，肯定要照顾到任何情况）。所以，每个列表是一个单独的实例，列表之间是不能复用的。
3.因为JXCategoryListContainerView采用了懒加载的形式，显示到对应index才会加载对应列表，所以内存大部分情况比较乐观。即使全部加载完毕，我们项目最多有20多个页面的情况，内存也没有爆，具体你可以自测看下内存增长情况。

**Comment by QOIKINGCHUNG** [comment]
1.抱歉是我编辑问题的时候写错了，我项目用的是JXCategoryListContainerView。
2.我的意思是想达到复用的效果，不是复用也行至少把不在显示区域的实例释放调，不一定用UICollectionView，只是觉得UICollectionView本身有复用机制，实现起来会不会简单些。我现在在尝试把超越当前index 1个（或n个）位置的实例释放掉，所有以后整个UIScrollView上面最多只有3个（或2n+1个）实例，但是我遇到的问题是下面的delegate懒加载才会触发
`- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index`
作者对我这样做有什么建议吗？
3.其实我的项目不会有什么大问题，也有不少页面。但是确实是懒加载一个内存多一点懒加载一个内存又多一点，但是总体还是乐观的。

**Comment by pujiaxin33** [comment]
你想要的效果是不是，当前显示的A列表，切换到B的时候，A没有显示了，就把A给释放掉。其他同理，这样子显示某一个列表的时候，其他列表都没有了，也就没有内存问题了。
那么，请问你如果保存之前列表的状态呢？难道每次切换列表都要重新alloc，然后请求网络加载数据？
所以，你说想要的cell复用机制，在这里对于每个列表的状态都需要保存的情况，已经不适用了！

**Comment by QOIKINGCHUNG** [comment]
是的每次换列表都要重新alloc，你懒加载的时候不是也alloc了吗，alloc消耗感觉不会太大，我在我的项目里面没有感觉alloc有很大消耗。因为JXCategory切换的时候是一个一个切换的，并不是像tableview一样一列刷新的，然后服务器请求到的数据可以保存（我说的保存不是plist或者沙盒，而是用变量，数组之类），数据不需要每次拿，每列的只拿一次（我的项目是一开始就拿到所有数据了，没有做分页，但是分页也是同理）

**Comment by pujiaxin33** [comment]
那你的数据也是一大坨内存啊，还有关键的一点，你仅保存了数据，没有保存页面的状态。比如某个列表用户操作了一些，最简单的就是滚动的距离。所有其他页面可以点击之类的控件。你重新创建之后，之前的页面状态没了，用户直接懵逼。

**Comment by pujiaxin33** [comment]
还有一个选择，你可以使用列表自定义，进行自己控制加载逻辑。
最后再表达一下我的观点，列表和cell不一样。cell是一套UI模板，数据不同而已，可以复用。但是每个列表是不一样，不仅是UI样式，还有它的操作状态。当然有内存问题，但并不能因为内存问题忽略了用户体验和增加一些特别复杂的列表状态恢复机制。

**Comment by pujiaxin33** [comment]
好吧，刚才测试了一下UICollectionView的方案，内存控制确实要好的多，后续版本会加入进来。我一直关注的是列表实例变量的内存。但是还有View实例的内存。用UIScrollView，所有的列表view都会被添加进去。但是UICollectionView只会在显示的时候进行添加。所以主要差别在view内存这一块。

**Comment by pujiaxin33** [comment]
你好，针对内存这一块，新增了`JXCategoryListCollectionContainerView`类

- 有了`JXCategoryListContainerView`为什么还要`JXCategoryListCollectionContainerView`类呢？
    - 因为`JXCategoryListContainerView`内部使用的是`UIScrollView`，当所有列表都加载出来后，所有的列表都被addSubview到`UIScrollView`上面了。所以，在视图内存这一块会比较大，对于一些列表复杂且数量多的应用，内存表现不太好。

- `JXCategoryListCollectionContainerView`的优势
    - 只有当前显示的列表才会被addSubview，视图内存表现良好；
    - 因为内部使用`UICollectionView`，在api设计上更加简洁；

具体使用示例，点击参看[JXCategoryListCollectionContainerView使用示例](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/JXCategoryListCollectionContainerView%E4%BD%BF%E7%94%A8.md)
