### ISSUE TITLE
指定了self.categoryView.cellWidth的宽度, 当文字过多时, 不会换行

### ISSUE THREAD

**Issue by Xianyus** [pujiaxin33/JXCategoryView#88]
由于项目涉及到国际化, 有些语言标题会很长, 建议作者暴露出一个numberOfLine的属性

**Comment by pujiaxin33** [comment]
目前因为设置numberOfLine为多行的话，会应该许多其他问题，尤其是同时大小缩放。所以，需要等段时间才能支持

**Comment by pujiaxin33** [comment]
1.2.7版本新增了titleNumberOfLines属性。
通过设置JXCategoryTitleView的titleNumberOfLines属性为指定行数，比如2就是显示两行。但是因为内部实现原理限制，目前暂不支持自动换行，需要自己插入\n换行符。详情请参考【多行文本】使用示例。
