### ISSUE TITLE
个人主页列表获取navigationController的方式

### ISSUE THREAD

**Issue by CoderST** [pujiaxin33/JXCategoryView#90]
大神您好,看了issues的问题,有的朋友也问了 像在特殊效果->个人主页中点击cell去拿导航控制器的问题

自定义VC后,拿不到导航控制器, 我看你的建议是把导航控制器传递给子类.

但是目前项目中部分写的是通过view获取当前控制器,然后直接拿导航,(在UIView分类中获取viewController,然后在UIView中self.viewController.navigationController)

不知道大神可否考虑写这个问题,如果实在牵扯很多,不好弄,那就暂时用你建议的方法去处理.

希望能收到您的答复,谢谢~~

**Comment by pujiaxin33** [comment]
能看下你的分类具体代码么？

**Comment by CoderST** [comment]
- (UIViewController *)viewController {
    UIResponder *next = [self nextResponder];
    do {
        if ([next isKindOfClass:[UIViewController class]]) {
            return (UIViewController *)next;
        }
        next = [next nextResponder];
    } while (next != nil);
    return nil;
}
这个是分类的方法.

**Comment by pujiaxin33** [comment]
顺着你的思路我写了一个分类，代码如下：
```Objective-C
- (UINavigationController *)naviResponder {
    UIResponder *next = self.nextResponder;
    UINavigationController *navi = nil;
    while (navi == nil) {
        if ([next isKindOfClass:[UINavigationController class]]) {
            navi = (UINavigationController *)next;
        }
        next = next.nextResponder;
    }
    return navi;
}
```
我测试了一下，可行。但是我并不建议这么做。因为分类就面对所有的UIView，而且并不一定获取到导航控制器。所以我还是建议，通过属性传递。
