### ISSUE TITLE
Demo中隔个人主页发现问题

### ISSUE THREAD

**Issue by CoderST** [pujiaxin33/JXCategoryView#91]
我在个人主页中创建自己的子VC,把当前的nav赋值给子vc

当我在子vc中push到MYViewController时,发现在子vc的生命周期会走两边
- (void)viewDidDisappear:(BOOL)animated{  // 走两遍
    [super viewDidDisappear:animated];
}

- (void)viewWillDisappear:(BOOL)animated{ // 走两遍
    [super viewWillDisappear:animated];
}

在从MYViewControllerpop返回时候  在子vc中没有走生命周期方法

请问下,不知道是怎么回事,烦请看一下

**Comment by pujiaxin33** [comment]
个人主页效果请看[JXPagingView](https://github.com/pujiaxin33/JXPagingView)  在最新1.0.8版本添加了列表的显示和消失的生命周期方法；
再强调一些：
- JXPagingView和JXCategoryView的列表容器实现逻辑不一样。
- 不要依赖VC系统自带的生命周期方法，这些api在该场景不可靠，反正你要用它们就行。
- 需要依赖自定义的列表显示和消失的方法。
- 具体使用示例请仔细参考示例。
