### ISSUE TITLE
你好，在实际项目中对比其他框架内存稍微有点高，是否有可优化空间？

### ISSUE THREAD

**Issue by DotaAntiMagic** [pujiaxin33/JXCategoryView#92]
你好，我在项目中使用JXCategoryView,手动滑动加载完所有控制器后，对比其他类似框架(WMPageController,TYPagerController)内存加载完毕要多个10M左右,请问下是否还有可优化的空间？

**Comment by YanPengImp** [comment]
感谢您提出的宝贵建议，看了你提出的两个库，我们在后续版本中会加入对内存控制的处理。

**Comment by pujiaxin33** [comment]
你好，针对内存这一块，新增了`JXCategoryListCollectionContainerView`类

- 有了`JXCategoryListContainerView`为什么还要`JXCategoryListCollectionContainerView`类呢？
    - 因为`JXCategoryListContainerView`内部使用的是`UIScrollView`，当所有列表都加载出来后，所有的列表都被addSubview到`UIScrollView`上面了。所以，在视图内存这一块会比较大，对于一些列表复杂且数量多的应用，内存表现不太好。

- `JXCategoryListCollectionContainerView`的优势
    - 只有当前显示的列表才会被addSubview，视图内存表现良好；
    - 因为内部使用`UICollectionView`，在api设计上更加简洁；

具体使用示例，点击参看[JXCategoryListCollectionContainerView使用示例](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/JXCategoryListCollectionContainerView%E4%BD%BF%E7%94%A8.md)

**Comment by pujiaxin33** [comment]
并且会在内存警告的时候，清除当前未显示的缓存列表
