### ISSUE TITLE
你好能否新增顶部对齐样式，如下图：

### ISSUE THREAD

**Issue by xiaojiguang** [pujiaxin33/JXCategoryView#93]
![wechatimg3](https://user-images.githubusercontent.com/11371184/53313769-e6b0cc00-38f5-11e9-898a-387f9cdf220a.jpeg)

**Comment by pujiaxin33** [comment]
有参考的app吗，需要体验这个效果的细节

**Comment by xiaojiguang** [comment]
截图app是《皮皮虾》是顶部对齐，《脉脉》是底部对齐

**Comment by pujiaxin33** [comment]
好的

**Comment by Share-Yida** [comment]
哪个放大镜哪里用什么方法实现呢

**Comment by pujiaxin33** [comment]
放大镜就是另一个按钮而已，和categoryView同为UIViewController的子视图

**Comment by pujiaxin33** [comment]
1.2.8版本新增JXCategoryTitleLabelAnchorPointStyle属性，支持顶部或者底部对齐。

**Comment by uclort** [comment]
> 1.2.8版本新增JXCategoryTitleLabelAnchorPointStyle属性，支持顶部或者底部对齐。

请问 Swift 版本是否支持这个属性？
