### ISSUE TITLE
title不滚动

### ISSUE THREAD

**Issue by lztbwlkj** [pujiaxin33/JXCategoryView#94]
底部的JXCategoryBaseView的contentScrollView关联可以滑动，但是顶部的JXCategoryTitleView怎么也不动，我按照demo中的将JXCategoryTitleView *titleCategoryView = (JXCategoryTitleView *)testVC.categoryView;运行起来说是找到不titles方法 第一次使用，有点纠结。。好像titleView和底部滚动的view没关联起来

**Comment by pujiaxin33** [comment]
请问你是在开发嵌套效果吗？

**Comment by lztbwlkj** [comment]
那个问题解决了。请问滚动的列表是继承与UITableViewController，但是cell点击无效了。 我代码是将你的Demo中的ContentBaseViewController类copy到项目中然后继承，和你demo中的用法一样

**Comment by pujiaxin33** [comment]
- 滚动的列表只是包含有UIScrollView及其子类即可；
- cell点击无效的具体含义？是didSelectedRow方法没有调用？还是调用了里面的跳转代码没有生效？
- 尽量不要直接用示例工程的类，里面耦合了其他逻辑，你需要什么再拷贝什么代码即可

**Comment by lztbwlkj** [comment]
你好，点击后是跳转代码没有生效

**Comment by pujiaxin33** [comment]
答案在这里[其他注意事项](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/%E4%BD%BF%E7%94%A8%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.md)

点击cell跳转章节

**Comment by lztbwlkj** [comment]
![wechateef678ec54ceaca4f9a5b1acd0243b05](https://user-images.githubusercontent.com/20568661/53539544-ea8a5b80-3b4c-11e9-91ee-febd0d22b632.png)
这样子创建JXCategoryTitleView和JXCategoryBaseView有什么不对吗，为什么JXCategoryIndicatorLineView滚动而JXCategoryTitleView的文字不动,

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/53544361-c20c5c80-3b60-11e9-862c-bdd53c699255.png)
把红框的self.categoryView修改为self.titlesCategoryView即可。

**Comment by lztbwlkj** [comment]
在1的区域内测滑手势可以返回上级，在2的区域内测滑不能返回上级界面，不知道这个该怎么处理？也看了你的《侧滑手势处理说明文档》
![we](https://user-images.githubusercontent.com/20568661/53545512-ab680480-3b64-11e9-8717-1b3f014e572f.png)

**Comment by pujiaxin33** [comment]
请再按照文档多试验一下，或者自己google多了解相关资料。
