### ISSUE TITLE
reload重载导致iPhone X下面没有安全间距

### ISSUE THREAD

**Issue by Yangshaoyi** [pujiaxin33/JXCategoryView#96]
self.categoryView.defaultSelectedIndex = self.selectIndex;
        [self.categoryView reloadData];

        self.listContainerView.defaultSelectedIndex = self.selectIndex;
        [self.listContainerView reloadData];
重载导致iPhone X下面没有安全间距

**Comment by pujiaxin33** [comment]
建议先使用`JXCategoryListCollectionContainerView`类，该类自测没有安全间距问题。之前的问题，目前还在研究中

**Comment by pujiaxin33** [comment]
目前发现列表是UIViewController类封装的有问题，列表用UIView封装的没有问题。

**Comment by VikBob** [comment]
我项目有个需求 需要弹出一个view里面是btn btn事件要做到和点击titleview点击或移动的效果一样，最开始使用reloaddata各种闪屏问题，之后增加一个方法模拟点击事件效果 代码和点击事件代码一样。 效果是达到了，应该没后续问题。

**Comment by AnnyName** [comment]
> 建议先使用`JXCategoryListCollectionContainerView`类，该类自测没有安全间距问题。之前的问题，目前还在研究中

如果.defaultSelectedIndex = 1 会看到还是没有安全区域

**Comment by pujiaxin33** [comment]
我再来总结一下：
1、使用`JXCategoryListCollectionContainerView`类不会有底部安全边距问题；
2、列表使用`UIView`封装不会有底部安全边距问题；
3、列表使用`UIViewController`封装有底部安全边距问题，添加代码` [self addChildViewController:listVC];`即可避免，完整代码如下：
```Objective-C
- (id<JXCategoryListContentViewDelegate>)listContainerView:(JXCategoryListContainerView *)listContainerView initListForIndex:(NSInteger)index {
    LoadDataListContainerListViewController *listVC = [[LoadDataListContainerListViewController alloc] init];
    listVC.naviController = self.navigationController;
    //如果列表是UIViewController包裹的，需要添加addChildViewController代码，这样子在iPhoneX系列手机就不会有底部安全距离错误的问题！！！
    [self addChildViewController:listVC];
    return listVC;
}
```
