### ISSUE TITLE
请问为什么我在用uitableview作为JXCategoryListContainerView子界面的时候会出现第三个界面是空白的  其他的界面是正常的

### ISSUE THREAD

**Issue by noahxinhao** [pujiaxin33/JXCategoryView#97]

**Comment by pujiaxin33** [comment]
1、确定第三个列表内部的加载逻辑是否触发？
2、查看第三个列表的视图层级及frame
3、再参考demo里面的用法，细节排除一边

**Comment by pujiaxin33** [comment]
如果是初次加载指定默认页面，需要把categoryView.defaultSelectedIndex和listContainerView.defaultSelectedIndex都设置为同一个值
