### ISSUE TITLE
设置下标无效

### ISSUE THREAD

**Issue by wufengshou** [pujiaxin33/JXCategoryView#99]
}else if ([title isEqualToString:@"Cell背景色渐变"]) {

    TitleViewController *testVC = [[TitleViewController alloc] init];
    testVC.title = title;
    JXCategoryTitleView *titleCategoryView = (JXCategoryTitleView *)testVC.categoryView;
    titleCategoryView.titleColorGradientEnabled = YES;
    titleCategoryView.cellBackgroundColorGradientEnabled = YES;
    titleCategoryView.cellSpacing = 0;
    titleCategoryView.cellWidthIncrement = 20;
    titleCategoryView.defaultSelectedIndex = 3;
    testVC.myCategoryView.defaultSelectedIndex = 3;
// [testVC.myCategoryView selectItemAtIndex:3];
// [testVC.listContainerView didClickSelectedItemAtIndex:3];
我在github下载的demo 通过以上方式 无法设置下标

**Comment by pujiaxin33** [comment]
是demo基类ContentBaseViewController重载了index，我刚修复了，你更新下仓库即可

**Comment by wufengshou** [comment]
你好  我设置defaultSelectedIndex = 3 可以跳转到第三页 但是view好像没加载出来

**Comment by pujiaxin33** [comment]
需要添加
listContainerView. defaultSelectedIndex = 3
